### ISSUE TITLE
[upbibtex] pbibtex と upbibtex の substring 命令の違い

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#1]
これは [forum:2006](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2006) からの抜粋です。

> この `substring$` 関数の引数として日本語の文字列を与えた場合に、pbibtex とupbibtex で結果が変わってしまいます。
> 例えば、pbibtex では
> `"あいうえお" #-1 #1 substring$`
> は「お」を返しますが、upbibtex では返ってくる文字列が文字化けしてしまいます。

テストケースなどは forum に添付されています。また、[forum:1886](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1886) というのもありました。

**Comment by t-tk** [comment]
遅くなりましたが、現象をようやく理解しました。dd80645 のコミットで修正を試みました。
forum:1886, forum:2006 の両方の事例ともに対応出来たと思います。
ついでに内部コードのdefaultをutf8に戻したいと思います。
追試していただけると助かります。

武田さんの情報↓が大変参考になりました。
ftp://ftp.yzu.edu.tw/CTAN/biblio/pbibtex/base/jbtxhak.pdf

> 調整は開始位置が漢字コードの1 バイト目に一致していれば．開始位置はそのまま，
> 2 バイト目であれば1 バイト目から取り出すように調整する．
> 終了位置が漢字コードの1 バイト目であれば2 バイト目まで取り出すように調整する．
> したがって指定した長さより最大2 バイト長い文字列となる．
>
> これは日本語用でないスタイルファイルを使った場合でもそれなりの出力が得られるようにするためである．

upbibtexでは、以下のようになったはずです。
2~4 バイト目であれば1 バイト目から取り出すように調整する．
終了位置が漢字コードの1 バイト目であれば2~4 バイト目まで取り出すように調整する．
したがって指定した長さより最大8 バイト長い文字列となる．

バイト数単位でカウントしているため、内部EUCと内部UTF-8の出力を同等にするのは難しいです。
もし揃えようとするならもっと根本から修正する必要が出てきますが、
そこまでやるまでも無いように思います。

**Comment by t-tk** [comment]
Markdownの文法ミスで、思わぬ打ち消し線が入ってしまいました。
バイト数も間違っていました。もう一度書き込みます。

upbibtexでは、以下のようになったはずです。
> 2〜4 バイト目であれば1 バイト目から取り出すように調整する．
> 終了位置が漢字コードの1 バイト目であれば2〜4 バイト目まで取り出すように調整する．
> したがって指定した長さより最大6 バイト長い文字列となる．

**Comment by aminophen** [comment]
win32 でビルドして試してみました。

biblatex のバックエンドとしての動作が ok になっていました。また、Takeda Shiro さんのテストケース `run_bibtex.bat` を「TeX Live 2015 frozen のもの」と「今回の開発版」で走らせたときの差分も

~~~~ patch
diff -urxN 120-utf/test_upbibtex.blg 122-utf/test_upbibtex.blg
--- 120-utf/test_upbibtex.blg	Sun Jan 15 00:25:09 2017
+++ 122-utf/test_upbibtex.blg	Sun Jan 15 00:18:36 2017
@@ -1,5 +1,5 @@
-This is upBibTeX, Version 0.99d-j0.33-u1.20 (utf8.uptex) (TeX Live 2015/W32TeX)
-Capacity: max_strings=35307, hash_size=35307, hash_prime=30011
+This is upBibTeX, Version 0.99d-j0.33-u1.22 (utf8.uptex) (TeX Live 2016/W32TeX)
+Capacity: max_strings=100000, hash_size=100000, hash_prime=85009
 The top-level auxiliary file: test_upbibtex.aux
 The style file: jplain_alt.bst
 Database file #1: test.bib
diff -urxN 120-utf/test_upbibtex.bbl 122-utf/test_upbibtex.bbl
--- 120-utf/test_upbibtex.bbl	Sun Jan 15 00:25:09 2017
+++ 122-utf/test_upbibtex.bbl	Sun Jan 15 00:18:36 2017
@@ -1,9 +1,9 @@
 \verb|substring$| の動作 \\
 \\
-\noindent あいうえおの最後の1文字 = 「」
+\noindent あいうえおの最後の1文字 = 「お」
 \\ あいうえおの最後の2文字 = 「お」
 \\ あいうえおの最後の3文字 = 「お」
-\\ あいうえおの最後の4文字 = 「お」
+\\ あいうえおの最後の4文字 = 「えお」
 \\ あいうえおの最後の5文字 = 「えお」
 \\ あいうえおの最後の6文字 = 「えお」
 \\ abcdefの最後の1文字 = 「f」
~~~~

となっていて、意図どおりになっているように見えます。
