### ISSUE TITLE
[(u)pTeX] \endlinechar=-1 のときの挙動

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/tex-jp-build#10]
devel ではすでに流しましたが，

> https://twitter.com/aminophen/status/848164588969381888
> https://twitter.com/zr_tex8r/status/848147077519482880

において，\endlinechar=-1 のときの (u)pTeX のおかしな挙動が観測されています．

 * 行が `\あ` のような和文の1文字命令で終わる場合，`Undefined control sequance` のエラーが出ます．WEB ソースをみるに，「あ」の UTF-8 の先頭バイト E3 を使った `\^^e3` と解釈してしまっているようです．
 * upTeX で，行が和文文字で終わる場合，それが欧文（単なるバイト列）扱いとなります．

endlinechar ブランチ ( commit 1793f26ed7f0c98f08f069c6320960e344eae48a) で，修正案とテスト endlinechar.tex を入れてみました．

**Comment by aminophen** [comment]
拾っていただきありがとうございます．あとで試してみます．

ツイッターの件で補足しておきますと，本件を初めて知ったのが

ftp://akagi.ms.u-tokyo.ac.jp/pub/TeX/source/ascii-jtex-1.7/

にある tex17p1.tar.gz でした（1993 年に pTeX の和文一文字命令のバグが報告されたときの MWE を含むアーカイブ）．テストケースを増やたほうがよければ，この辺も GitHub に置いておくと良いかもしれません．（ついでに同じ場所の jtex1.7.tar.gz が，アスキー日本語 TeX から pTeX になる過程のベータ版のソースコード．公開の場所に現存する pTeX ソースの中で最も古いかも．）

**Comment by aminophen** [comment]
win32 でビルドして試してみました．私の簡単なテストでは問題なく動いています．（upTeX のバッファの件はよくわかっていないので，合っているのかどうかはよくわからないですが．）

**Comment by aminophen** [comment]
> \endlinechar=-1

upTeX のバッファの件を主メンテナでいらっしゃる @t-tk さんのご意見を伺ったうえで，master にマージするという方向で良いと思います．

**Comment by t-tk** [comment]
北川さん、aminophenさん、ありがとうございます。
確認しました。良いと思います。

pTeX の後禁則ペナルティ の方と texk/web2c/ptexdir/ChangeLog のコンフリクトがあったため、
ChangeLogの日付を本日にしてマージしました。
今の main ブランチのように、後ほどTeX Live svnにコミットしようと思います。

**Comment by t-tk** [comment]
TeX Live svn にコミット([r43720](http://www.tug.org/svn/texlive?view=revision&sortby=file&revision=43720))しました。
