### ISSUE TITLE
`! Emergency stop.` 時のファイル名の表示

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/tex-jp-build#100]
#45 とどれほど関係があるかわかりませんが，Slack にもほぼ同じことを書いたのでここに書いておきます．

hoge.tex を
```
\message{ゆ き だ る ま}\endinput
```
という一行だけのファイルとし，これを ptex で処理すると
```
$ ptex hoge
This is pTeX, Version 3.14159265-p3.8.3 (utf8.euc) (TeX Live 2020) (preloaded format=ptex)
 restricted \write18 enabled.
(./hoge.tex ゆ き だ る ま)
*
```
と入力待ち状態になります．その後 Ctrl-D を押すと `! Emergency stop.` になるわけですが，その際に出力されるメッセージが
```
<*> ^^@oge
```
と，先頭バイトだけ NUL に変わってしまいます．

tex, pdftex ですと
```
<*> hoge
```
ときちんとファイル名全体が表示されます

**Comment by h-kitagawa** [comment]
ptexenc.c の `input_line2` 関数で，`buffer[last] = '\0';`……① と NUL を書き込んでいることが直接の原因のようです．

pTeX が `input_line` 関数（lib/openclose.c) でファイル終端以外の「一行」を読むときには，`input_line2` で一行読んた後に `buffer[last] = ' ';` と上書きされます．そのため①がどこまで必要なのかわかりませんが，とりあえず①を
```
if (i != EOF || first != last) buffer[last] = '\0';
```
とすると症状は収まるようです．

**Comment by t-tk** [comment]
有難うございます。
動作を確認しました。
TeX Live svnにコミットしました。([r55082](https://www.tug.org/svn/texlive?view=revision&revision=55082))
