### ISSUE TITLE
Bug report address

### ISSUE THREAD

**Issue by t-tk** [texjporg/tex-jp-build#101]
コマンドラインヘルプに表示される "Email bug reports to issue@texjp.org." のような表記についての話題です。
現状、よく使われる主要なツールは大体
```
$ ptex --help
Usage: ptex [OPTION]... [TEXNAME[.tex]] [COMMANDS]
   or: ptex [OPTION]... \FIRST-LINE
   or: ptex [OPTION]... &FMT ARGS
(...)

Email bug reports to issue@texjp.org.
```

のように issue@texjp.org が出るようになっているのですが、一部まだ出ないものがあります。
upmendex は私がメンテナンスしていますが先日 Karl さんから BUG_ADDRESS として tex-k@tug.org を使ってもいいよとsuggestionがありました。 upmendex は、`Email bug reports to issue@texjp.org, tex-k@tug.org.` と出るようにさせて頂こうかと考えています。
他に、tex-jp-build にソースがあるもので BUG_ADDRESS が出ないツール類がまだ残っています。tex-jp-buildがupstreamになっているものと、ここ以外であまりメンテナンスされていないものが含まれます。

細かい議論やすり合わせは要らない話だとは思いますが、ここで記録を残しつつぼちぼち作業していこうかと思います。何かあればご意見ください。

**Comment by t-tk** [comment]
気がついたもののリストです。

tex-jp-build が upstreamとなっているもの

[ ] mendex
[ ] dviout-util (dvispc, chkdvifont)

それ以外

[ ] seetex (dvibook, dviconcat, dviselect, dvitodvi)
[ ] dvidvi
[ ] dvi2tty

**Comment by aminophen** [comment]
bug_address は configure.ac で制御すべきな気がします。ビルド時の testsuite には configure.ac に書かれたアドレスが使われますので。

**Comment by t-tk** [comment]
例えば `mendex` の場合 https://github.com/texjporg/tex-jp-build/commit/c7741eba3f104e4ea5eeda8958fca78c83c02f15 のように  `configure.ac` の
```
AC_INIT([mendex (TeX Live)], [3.2])}
```
を
```
AC_INIT([mendex (TeX Live)], [3.2], [issue@texjp.org])}
```
として `aclocal`, `autoconf` とすると
PACKAGE_BUGREPORT
に `issue@texjp.org` が入るみたいです。

PACKAGE_BUGREPORT と BUG_ADDRESS は別の概念のような気もして迷いました。
packageの部分についてのレポート先とソフトの中身のレポート先とばらばらの場合もありそうで。

**Comment by aminophen** [comment]
> PACKAGE_BUGREPORT と BUG_ADDRESS は別の概念のような気もして迷いました。
> packagingの部分についてのレポート先とソフトの中身のレポート先とばらばらの場合もありそうで。

なるほど，確かにバラバラの場合もありそうですね。

**Comment by t-tk** [comment]
このあたり(etex, ptex, uptex, eptex, euptex)は configure.ac を介さず BUG_ADDRESS を直接#defineしているみたいです。

```
$ ag ADDRESS web2c/*/*.h
web2c/eptexdir/eptexextra.h
14:#define BUG_ADDRESS "issue@texjp.org"

web2c/etexdir/etexextra.h
27:#define BUG_ADDRESS "tex-k@tug.org"

web2c/euptexdir/euptexextra.h
15:#define BUG_ADDRESS "issue@texjp.org"

web2c/ptexdir/ptexextra.h
12:#define BUG_ADDRESS "issue@texjp.org"

web2c/uptexdir/uptexextra.h
13:#define BUG_ADDRESS "issue@texjp.org"
```

**Comment by aminophen** [comment]
web2c/ 以下のプログラムは共通の config.h しかなく，プログラム毎に違うアドレスを指定できるように直接 define しているのだと思います。

packagingの部分についてのレポート先とソフトの中身のレポート先とばらばらの場合もあり得ることを考えると，configure.ac はパッケージングのレポート先として別に考えてもいいような気がしてきました。

**Comment by t-tk** [comment]
SeeTeX についても tex-k@tug.org を表示するようにしてみました。https://github.com/texjporg/tex-jp-build/commit/bc00a67ebd44c034d9735b44ff5cb8c75d04a8fb
この方法で `VERSION`, `TL_VERSION` は `configure.ac` から取り出しています`BUG_ADDRESS` は新設の `common.h` で直接 define しています。

SeeTeX の過去の VERSION は何が適当なのかよく分からなかったので日付にしました。

**Comment by t-tk** [comment]
dvi2tty は原作者の方のメールアドレスと、気に入ったら寄付してというメッセージがあります。
原作者のサイト http://www.mesa.nl/~marcel/ は現状もアクセス可能なのと、TL の upstream を移した後もバグレポートを受けたことがないことを考えてそのままにすることにしました。

それと、pmpost と upmpost が tex-jp-build にソースがあって現状 `BUG_ADDRSS` が無いものに該当していますが事情がよくわからないのでそのままにします。

**Comment by t-tk** [comment]
私も autotools の詳細は理解できないまま他所の実装をまねして動かしてみている程度の知識なので、よりよい実装のご提案があれば歓迎です。

今回考えたリストは一応網羅されたのでここは閉じます。
