### ISSUE TITLE
pTeX の後禁則ペナルティ

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#11]
[pTeX の後禁則ペナルティがサッパリわからない話](http://d.hatena.ne.jp/zrbabbler/20170405/1491391939)というのが出ているので貼ります。

また，

~~~~ tex
\parbox{5zw}{アレアレ＃\nolinebreak アレアレ}
~~~~

とかが期待通りにならない（`\postbreakpenalty＃=200`）とのことです。

**Comment by h-kitagawa** [comment]
> ```tex
> \postbreakpenalty＃=200 アレアレ＃\nolinebreak アレアレ
> ```

そもそも TeX の `\penalty` 自体が
```tex
a\penalty100\penalty2900
```
と二回連続発行しても合算されませんが，（`\prebreakpenalty` がやっているように）「禁則ペナルティだけ合算」という仕様にするのが自然，ということでしょうか？

> ```tex
> \postbreakpenalty`ア=1234
> \setbox0\hbox{ア\unpenalty レ}\showbox0
> ```
`\showlists` で調べてみると，`\unpenalty` の直後では消えているものの，`レ`を水平リストに追加するところで復活しているようです．`\unpenalty` の次の文字を欧文文字にすると復活しないっぽいです．

**Comment by h-kitagawa** [comment]
> `\unpenalty` の直後では消えているものの，`レ`を水平リストに追加するところで復活しているようです．

更に調べた所，`@<Append KANJI-character |cur_chr| ...@>` のセクションにある
```pascal
if is_char_node(tail) then
  begin cx:=qo(character(tail)); @<Insert |post_break_penalty|@>;
  end
else if type(tail)=ligature_node then
  ...
```
の部分で追加されていることがわかりました．おそらくこの処理は，`\postbreakpenalty` が設定されている欧文文字に対してペナルティを追加するための処理と思われる（和文文字に対してはそれがリストに追加されると同時にペナルティのノードが追加されるはず））ので，`cx` に 256 以上という制限をかけたらどうでしょうか？

**Comment by h-kitagawa** [comment]
後禁則ペナルティが合算されないことは保留にしていますが，復活してしまうことについては 865aead4b で対処したつもりです．

**Comment by aminophen** [comment]
> 復活してしまうことについては  865aead  で対処したつもりです．

遅くなりましたが修正されたのを確認しました。

> 後禁則ペナルティが合算されない

~~~~ tex
\documentclass{jarticle}
\prebreakpenalty`か=1000
\postbreakpenalty`そ=1000
\begin{document}
\parbox{5zw}{あいうえお\nobreak かき}% 「お」と「か」の間は分割しない
\parbox{5zw}{さしすせそ\nobreak たち}% 「そ」と「た」の間で分割
\end{document}
~~~~

を処理してみると，\pre～ と \post～ で違うのは不思議に感じます。「TeX のペナルティは合算しない」はそのとおりなのですが，この例をみると禁則ペナルティは合算する方が私は直感に合いました。

**Comment by h-kitagawa** [comment]
> 禁則ペナルティは合算する

6e3ca0327 で和文処理ペナルティ（禁則，`\jcharwidowpenalty`）の直後に
`\penalty` プリミティブでペナルティが来た場合に合算するようにしてみました．
`testpena2.tex` にあるように，
```tex
 「\penalty1000\penalty100
```
と 2 つ続いた場合は，直後のもの (`\penalty1000`) のみを合算します．

----
ついでに気がついた事柄ですが，
```tex
\postbreakpenalty`a=-1000 a\nobreak あ
```
とした場合に，禁則ペナルティが入らず，`\nobreak` による `\penalty10000` のみが入るようです． `a` のところを和文の `「` としても同じです．
ただ，この場合も合算するようにすると，`\break`，つまり `\penalty-10000` による強制分割に
影響が出ると思うので，どうしたものでしょう．

**Comment by aminophen** [comment]
従来から「合算」だった \prebreakpenalty については再考しています。

たとえば

~~~~ tex
\documentclass{jarticle}
\prebreakpenalty`は=-1000
\begin{document}
\parbox{5zw}{なにぬねの\nobreak はひ}
\end{document}
~~~~

は「Underfull \hbox (badness 10000)」と「\penalty10000 + 禁則 -1000 = 9000」を比較した結果，分割が起こります。これが果たして意図するものなのかは自明ではない気がします。

> ついでに気がついた事柄ですが，
> [...]
> とした場合に，禁則ペナルティが入らず， \nobreak  による  \penalty10000  のみが入るようです．

を見て思ったのですが，「\penalty プリミティブが明示された場合，和文処理ペナルティ（前禁則・後禁則・\jcharwidowpenalty）を無視する」だとどうでしょう（可能でしょうか）？

**Comment by h-kitagawa** [comment]
合算する場合でも絶対値が 10000（以上）の値の特別扱いはあってもいいかもしれません．
参考までに LuaTeX-ja では基本的には合算ですが，次のコードを使っています．
```lua
local function add_penalty(p,e)
   local pp = getfield(p, 'penalty')
   if pp>=10000 then
      if e<=-10000 then setfield(p, 'penalty', 0) end
   elseif pp<=-10000 then
      if e>=10000 then  setfield(p, 'penalty', 0) end
   else
      pp = pp + e
      if pp>=10000 then      setfield(p, 'penalty', 10000)
      elseif pp<=-10000 then setfield(p, 'penalty', -10000)
      else                   setfield(p, 'penalty', pp) end
   end
end
```

**Comment by aminophen** [comment]
> 合算する場合でも絶対値が 10000（以上）の値の特別扱いはあってもいいかもしれません．

確かに。和文ペナルティと \penalty プリミティブが（順不同で）連続する場合，両方の値が -9999〜9999 に収まる場合だけ合算すれば良いのかもしれません。

**Comment by zr-tex8r** [comment]
今思っていることとしては：

  * 単に「前禁則と合わせたほうが仕様が綺麗」くらいの理由で仕様を変更すべきではない。
  * 後禁則も前禁則も、無限大（絶対値10000以上）のペナルティの扱いは、改善することを考慮する余地がありそう。

**Comment by zr-tex8r** [comment]
* そもそも何故「前禁則だけ合算」という仕様になったか？
      * 多分、「禁則ペナルティ同士（後禁則と前禁則）を合算させる」のが目的だったのではないか。
      * このためには、「前禁則だけ合算」で十分。
      * 合算しないと `（ってことは` とか `金よこせ￥」` とかが破綻するし、これはマクロで対処できない。
  * 合算になるのは“例外”であり、例外はあまり増やさないほうがよい気がする。
  * 「`\unpenalty` できない」問題が解決した前提では、後禁則において「合算にする」必要があるのなら、TeXのコードを書けば実現できる。

**Comment by h-kitagawa** [comment]
> * そもそも何故「前禁則だけ合算」という仕様になったか？ 
>   * 多分、「禁則ペナルティ同士（後禁則と前禁則）を合算させる」のが目的だったのではないか。

```tex
\penalty100）
```
のような `\penalty` と前禁則ペナルティで合算が起こるのが気になります．
`\penalty`，禁則によるペナルティ，`\jcharwidowpenalty` は subtype で区別可能ですから，
```
最後のノードが禁則ペナルティや \jcharwidowpenalty のときだけ，前禁則ペナルティと合算
```
という仕様も可能なはずです．

**Comment by aminophen** [comment]
そういえば，「直前のペナルティと前禁則ペナルティを合算する」という挙動は，platex が開発された頃には認知されていたのかもしれないです（強制改行命令 `\\` の内部マクロ `\@gnewline` を再定義している部分の pldoc.pdf の説明に，合算という言葉が出ているようです）。合算の対象が禁則ペナルティのみであれば，この再定義も不要だったはずなのに。

**Comment by aminophen** [comment]
ついでに

~~~~ tex
\documentclass{jarticle}
\begin{document}
テスト（\linebreak ）テスト。\par
テスト（\\ ）テスト。
\end{document}
~~~~

TL2016 の pTeX だと \linebreak は改行が起きませんね。

**Comment by zr-tex8r** [comment]
そもそも「どういう仕様が自然と感じられるか」が人によって違う気がします。

例えば、次の例で〈」〉の前で改行は許可されるか否か。

```tex
アレ\nolinebreak[2]」アレアレ
```

**Comment by aminophen** [comment]
@zr-tex8r さん

> 「どういう仕様が自然と感じられるか」が人によって違う

のはそのとおりだと思うのですが，“実際にそのコードを書く人が存在し得たか”と考察してみると，ご提示の例は人工的すぎる感じがします。少し一般化すると

『前禁則ペナルティ 10000 と合算される箇所で \(no)linebreak[0-3] を発行する事例』

といえますが，実際に走らせてみれば「オプションは実質無意味だ」とすぐに気づきそうですよね。

一方で， @h-kitagawa さんの

> 最後のノードが禁則ペナルティや \jcharwidowpenalty のときだけ，前禁則ペナルティと合算

も少し心配な点があります。 texjporg/platex#16 の改修を施した際，「\footnote 直前に後禁則ペナルティがあった場合を考慮して，`\pltx@foot@penalty` に一旦その値を退避し，最後に復帰する」という処理があります。この復帰処理は \penalty プリミティブを使うため，それが後禁則ペナルティ由来だったという情報は失われていそうです。

**Comment by aminophen** [comment]
人工的，と言い始めると私自身が挙げた例などほとんど当てはまっていますが(^^;; まあ

~~~~ tex
\documentclass{jarticle}
\begin{document}
あいうえお\linebreak ！かきく\par
あいうえお\\！かきく
\end{document}
~~~~

`\linebreak` と `\\` は両方とも「LaTeX らしい命令」であるにもかかわらず，pLaTeX では前者において改行が起きない，というのはさすがに変だと思っています。

**Comment by aminophen** [comment]
禁則ペナルティの話を再訪しています。読み返して思ったことを書いておきます。

- 「前禁則ペナルティは直前の値と合算するが，後禁則ペナルティは直後の値と合算しない」は維持すべき。
    - これは「禁則ペナルティ同士（後禁則と前禁則）を合算させる」のが目的と推察できるし，前禁則ペナルティの合算は（後禁則と違って）マクロでは実現不可能だから。
    - 合算において「直前の値」が禁則ペナルティかどうかで分岐するような改変も入れないべき（\footnote マクロのような退避-復帰の挙動に影響するから）。
- ただし，「前禁則ペナルティは合算」するとき，無限大のペナルティは例外扱いした方がよさそう。LuaTeX-ja の処理を参考にしたい。

**Comment by aminophen** [comment]
本 issue は2点混在していますが

- 後禁則ペナルティが復活してしまう問題：2017-04-06 で対処済み。
- `\parbox{5zw}{アレアレ＃\nolinebreak アレアレ}` で行分割が起きてしまう話：関連の #27 へ統一

ということにして，こちらは閉じます。
