### ISSUE TITLE
[dvipdfmx] 特定STIX利用dviでクラッシュ(pdf_encoding_new_encoding)

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#114]
転載しておきます。

* https://twitter.com/kmuto/status/1387665411764719622
* https://gist.github.com/kmuto/5263e8ff390e1032803372bdf264f7e9

> TeXLIve2019〜2020、trunkのdvipdmfxで落ちるのは確実にわかってるのだが、業務データで完全に作り上げないとエラーにならないという非常にテストも協力も求めづらい状況だ…

> STIX混ぜたときにsegvはわかってたので、フォントとpdfencodingのあたりかなというのは推測どおりか。あとはなんでこうなるか…
> baseenc[code]が別のメモリ指してるな、なんだこれ

> `create_encoding_resource` の `baseenc ? baseenc->glyphs : NULL` でbaseencはあるのだが`baseenc->glyphs`がやっぱり壊れているな。encoding->glyphsは全部読めてる
> baseenc->glyphsも全部見えないわけじゃなくてちらほら見えてるのがある…謎い

Slack より：

> pdfencoding.c の pdf_encoding_new_encoding に問題があります。
> RENEW による再確保が実行されると encoding->baseenc が dangling pointer になります。
> （16 毎に再確保するので異なるエンコーディングのフォントを 17 以上使うと再現しそう）

@kmuto @h20y6m とりあえず埋もれないようにファイルしておきます。もし後で平田さんにお伝えする時に，参照先として1箇所の方がよいかと思い。

**Comment by aminophen** [comment]
@kmuto ソース(.tex)の開示は難しいのだと思いますが，DVIに含まれるフォントの一覧は開示可能ですか？ 例えば，TeX Live には [dviinfox](https://github.com/aminophen/tex-assort) や [chkdvifont](https://github.com/aminophen/dviout-util) というツールが入っていて，それを使えば「DVIにから参照されるTFMファイルの一覧」を表示することができます。それがわかれば，フォントパッケージを探って再現例を作れる人が現れるかもしれません。

**Comment by kmuto** [comment]
ありがとうございます、
dviinfox -fはDVI error: Expected POST_POST command, not 0xf4!となってしまいました。

chkdvifontの結果を問題のあるもの bad.log(lmr利用)、問題のないもの ok.log(代替でほかでも使っているhiramin利用)として書き出しました。
[chkdvifont-log.zip](https://github.com/texjporg/tex-jp-build/files/6481650/chkdvifont-log.zip)

tfm/vfは @munepi さんに作成いただいた業務用のもので、やはり出しにくいところがあります。

**Comment by h20y6m** [comment]
> 異なるエンコーディングのフォントを 17 以上使うと再現しそう

以下のソースで再現できました。

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{stix2}
\begin{document}
A quick brown fox jumps over the lazy dog.
\[ \left( \int_0^\infty \frac{\sin x}{\sqrt{x}} dx \right)^2
= \sum_{k=0}^\infty \frac{(2k)!}{2^{2k}(k!)^2} \frac{1}{2k+1}
= \prod_{k=1}^\infty \frac{4k^2}{4k^2 - 1} = \frac{\pi}{2} \]
\[ \mathrm{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathbf{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathit{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathbfit{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathcal{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathscr{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathbfscr{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathsf{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathbfsf{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathsfit{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathbfsfit{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathbb{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathfrak{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathbffrak{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\[ \mathtt{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \]
\end{document}
```

**Comment by trueroad** [comment]
パッチ作ってみました。
https://github.com/texjporg/tex-jp-build/issues/114#issuecomment-841578079
が正常に通るようになりました。

```patch
--- a/source/texk/dvipdfm-x/pdfencoding.c
+++ b/source/texk/dvipdfm-x/pdfencoding.c
@@ -74,7 +74,7 @@ typedef struct pdf_encoding
   char     *glyphs[256];     /* ".notdef" must be represented as NULL */
   char      is_used[256];
 
-  struct pdf_encoding *baseenc;
+  int baseenc_id;
   pdf_obj  *tounicode;
 
   pdf_obj  *resource;
@@ -100,7 +100,7 @@ pdf_init_encoding_struct (pdf_encoding *encoding)
 
   encoding->tounicode = NULL;
 
-  encoding->baseenc   = NULL;
+  encoding->baseenc_id= -1;
   encoding->resource  = NULL;
 
   encoding->flags     = 0;
@@ -437,7 +437,7 @@ pdf_encoding_new_encoding (const char *enc_name, const char *ident,
     if (baseenc_id < 0 || !pdf_encoding_is_predefined(baseenc_id))
       ERROR("Illegal base encoding %s for encoding %s\n",
 	    baseenc_name, encoding->enc_name);
-    encoding->baseenc = &enc_cache.encodings[baseenc_id];
+    encoding->baseenc_id = baseenc_id;
   }
 
   if (flags & FLAG_IS_PREDEFINED)
@@ -464,9 +464,11 @@ void pdf_encoding_complete (void)
        */
       int with_base = !(encoding->flags & FLAG_USED_BY_TYPE3)
 	              || pdf_check_version(1, 4) >= 0;
+      pdf_encoding *baseenc = (encoding->baseenc_id < 0) ?
+	NULL : &enc_cache.encodings[encoding->baseenc_id];
       ASSERT(!encoding->resource);
       encoding->resource = create_encoding_resource(encoding,
-						    with_base ? encoding->baseenc : NULL);
+						    with_base ? baseenc : NULL);
       ASSERT(!encoding->tounicode);
       encoding->tounicode = pdf_create_ToUnicode_CMap(encoding->enc_name,
 						      encoding->glyphs,
```

**Comment by trueroad** [comment]
@h20y6m さんの再現ソースとパッチを投げておきました
https://tug.org/pipermail/dvipdfmx/2021-May/000270.html

**Comment by aminophen** [comment]
本題（dvipdfmx）とは関係ないですが

> dviinfox -fはDVI error: Expected POST_POST command, not 0xf4!となってしまいました。

の修正版をリリースしました。 https://github.com/aminophen/tex-assort/issues/1

**Comment by aminophen** [comment]
https://tug.org/pipermail/dvipdfmx/2021-June/000285.html

> It's true that with the suggested patch segmentation fault can be avoided, but it is not appropriate one.

**Comment by aminophen** [comment]
[r59525](https://www.tug.org/svn/texlive?view=revision&revision=59525) にて正式な修正が入ったようです。
