### ISSUE TITLE
[(up)mendex] -s styfile  オプションで複数のファイル読み込み, 新オプション kana_head

### ISSUE THREAD

**Issue by t-tk** [texjporg/tex-jp-build#116]
upmendex のスタイルファイルの説明 https://github.com/t-tk/upmendex-package/issues/3 で@aminophen さんからご提案のあった style file の複数読み込みを実装しようと思います。

**Comment by t-tk** [comment]
複数 style file の読み込みの機能自体は https://github.com/texjporg/tex-jp-build/commit/c092fe7e4d49c9419af639704c626edbfaac61ca で動いているようです。
初期化や読み込みなどの順番を少々入れ替えたので少し不安があり、もう少しテストするつもりです。

標準として配布する .ist としてはどんなものが適当か議論していただけるとありがたいです。

**Comment by aminophen** [comment]
> 複数 style file の読み込み

私の突然の思い付きにもかかわらず，ご検討いただきありがとうございます。テストしてみます。

> 標準として配布する .ist

複数 style file の読み込み機能があれば，想定としては「makeindex 用に配布されている style file にちょい足しできる，とにかくミニマムな日本語書籍用設定」があればよいと思います。upmendex のサンプルがたくさんあるようですので，そこから (up)mendex 特有の設定値のみを抽出するイメージです。

**Comment by aminophen** [comment]
> 複数 style file の読み込み

初期化順序を変えた影響を調べてみました。普通の挙動については問題なさそうです。

一方，styfile.c を見ると

``` c
if (getparam(buff,"atama",atama)) continue;
```

という行があり，この "atama" というどこにもドキュメントされていない謎のキーを認識するようです。この "atama" というキーは元々 style file でどう与えても無視される挙動でしたが，初期化順の変更（具体的には `initkanatable()` より後に `styread` する）により「style file で "atama" に無意味な文字列を与えると，区切り文字（アイウエオまたはアカサタナ）が壊れる」という挙動に変化します。したがって，styfile.c の上記1行は削除しましょうか。

**Comment by aminophen** [comment]
> "atama" というどこにもドキュメントされていない謎のキー

追記です。mendex については「単に styfile.c の例の1行を削除」で良いと思います。upmendex には "atama" とよく似た動作をする "tumunja" があり，この "tumunja" の方はドキュメント通りに動作していたようですので，単に "atama" を消すのかそれとも "atama" も "tumunja" 並みの動作とするのか検討の余地があると思います。

**Comment by t-tk** [comment]
1. 単に "atama" を消すのか
2. それとも "atama" も "tumunja" 並みの動作と定めてドキュメント化するのか

実は、upmendex にハングルを導入するときに少々悩んだ上、`atama` の実装をまねして `tumunja` を実装しました。
そして将来 `atama` も `tumunja` なみの公式な動作にしようかと構想だけは持っていました。
今回、初期化の順番を入れ替えたのもその狙いに沿ってやりました。
https://github.com/texjporg/tex-jp-build/commit/c092fe7e4d49c9419af639704c626edbfaac61ca では、style fileで`atama` を指定してもデフォルトで `letter_head` が 1 になっていて style file の `atama` を有効にするためには `letter_head` を 0,1,2 以外に指定する必要があります。そんな仕様では少々分かりにくいので style file で `atama` を読み込んだ場合はそちらを優先するような実装に変えようか、とも思います。

mendex でも同様の仕様に出来るかもしれませんし、そもそも style file で `atama` の変数が読めるようになっている事自体 `atama` のカスタマイズという構想がASCII社さんの開発当初からあったのかもしれません。しかし、実際には現状の実装では動かないしドキュメントにも記載が無いので、mendex の方は単純に「style  file で `atama` を読む動作を消す」のでいいかもしれません。実装しようとすると文字コード混在が問題になりそうなのも懸念です。

私の現在の考えは、upmendex は 2 でさらに使いやすくする、mendex は 1 です。
どうでしょう。

**Comment by aminophen** [comment]
> upmendex は 2 でさらに使いやすくする、mendex は 1 

賛成いたします。mendex で「現状の実装では動かない」「実装しようとすると文字コード混在が問題になりそうなのも懸念」は全くその通りですね。upmendex の構想もソースコードから何となく想像がついていましたので，「style file で `atama` を読み込んだ場合はそちらを優先するような実装」に変えることも違和感ありません。

**Comment by t-tk** [comment]
https://github.com/texjporg/tex-jp-build/commit/5bf039b36d4e862750a7d8c5a400937240946073 で mendex, upmendexともに `atama` を style file から読み込むのはやめました。
upmendex は style file のパラメータとして新規に `kana_head` を作りました。
style file内に`kana_head` が存在しない場合(デフォルト)では従来と同じ動作、`kana_head` が存在する場合は `kana_head`を内部変数`atama` に代入して動作させます。 
`kana_head` は `tumunja` と同様の動作を仮名見出しに対して行います。
`kana_head` に使える文字は通常の平仮名、片仮名に加えて丸囲み片仮名(U+32D0..32FE, ㋐ .. ㋾) が使えます。

例えば style file 内に以下のように指定します。
```
kana_head  "㋐㋑㋒㋓㋔㋕㋖㋗㋘㋙㋚㋛㋜㋝㋞㋟㋠㋡㋢㋣㋤㋥㋦㋧㋨㋩㋪㋫㋬㋭㋮㋯㋰㋱㋲㋳㋴㋵㋶㋷㋸㋹㋺㋻㋼㋽㋾"
```
とか
```
kana_head  "㋐㋕㋚㋟㋤㋩㋮㋳㋶㋻"
```
などです。この指定で飛ばした分は、出力の見出しも飛ばしたものになります。

**Comment by t-tk** [comment]
`kana_head` のテストを https://github.com/t-tk/upmendex-package/commit/0d025f0729a57e80300d22784209b104bfd0d521 に入れました。

**Comment by aminophen** [comment]
ありがとうございます。実装確認と簡単なテストをしてみて，mendex も upmendex も期待通りに動いているようです。

**Comment by aminophen** [comment]
> 標準として配布する .ist

この件は別なので https://github.com/texjporg/mendex-doc/issues/11 に移ることにします。

**Comment by t-tk** [comment]
テスト有難うございます。
こちらの実装の方は収束していると思うので後ほど TeX Live svn にコミットしておきます。

**Comment by aminophen** [comment]
よろしくお願いします。TeX Live svn へのコミット時に mendex-doc の mendex.1, mendex.1.ja も https://github.com/texjporg/mendex-doc/commit/7a060c257255140b7135d625861d253740a6c85f で更新していただけると助かります。

**Comment by t-tk** [comment]
TeX Live svn にコミットしました。 r59487, r59488

**Comment by t-tk** [comment]
話題が2つ残っていますが、ここでの目的は達成したのでここは閉じます。
https://github.com/texjporg/mendex-doc/issues/10
