### ISSUE TITLE
[mendex] 記号類が最初でないとき，symhead_positive や symhead_negative が現れない

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#117]
https://github.com/texjporg/mendex-doc/issues/10 で気づきました。

`character_order` をデフォルト値 ("SNEJ") 以外（例えば "JESN" など）に変更した場合，パラメータ `symhead_positive` や `symhead_negative` の値にかかわらず見出しが「空」になります。パラメータ `symbol` を定義すれば解決する話なので実際に困った人は少ないと思いますが，mendex 2.5 でこれらを追加した時の考慮漏れのように思います。

```
character_order "JESN"
heading_flag 1
symhead_positive "記号"
```

実装を見てみると，デフォルトの「記号類が最初に来る場合」では

https://github.com/texjporg/tex-jp-build/blob/3a8384d1a5f0d07e0b6058e157c69e785f9c3ed7/source/texk/mendexk/fwrite.c#L147-L158

このように `symhead_positive` と `symhead_negative` が考慮されますが，順序を `character_order` パラメータで入れ替えた場合は

https://github.com/texjporg/tex-jp-build/blob/3a8384d1a5f0d07e0b6058e157c69e785f9c3ed7/source/texk/mendexk/fwrite.c#L217-L224

のように `symhead_positive` と `symhead_negative` が参照されません。

**Comment by aminophen** [comment]
upmendex では `symhead_positive` と `symhead_negative` が無視される問題は解消していますが，一方

```
character_order "SLJN"
```

のように S と N を離すとやはり「記号類」の見出し文字列として全く同じものが2回出力される，という点は mendex と同じでした。

**Comment by aminophen** [comment]
> 記号類が最初でないとき `symhead_positive` や `symhead_negative` が現れない

'mendex-fix' ブランチ f608b5d で，upmendex と同じ挙動になりました。

> S と N を離すとやはり「記号類」の見出し文字列として全く同じものが2回出力される

この現象には対処していません。mendex と upmendex で同じ状態です。

**Comment by t-tk** [comment]
ありがとうございます。

>  S と N を離すとやはり「記号類」の見出し文字列として全く同じものが2回出力される

upmendex でもこの件は https://github.com/texjporg/mendex-doc/issues/10 で mendex のマニュアルに「S と N は必ず隣り合わせてくださいと明記する。」と同様、現状追認でupmendexのマニュアルに追記する方針にしたいと思います。
mendex の方は、バージョン番号管理(上げる? 上げない? 日付だけ替える?)、TeX Live svn へのコミットなどはおまかせします。

**Comment by aminophen** [comment]
ご確認と upmendex の追随ありがとうございます。今回はバグ修正なのでバージョン番号は上げずに，日付だけ区別するようにしようと思います。

**Comment by aminophen** [comment]
mendex については #117, #118, #119 を r59571 で一括コミットしました。

**Comment by t-tk** [comment]
upmendex も #118, #119 を [r59572 ](https://www.tug.org/svn/texlive?view=revision&revision=59572)でコミットしました。
