### ISSUE TITLE
[mendex] .ist や .log がない場合の終了コード

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#118]
mendex のドキュメントにサンプルを入れるつもりで Makefile を作っている途中に気づきました。

```
$ mendex -s nonexistent index-test      ← 索引スタイル .ist がない場合
```

```
$ mendex -p odd index-test              ← TeX  の .log ファイルを参照させる機能で .log がない場合
```

のようにすると，何も出力されずに終了します。

pageread.c

``` c
	if (fp==NULL) {
		fprintf(stderr,"No log file, %s.\n",logfile);
		exit(0);
	}
```

styfile.c

``` c
	if (fp==NULL) {
		fprintf(stderr,"%s does not exist.\n",filename);
		exit(0);
	}
```

このいずれも，exit code 0 ではなくエラー終了としたいです。

**Comment by t-tk** [comment]
ありがとうございます。賛成です。
upmendex もその辺りは触っておらずmendexとの差分は無いはずなので、mendex で実装されれば追従しようと思います。

**Comment by aminophen** [comment]
mendex の他のエラー終了は 255 だからという理由で，単純に 255 にしようと思います。

**Comment by aminophen** [comment]
いろいろな修正を 'mendex-fix' branch で作り始めます。まずは 2720a5c で exit code の修正案。

**Comment by t-tk** [comment]
ありがとうございます。
https://github.com/texjporg/tex-jp-build/commit/2720a5c3e46ce85f8343aa461b6682f24e0817ec を確認しました。
upmendex も追従します。

**Comment by aminophen** [comment]
r59571, r59572 で完了。
