### ISSUE TITLE
[mendex] 出力ファイルの書込失敗で mendex 自体が落ちる

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#119]
立て続けに見つけました。mendex の出力先が .ind ファイルである場合，その .ind ファイルがロックされている／読取専用設定などで書込失敗すると，少なくとも Win32 では「Making index file.」を表示した後で「...done.」に辿り着く前に，静かに mendex プログラムが落ちます。

なお mendex が出力しようとするログファイル .ilg が書込失敗の場合は，代わりに stderr に書き出す仕様のようです。こちらで落ちる可能性有無はまだ調べていません。

**Comment by aminophen** [comment]
次に 'mendex-fix' branch でファイルオープン失敗時の Segementation fault: 11 防止のため，出力ファイル .ind を書込オープンできなかった場合は stdout にフォールバックスルように。(5fa2509)

**Comment by t-tk** [comment]
ありがとうございます。
https://github.com/texjporg/tex-jp-build/commit/5fa25091bbbc30d12b3e0cda312e518f0ef25c1c, https://github.com/texjporg/tex-jp-build/commit/416dca84c377d9636aec99f288b26c2050846145 を確認しました。
upmendex も追従します。

**Comment by aminophen** [comment]
r59571, r59572 で完了。
