### ISSUE TITLE
pTeX ロゴ

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/tex-jp-build#12]
ptex-base.ch 等に `p\TeX` という表現を見つけたので， a1a57231693df00bb9d4c723d33cf3b2c7379046 で全面的に `\pTeX` に改めました．
p と T の間隔ですが，とりあえず今は `\kern-0.15em` にしています（ptexdir/ptex-base.ch と pmpostdir/pmpxout.ch にあります．参考： texjporg/jsclasses#13）．

Edit: リンクがきくように修正．

**Comment by aminophen** [comment]
ptexlogo は仕様変更とかではないので，それほど議論なくマージして問題ないと思います。synctex とかもパッチされていますが，妥当な変更だと思います。

**Comment by h-kitagawa** [comment]
マージしました．
