### ISSUE TITLE
[(e)(u)pTeX] INI モードで \char すると Segmentation fault: 11

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#123]
```
$ ptex -ini '\noindent\char65\end'
```

これで Segmentation fault: 11 が起こりました。

**Comment by aminophen** [comment]
```
$ ptex -ini '\noindent a\end'
```

も同様に Segmentation fault: 11 でしたが，スペースを入れた

```
$ ptex -ini '\noindent a \end'
```

だと大丈夫でした。

**Comment by h-kitagawa** [comment]
line_break の前処理 `<Get ready to start line breaking>` に

 * link(temp_head):=link(head) した後に
 * tail が disp_node だったときに tail を削除する

という処理がありますが，これでは link(head)==tail のときにおかしくなります．今回は引っかかっているようです．

https://github.com/texjporg/tex-jp-build/tree/kitagawa_tjb123 でうまく治っていると良いなあ．

**Comment by aminophen** [comment]
なるほど。「INI mode 故にフォントが文字を含まないため char_node が生成せず，しかし欧文文字を想定して disp_node だけ先に挿入されてしまったケース」がここに当たってしまうのですね。理解しました。

**Comment by aminophen** [comment]
> `kitagawa_tjb123`

Segmentation fault が治っていることを確認できました。TeX, pdfTeX, XeTeX では `No pages of output.` となるのに対して (e-)(u)pTeX では `Output written on texput.dvi (1 page, 128 bytes).` になるという違いはありますが，問題なく終了したので大丈夫そうです。一応

``` tex
\tracingoutput1
\showboxdepth10000
\showboxbreadth10000
```

を仕込んで何が出たのか確認すると

```
Completed box being shipped out [0]
\vbox(0.0+0.0)x0.0, yoko direction
.\glue(\topskip) 0.0
.\hbox(0.0+0.0)x0.0
..\glue(\rightskip) 0.0
.\hbox(0.0+0.0)x0.0
.\glue 0.0 plus 1.0fill
```

でした。

**Comment by aminophen** [comment]
> TeX, pdfTeX, XeTeX では No pages of output. となるのに対して (e-)(u)pTeX では Output written on texput.dvi (1 page, 128 bytes). になるという違い

5fe1e0a で `line_break` に渡る前の `end_graf` で弾くようにすると解消しました。

**Comment by h-kitagawa** [comment]
> https://github.com/texjporg/tex-jp-build/commit/5fe1e0a30ad78890ec5b7b7c16bd95bcb0a999ca で line_break に渡る前の end_graf で弾くようにすると解消しました。

ありがとうございます．`<Go into display math mode>` のところでも line_break 呼び出しがあったので，https://github.com/texjporg/tex-jp-build/commit/10dd7ec38582d9a655327273fdb837d6845e5550 で同様の処理を加えました．

**Comment by aminophen** [comment]
> `<Go into display math mode>` のところでも line_break 呼び出しがあった

確認漏れていましたし，ノード削除も入れておくのが安全でした。ありがとうございます。これで問題なさそうですので，夜にでも merge & commit します。ついでに

* master に入っている b443b80  (ptexenc/unicode-jp.c)
* #120 = 禁則テーブルの検索，\let した和文文字の kcatcode を再計算しない（昔の pTeX に戻す）

もコミットするつもりです。\ucs, \toucs (#121) は不正な値をもう少し調査してからにします。

**Comment by aminophen** [comment]
* 本 issue の修正 → r59697
* ptexenc/unicode-jp.c の修正 → r59698
* \let した和文文字の kcatcode を再計算しない（昔の pTeX に戻す） → r59699
* 禁則テーブルの検索の修正 → r59700
