### ISSUE TITLE
[(up)mendex] more compatible with makeindex / makeindexとの互換性向上

### ISSUE THREAD

**Issue by t-tk** [texjporg/tex-jp-build#124]
最近、@FrankMittelbach さんから質問、要望などをいろいろ頂いています。
例えば、https://github.com/t-tk/upmendex-package/issues/5
upmendex を makeindex の後継と期待されているものの非互換性の懸念をご指摘いただいています。
そこで、無理のない範囲で makeindex 互換を取り入れる方針にしようと思います。

並べ替え順序のドキュメント https://github.com/texjporg/mendex-doc/issues/10 で話題になったような hedings_flag と heading_flag の問題は、makeindex互換の headings_flag も受け付けるように変更しようと思います。
ここに記録を残しながら進めます。

**Comment by FrankMittelbach** [comment]
Am 28.08.21 um 06:08 schrieb TANAKA, Takuji:
> ***@***.*** <https://github.com/FrankMittelbach> さんから質 
> 問、要望などをいろいろ頂いています。
> 例えば、t-tk/upmendex-package#5 
> <https://github.com/t-tk/upmendex-package/issues/5>
> upmendex を makeindex の後継と期待されているものの非互換性の懸念をご指摘 
> いただいています。
> そこで、無理のない範囲で makeindex 互換を取り入れる方針にしようと思います。

thank you

> 並べ替え順序のドキュメント texjporg/mendex-doc#10 
> <https://github.com/texjporg/mendex-doc/issues/10> で話題になったような 
> hedings_flag と heading_flag の問題は、makeindex互換の headings_flag も 
> 受け付けるように変更しようと思います。
> ここに記録を残しながら進めます。

As this flag turns on all different headings it is reasonable to have it 
as a plural word the way makeindex does (and the way it is therefore 
used in various .ist files across TeXLive).

**Comment by t-tk** [comment]
I committed the changes shown above to TeX Live svn ([r60417](https://www.tug.org/svn/texlive?view=revision&revision=60417), [r60418](https://www.tug.org/svn/texlive?view=revision&revision=60418), [r60419](https://www.tug.org/svn/texlive?view=revision&revision=60419)).
I bumped version mendex v3.6 [6-Jun-2021], upmendex v0.59.

About character ordering, 
if we set symbol_flag=2, symbols and numbers are treated as different groups and can be placed separately.

Using option settings, new upmendex can output character ordering compatible with makeindex.
Examples are shown at
https://github.com/t-tk/upmendex-package/tree/master/doc/samples/option
char_order_m1, char_order_u1, char_order_cmp_mu in Makefile.
Examples of outputs are shown at
https://github.com/t-tk/upmendex-package/tree/master/doc/samples/option/output
chorder1_00-umdx.ind
chorder1_01-umdx.ind
chorder1_02-umdx.ind
chorder1_g_00-umdx.ind
chorder1_g_01-umdx.ind
chorder1_g_02-umdx.ind

**Comment by FrankMittelbach** [comment]
looks good, thank you. So when would that build show up in TeXLive?

**Comment by t-tk** [comment]
Hi @FrankMittelbach ,

The updated source has already been committed in TeX Live svn.
If you will wait official release of TeX Live, it will take more time.

https://www.tug.org/texlive/
```
Plan for TeX Live 2022:
15feb: candidate/final sources committed, test builds begin.
25feb: [tlpretest](https://www.tug.org/texlive/pretest.html) starts, CTAN updates continue there and in tlnet.
10mar: code freeze for final build, major bug fixes only.
22mar: final updates from CTAN, final doc tweaks.
23mar: deliver TL image for TeX Collection packaging/testing.
1apr: deliver [TeX Collection DVD](https://www.tug.org/texcollection/) image for manufacturing.
1apr: public release (also of MacTeX).
June?: delivery of DVDs to members.
```
