### ISSUE TITLE
数式モード内の \chardef と文字コード 256

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#129]
ptex-base.ch と uptex-m.ch を読んでいて，変だと思ったので MWE を作りました。

### 問題1

※ printkanji_16bit や unicode-14.0 とは関係ありません

``` tex
%#!uptex
\chardef\AX=256\relax
\chardef\AY=257\relax
$[\AX A^\AX]$, $[\AY A^\AY]$

\kchardef\KX=256\relax
\kchardef\KY=257\relax
$[\KX A^\KX]$, $[\KY A^\KY]$

\end
```

この結果は以下のようになり，1行めの左の上付き文字が変です。

<img width="477" alt="20220123-math-chardef-256-ng" src="https://user-images.githubusercontent.com/9957466/150681153-a1e9f614-9b57-432c-96e6-df80c40de3a1.png">

文字コード 256 に特有のようで #68 (upTeX の \if) と同様に

> \if は制御綴に便宜上「文字コード256」を与える

が原因ではと思います。例えば https://github.com/texjporg/tex-jp-build/commit/0b3df9dd7249e73733fa4a5b217e374f98ac03e1 はどうでしょうか。（edit: 256 のままでは駄目なのは明らかですが，では何の値にすれば意図通りなのかは自信がありません）

<img width="607" alt="20220123-math-chardef-256-ok" src="https://user-images.githubusercontent.com/9957466/150681499-4227433a-0497-4d5d-b563-59649d7a3ae4.png">

INI モード用 (uptex -ini) のテストファイル → [Gist](https://gist.github.com/aminophen/3e9b6bf3d5652a48dd63bcc26142bb0a)

**Comment by aminophen** [comment]
もう一つバグがありますね。

``` tex
% 昨日の INI モード用テストファイルの末尾にこれを追記
\mathcode"79="5AB
\mathcode"80="5CD
\message{\fontname\textfont5}% => nullfont
\chardef\AB="79
\chardef\CD="80

\hsize=300pt \vbox{$[^^79][^^80]\AB\CD$}
```

(e)(u)ptex では「\textfont5 が未定義というエラー」が2回しか出ず，128--255 の \mathcode 設定が正しく判定されません。[古い日本語 TeX のソース](https://github.com/texjporg/historical-ptex) をあさってみると，TeX2 の頃のコードを基にしたまま TeX3 に追随していなかったようです。

`set_math_char(ho(math_code(cur_chr)))` vs. `set_math_char(ho(math_code(cur_chr)))`

→ こちらは 4e8aff1da99c7286545242b73994e1207e387d6a でどうでしょうか。

**Comment by h-kitagawa** [comment]
問題 2 についてはこれで良いように思っています．

問題 1 の `cur_chr=256` は私もよくわかりませんが，このとき`math_code(cur_chr)` は範囲外ですからおかしいことは確かです．昔の pTeX から（p3.1.11 までも）残ったコードの誤記
```
if (cur_chr>=0)and(cur_chr<=256) then begin
```
が，ptexenc 用に書き換えられたときも直されなかったということなのでしょう．

**Comment by aminophen** [comment]
#131 マージに伴いクローズ，r61804
