### ISSUE TITLE
(u)pbibtex: freeze at en-dash etc. + sieicej.bst

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#133]
Twitter より

* https://twitter.com/triadsou/status/1349632219304718338
* https://twitter.com/jj1bdx/status/1460450675452645378

別々のツイートですが，この2つの合わせ技で「[電子情報通信学会論文誌 pLaTeX2e クラスファイル (ieicej.cls)](https://www.ieice.org/ftp/) に付属の sieicej.bst を使い，文献リストの pages に en-dash などの文字が入っている時に (u)pbibtex がメモリを食いつぶしてフリーズする」という現象を再現しました。後ほど再現ケースを投稿します。

**Comment by aminophen** [comment]
sieicej.bst を使わずに，最小化 BST ファイルで再現例を作成しました。

* https://github.com/texjporg/pbibtex-manual/commit/30c64637e0e85406106effc652ddf4f94961087b

こちらで `uptex 03jtest` → `upbibtex 03jtest` とすると再現できます。

* U+2013: pbibtex ではフリーズせず `^^` 形式にエスケープ），upbibtex はフリーズ
* U+2014, U+2015: pbibtex / upbibtex ともにフリーズ

要は pages に和文扱いされる文字が入っていると NG なようで，en-dash に限らず「あ」とかが入っていてもフリーズします。論文誌などで提供される BIB ファイルに U+2013 (en-dash) が入っているケースは割と起こり得るのだと思いますが，ユーザには原因がわかりにくいので (u)pbibtex 側で原因を調べたいと思います。

**Comment by aminophen** [comment]
原因がわかりました。

* BST で定義されている `n.dashify` および `multi.page.check` は `substring$` を使って「pages の文字列を先頭から読み，ページ番号の区切り文字を見つけたら，それより後ろの文字列を取り出す」という処理を行う。
* ここでは文字列 t がどんどん短くなることを想定しているが，(u)pbibtex の `substring$` 関数は「多めに取り出す」という仕様のため，文字列 t が一向に短くならない → 無限ループになる。

ちなみに plain.bst や [jecon.bst](https://github.com/ShiroTakeda/jecon-bst) を使っても同様にフリーズします。

**Comment by aminophen** [comment]
`substring$` の仕様とはいえ，個人的には「先頭または終端ではないバイトを敢えて開始位置としたにもかかわらず，実際には先頭や終端から切り出されてしまう」というのは困ると思います。取り出される文字列が必ず短くなるように，開始位置が `#2` 以上または `#-2` 以下の場合は特殊処理を入れる，という改良はできないでしょうか。

**Comment by aminophen** [comment]
さらにテストを追加してみると (03substring)，そもそも現行の pbibtex は仕様を満たさない気が。

```
  "漢" #1 #1 substring$ % => pbibtex: 空，upbibtex: 「漢」 … (1)
  "漢" #2 #1 substring$ ' % => pbibtex: 「漢」，upbibtex: 「漢」 … (2)
  "A" #1 #1 substring$ % => pbibtex: 「A」，upbibtex: 「A」
  "A" #2 #1 substring$ % => pbibtex: 空，upbibtex: 空
```

(1) の `"漢" #1 #1 substring$` は「多めに取り出す」が仕様なら pbibtex でも「漢」が返らないといけませんが，現状では空になっています。(2) は現在の「多めに取り出す」から期待される動作ですが，先のコメントのように「短く取り出す」に変更したいと思っているところです。

**Comment by aminophen** [comment]
pbibtex-substring ブランチを作ってみました。

> pbibtex の(1)のバグ修正

upbibtex が仕様通りに動いていることを元に https://github.com/texjporg/tex-jp-build/commit/3077da916f5cfa0b57b4246318ef28ed64ad483f で修正してみました。

**Comment by aminophen** [comment]
> pbibtex, upbibtex の(2)の改良

`substring$` で取り出される文字列が必ず短くなるように，開始位置が #2 以上または #-2 以下の場合は特殊処理を入れてみました。 → https://github.com/texjporg/tex-jp-build/commit/fe0b469fc98658dfbf1fd989a5f7a60faa638da3

テストケースを https://github.com/texjporg/pbibtex-manual/commit/efcb45933bb002fd018df17824ce87fd43fbe4bf に置いています。

**Comment by t-tk** [comment]
ありがとうございます。大変そうですね。力になれなくてすみません。
jBibTeX の作者の松井さんの意図がどうだったのか、ドキュメントをあさってみました。

texmf-dist/doc/ptex/pbibtex/jbibtex.pdf  よりコピペ
```
substring$ スタックトップの3 つのリテラル(順に長さlen，開始位置start の2 つの整数リテラル，文字列
リテラル) をポップする．start が正ならば文字列の先頭から数えて，(最初が1 文字目として)start 文字目
からの，start が負ならば文字列の終りから数えて(最後の文字が1 文字目として)，􀀀start 文字目からの，
連続する(高々)len 文字の部分文字列をプッシュする．

JBibTEX での注意：この関数は1 文字は1 バイトからなるものとして処理するので，漢字コード文字列で
は指定した文字数の半分の数の漢字コードが得られる．また漢字コードの1 文字の間で切られないように
開始位置，文字数(バイト数) の調整を行なう．調整は開始位置が漢字コードの1 バイト目に一致してい
れば．開始位置はそのまま，2 バイト目であれば1 バイト目から取り出すように調整する．終了位置が漢
字コードの1 バイト目であれば2 バイト目まで取り出すように調整する．したがって指定した長さより最
大2 バイト長い文字列となる．これは日本語用でないスタイルファイルを使った場合でもそれなりの出力
が得られるようにするためである．
```

私の理解では substring$ が最大2バイト伸びることは想定されていたようです。
今回の件は、これが正しく動いたとしてもまずい = 仕様がまずい、ということでしょうか?

**Comment by t-tk** [comment]
仕様として、

1. 開始位置を漢字コードの先頭に揃うように長めに切り出す。終了位置を漢字コードの末尾に揃うように長めに切り出す。
2. 開始位置を漢字コードの先頭に揃うように長めに切り出す。終了位置を漢字コードの末尾に揃うように短めに切り出す。
3. 開始位置を漢字コードの先頭に揃うように短めに切り出す。終了位置を漢字コードの末尾に揃うように長めに切り出す。
4. 開始位置を漢字コードの先頭に揃うように短めに切り出す。終了位置を漢字コードの末尾に揃うように短めに切り出す。

1は現状の仕様。
「文字列 t がどんどん短くなることを想定している」場合に上手く動くようにするには 2 に仕様変更すればよい?

**Comment by aminophen** [comment]
仕様1は現状のものですが，私の案は仕様2でも仕様3でもありません。先ほどの例を見ていただくのが早いと思います。

pbibtex では切り出しの起点が `#2` のとき（→文字列が和文文字で始まり，その2バイト目をカウント起点とするとき）と `#-2` のとき（→文字列が和文文字で終わり，その1バイト目をカウント終点とするとき）に特有の問題です。これらの場合に限り，長めに切り出すと「除去したいはずの文字が除去されない」という挙動になるのが良くないです。upbibtex でもバイト長が可変ですが同様のことが起こります。

**Comment by t-tk** [comment]
つまり、EUCの和文文字列の場合、和文文字列の長さが十分に長く、切り出しの起点が `#4`, `#6`, `#8`,... だったり、切り出しの終点が `#-8`, `#-6`, `#-4` の場合は従来通りの動作でよい、ということでしょうか?

**Comment by aminophen** [comment]
はい，そういう新仕様にしております。

**Comment by aminophen** [comment]
ちょっと来週時間が取れないので，早いですが [r62095](https://www.tug.org/svn/texlive?view=revision&revision=62095) でコミットしました。

**Comment by aminophen** [comment]
新仕様について pbibtex-manual に文書化しました。 https://github.com/texjporg/pbibtex-manual/commit/13d518e7be7345648eda6945816d12134b4eb79b

<img width="400" alt="20220220-pbibman-1" src="https://user-images.githubusercontent.com/9957466/154843811-e403d70a-e79c-4317-b600-53faa118386a.png">

<img width="400" alt="20220220-pbibman-2" src="https://user-images.githubusercontent.com/9957466/154843868-9f752d22-3378-46fc-b913-65d6f0c22e1e.png">

<img width="400" alt="20220220-pbibman-3" src="https://user-images.githubusercontent.com/9957466/154844067-4e681da4-d458-459e-a19e-5a1a4fd16acb.png">
