### ISSUE TITLE
((u)p)bibtex option -help, -version try to look for texmf.cnf

### ISSUE THREAD

**Issue by t-tk** [texjporg/tex-jp-build#145]
((u)p)bibtex の option -help, -version では texmf.cnf を見に行く必要がないのに見に行ってしまう問題です。

Ref.
https://github.com/texjporg/tex-jp-build/pull/144
https://ml.texjp.org/pipermail/issue/2022-August/000407.html

**Comment by h-kitagawa** [comment]
ありがとうございます，これで良いと思います．

**Comment by t-tk** [comment]
TeX Live svnにコミットしました。[r64276](https://tug.org/svn/texlive?view=revision&revision=64276), [r64277](https://tug.org/svn/texlive?view=revision&revision=64276)
