### ISSUE TITLE
[ptex] 未初期化の変数へのアクセスが発生する

### ISSUE THREAD

**Issue by h20y6m** [texjporg/tex-jp-build#151]
ptex-base.ch の `@<Seek list and make |t| pointing widow penalty position@>=` で未初期化の変数 `k` への読み取りアクセスが発生することがあります。

https://github.com/texjporg/tex-jp-build/blob/e3847757e19b80f1b12fcadbe1a738e312be2501/source/texk/web2c/ptexdir/ptex-base.ch#L7670

```
あABCDEFい。\par
```
のような入力で発生します。

`k` の値によっては（`k=-100` 等）「あ」と「A」の間に `\jcharwidowpenalty` が入ることがあるようです。

またC言語では未初期化の変数への読み取りアクセスは未定義動作（UB）なのでそもそもまともに動作する保証すらありません……

**Comment by h-kitagawa** [comment]
`\jcharwidowpenalty` の挿入位置をどう決めているんだっけ……と思い出すのに時間がかかりました．素直に `k:=0;` を加えるだけで良さそうに思えたので，そのようにしています．

**Comment by aminophen** [comment]
Done [r64786](https://www.tug.org/svn/texlive?view=revision&revision=64786)

ついでに https://github.com/h20y6m/tex-jp-build/commit/197a309f6b56234754d239410f4168c8958082c3#commitcomment-52683109 も思い出したので [r64787](https://www.tug.org/svn/texlive?view=revision&revision=64787)
