### ISSUE TITLE
[eptex] \lastnodechar でセグメンテーション違反

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/tex-jp-build#156]
[LuaTeX-ja のチケット #47755](https://ja.osdn.net/projects/luatex-ja/ticket/47755) で報告された件を最小化したものです．
以下のソースを e-upTeX で処理するとセグメンテーション違反がおこります：
``` tex
%#!euptex
\setbox0\hbox{，}\unhbox0 \the\lastnodechar
\bye
```

`\lastnodechar` の動作をたどったことによる推測ですが，`\unhbox` で「現在のリスト中の最後の和文文字ノード」 last_jchr の値が更新されない（今回は null = -268435455 のまま）ことが遠因ではないかと思われます．

**Comment by t-tk** [comment]
パッチを投稿していただいてから2週間ほど経ってしまいましたが
TeX Live svnにコミットしました。
https://tug.org/svn/texlive?view=revision&revision=66853
