### ISSUE TITLE
[makejvf] クオートが -m オプションで消える

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#17]
~~~~
$ makejvf -i -u jis -m `kpsewhich upjisr-v.tfm` piyo
~~~~

として upjisr-v.vf（uptex-fonts に入っている本物とは違う）と piyo.tfm を作って

~~~~
%#!ptex2pdf -l -u
\documentclass{utarticle}
\AtBeginDvi{\special{pdf:mapline piyo UniJIS-UTF16-V ipaexm.ttf}}
\begin{document}
“これはクオートです”
\end{document}
~~~~

を処理すると，dvipdfmx 実行中に

~~~~
char=0x201c(8220)
Tried to set a nonexistent character in a virtual font
char=0x201d(8221)
Tried to set a nonexistent character in a virtual font
~~~~

が出て，クオートが何も表示されなくなります。

https://twitter.com/munepixyz/status/416420459026989056

**Comment by aminophen** [comment]
とりあえず UCS mode の `-m` オプションで `set2` が欠落していることに気づいたので，r44772 で write.c に修正を入れておきました。これで少なくとも

~~~~
Tried to set a nonexistent character in a virtual font
~~~~

とか

~~~~
dvipdfmx:fatal: Premature end of DVI byte stream in VF font
~~~~

とかが出る可能性はなくなりました。

もう一点，同じブロックの中に

~~~~ c
	case 0x2019: /* ’ */
	case 0x201d: /* ” */
		if (jfm_id == 9 && minute) { /* 縦書き時はミニュートへ変換 */
			if (afp) {
				if (code == 0x2019)
					sprintf(buf2,"CH <216C>");
				else
					sprintf(buf2,"CH <216D>");
				rewind(afp);
~~~~

というコードがあるのですが，

~~~~ c
	case 0x2019: /* ’ */
	case 0x201d: /* ” */
		if (jfm_id == 9 && minute) { /* 縦書き時はミニュートへ変換 */
			if (afp) {
				if (code == 0x2019)
					sprintf(buf2,"CH <2032>");
				else
					sprintf(buf2,"CH <2033>");
				rewind(afp);
~~~~

の間違いではないかと疑っています。（その少し手前の方にある「開きクオート」

~~~~ c
	case 0x2018: /* ‘ */
	case 0x201c: /* “ */
~~~~

の所は afp への書き出しで UTF-16 エンコードを使っているのに，「閉じクオート」の方は JIS エンコードとなっているので，どちらか一方は間違っているはずです。（とはいうものの，そもそも AFM ファイルの使い道を理解できていないので，テストのやり方がわかりません…）

**Comment by zr-tex8r** [comment]
自分も“マルチバイトのAFM”というのは見たことがない……、多分昔の“CID形式フォント”に付属するものなのかな……？（それなら現在はもう使われることはない？）

原理的には「AFMは常にJISコード」という仕様の可能性もあるけど、かな詰めの処理を見る限りは「UCSモードではAFMはUTF-16」という仕様の想定、でいいのではないかと思います。

**Comment by aminophen** [comment]
> “マルチバイトのAFM”

私が知っているものは

- ftp://akagi.ms.u-tokyo.ac.jp/pub/dos/TeX/

にある afm-a2bk.zip の中身，だけです。展開すると rml.afm, rmlv.afm, gbm.afm, gbmv.afm が得られます。中身を見ると `EncodingScheme JIS12-88-CFEncoding` と書かれているようで，これが Adobe の「AFM 仕様書」に書かれているとおりの典型的なエンコードらしいです。

…で，これの makejvf での使い方が私には解りません。

調べてみてわかったのは，`-a` と `-k` は，アスキーが実装したオプションでありながら「サポート外」と明記されていることです。ptex-fonts/README_makejvf より：

~~~~
  ---以下２つは正式にサポートされているオプションではありません---

    -a  <AFMファイル名>
        PSフォントのAFMファイル名を指定します。
       かな詰めフォント作成時に使用します。

    -k  <数値>
        かな詰めマージンを指定します。文字幅を1000として整数で指定。
        -aオプションと共に使用します。
~~~~

> 原理的には「AFMは常にJISコード」という仕様の可能性もあるけど、かな詰めの処理を見る限りは「UCSモードではAFMはUTF-16」という仕様の想定、でいいのではないかと思います。

実装をみるかぎり，そうするほかに手段がないように見えますね。（「UTF-16 な AFM」は見たことがないので，実質的に「サポート外」ということになりそうですが。）

**Comment by zr-tex8r** [comment]
実際問題として、upTeXを使っていて「ダブルミニュートを（U+301D自体ではなく）ダブルクオートで入力したい」と考える人っているんですかね？ もしいるんだったら、秒記号で作った偽物ではなくて「本物」を出したほうが適切な気がしますね。シングルミニュートはUnicodeにもないのでそういうわけにいかないですが。

**Comment by aminophen** [comment]
> かな詰めの処理を見る限りは「UCSモードではAFMはUTF-16」という仕様の想定

ということで r44775 のコミットで全部 UTF-16 に統一しました。

> upTeXを使っていて「ダブルミニュートを（U+301D自体ではなく）ダブルクオートで入力したい」と考える人っているんですかね？

当該処理が私には完全には追いきれていないのでまた後で考えます。

**Comment by aminophen** [comment]
> upTeXを使っていて「ダブルミニュートを（U+301D自体ではなく）ダブルクオートで入力したい」と考える人っているんですかね？ もしいるんだったら、秒記号で作った偽物ではなくて「本物」を出したほうが適切な気がしますね。シングルミニュートはUnicodeにもないのでそういうわけにいかないですが。

よく理解できていないので，どの挙動を指しているのでしょう？

**Comment by t-tk** [comment]
ダブルミニュート(U+301D, U+301F, U+301E)の字形で出力したいupTeXユーザーが、入力時にダブルクオート(U+201C, U+201D)で入力したい、と考える人はいるか? vfなどでダブルクオートをダブルミニュートに置き換える機能をあてにして、そんな要望をする人はいるか?
という趣旨と私は理解しました。

**Comment by zr-tex8r** [comment]
要するに：
ucsモードでかつ`-m`指定の場合、ダブルクオート（U+201C/201D）の出力はどうするか？

 1. jisモードと同様で、U+2033（秒記号）を加工してダブルミニュートの字形を作り出す。  
    現在の動作。
  2. 何もしない。ucsモードではシングルクオート（U+2018/2019）だけ対応することにする。  
    JISコードとは異なりUnicodeにはダブルミニュート（U+301D/301F）があるのだから、upTeXでダブルミニュートを出力したいのなら、それを書けばよい、という考え。
  3. 本物のダブルミニュート（U+301D/301F）を代わりに出力する。

で、もし、「upTeXで縦書き文書を作っていてダブルミニュートを出力したい」という場合に、「ダブルクオートが入力されることが多い」のであれば、現状の1よりも3の方が適切ではないか、ということでした。

**Comment by aminophen** [comment]
なるほど。「ucs モードでかつ -m 指定の場合」は，この issue で直るまで使われて来なかったと推測します。ですから，あまり悩まずに，いま適切と思う仕様を実装すればよいでしょう。

私も，現状で動くようになった 1 よりも，3 の方が適切と思います。

**Comment by t-tk** [comment]
私の今の考えでいうと 1 または、「ucs モードでかつ -m 指定の場合」はサポートしない、です。
理由は後ろ向きになりますし美しくありませんが、些末な仕様を作りこんでもこの部分で喜んでいただけるユーザーさんが想定しにくいからです。
約10年前にupTeXの開発の方針について、土村さんやZRさんと議論していただいたことを思い出します。
開発項目は本件とは別ですが、pTeXの過去の資産との互換性をupTeXでどこまで保証するのか、複雑な割に効果が薄い機能までupTeXでサポートするべきか、後々メンテナンスの面で過剰な負担にならないか、というような話です。(このあたり→ [QA49177](http://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/49177.html), [QA49182](http://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/49182.html), [QA49183)](http://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/49183.html)
10年前の状況は、Unicode対応といいつつ内部はSJISで動いているようなソフトが多くあり、「ダブルミニュート（U+301D/301F）を出したければダブルミニュート（U+301D/301F）を入力してください」とは言いにくい状況だったと思います。なので、レガシーエンコーディングからの移行に関する機能は気にしていました。
しかし、今となっては「ダブルミニュート（U+301D/301F）を出したければダブルミニュート（U+301D/301F）を入力してください」でもよいように思います。
upTeXも10年目になりますし、過去に使われてなかったであろう機能ならば、今不具合が見つかったとしてもいっそのこと廃止してしまうチャンスと見ることもできます。

もちろん、その機能の有用性や費用対効果の面でaminophenさんの考えは私と異なるかもしれず、私の意見を強要するものではありません。

**Comment by aminophen** [comment]
コメントありがとうございます。

> 過去に使われてなかったであろう機能ならば、今不具合が見つかったとしても
> いっそのこと廃止してしまうチャンスと見ることもできます。

確かにおっしゃる通りで，「レガシーエンコーディングからの移行に関する機能」は再実装の必要はないと思います。そこで，これに当たるのかどうか調べているうちに JLReq の以下の記述が気にかかりました。

「3.1.1 縦組と横組で異なる約物など」の b の注 2，注 3

> ダブルクォーテーションマークに似た括弧類にダブルミニュート（始めダブルミニュート[〝] (REVERSED DOUBLE PRIME QUOTATION MARK)及び終わりダブルミニュート[〟] (LOW DOUBLE PRIME QUOTATION MARK)）がある（図 3.6）．これは，縦組専用の括弧類であり，横組では使用しない．

> 左ダブルクォーテーションマーク[“] (LEFT DOUBLE QUOTATION MARK)及び右ダブルクォーテーションマーク[”] (RIGHT DOUBLE QUOTATION MARK)は，横組専用の括弧類であり，縦組では使用しない．

`-m` は「クオートが入力された場合，横書きではそのままクオートを，縦書きではミニュートを出力する」という機能です。憶測にすぎませんが，pTeX だった時代にこれが実装された理由は「ダブルミニュート（U+301D/301F）の入力が難しいから」というより，「縦ならミニュート，横ならクオート」に自動で切り替わって便利だから，だと思います。そう考えると，upTeX でもサポート外にするのは勿体無いです。

OTF パッケージが upTeX が広く行き渡ってもなお使われている理由の一つに，「約物などの字形が縦と横で自動的に切り替わる」という機能が非常に強力なこと，が挙げられると思っています。「縦書きかどうかを考えて入力する文字を変える」という手間が省けるのは大きいです。

やっぱり私は 1（直したばかりの現状維持）または 3（本物のダブルミニュート）を支持します。

----

ところで，齋藤さんの OTF パッケージ (japanese-otf) も，本物のミニュートに置き換える仕様です。 http://psitau.kitunebi.com/otf.html により：

> v1.1b2(2003/10/24)
> 縦組み用のVFでクォーテーションマークをミニュートに変更[mkjvf, vf]

一方，japanese-otf-uptex では置き換えが起こらず，ダブルクオートのままです。この変化は意図的だったのでしょうか？

~~~~ tex
\ifx\ucs\undefined
  \documentclass{tarticle}
  \usepackage{otf}
\else
  \documentclass{utarticle}
  \usepackage[uplatex]{otf}
\fi
\begin{document}
ダブルクオート入力“□□”\par
ダブルミニュート入力〝□□〟
\end{document}
~~~~

**Comment by aminophen** [comment]
次に，「後々メンテナンスの面で過剰な負担にならないか」の視点でも考えてみます。

write.c のコードを見ると，JIS mode の writevf() と UCS mode の writevfu() は非常によく似ています。「似ている」という事実はメンテナンス性にプラスに働いていると思いますし，「似ている」状態から外れるとメンテナンス性が著しく落ちる恐れがあります。

JIS mode では `-m` オプションをサポートし続ける必要があります（pTeX 標準の tmin10.vf は `-m` 有効で作られている）。そうすると，コードの類似性という観点からは 1.（現状維持）が最善でしょうね。3. を実現しようとすると，ダブルミニュート（Unicode にある）とシングルミニュート（Unicode にない）を分けて複雑化してしまうので，そういう要望が実際には来ていない今実装する必要はないのかもしれませんね。

**Comment by aminophen** [comment]
上記2つの観点から考えた結果，

> jisモードと同様で、U+2033（秒記号）を加工してダブルミニュートの字形を作り出す。現在の動作。

を維持しようと思います。

- `-m` オプション自体は有用で，サポートし続けたい。
- makejvf の JIS mode と UCS mode の互換性・ソースコード類似性ともに担保でき、メンテナンスに都合がよい思われる。
- 「縦組みではダブルクオートを本物のダブルミニュートに置き換える」は、 #18 で提案している `REPLACE` 機能を使えば容易に実現できるはずである。

が理由です。

**Comment by t-tk** [comment]
> 「縦組みではダブルクオートを本物のダブルミニュートに置き換える」は、 #18 で提案している REPLACE 機能を使えば容易に実現できるはずである。

なるほど。
これは明快な仕様でかつ、機能も高く、さらに実装も簡潔になりそうです。良い提案だと感心しました。賛同します。

**Comment by aminophen** [comment]
試験的に， `REPLACE` と `MOVE` を実装してみました。

- https://gist.github.com/aminophen/8d29344483fe0804106ecec69d317609

これを適用して

~~~~
REPLACE	201C	301D
REPLACE	201D	301F
~~~~

file.txt を上のように書いて

~~~~
$ makejvf -i -u jis -t file.txt upjisr-v uprml-v
~~~~

とすると，期待どおりダブルクオートがダブルミニュートに置き換わると思います。

japanese-otf-uptex の件，調べようと思って別のマシンで同じソースをコンパイルすると，japanese-otf と同じ挙動になりました。昨日試した環境が意図せず壊れていた可能性が出たため，ひとまず無視してください。すみません。

**Comment by t-tk** [comment]
実装ありがとうございます。gistの方も覗いていますが、ぼんやり眺めるくらいしか出来ていません。
~~エキスパートしか使わない機能だと思うので、細かい点は実装者の都合優先で簡潔にする、規定のパターンに合わなければすぐ落とす、という感じで良いと思います。~~
いや、余計なお世話でした。お任せします。

japanese-otf-uptex の件、私のおぼろげな記憶とreadmeのhistoryを頼りにいうと、
2010.03.28 Ver.0.05と2012.01.02 Ver.0.07 の間でベースをotfstableからotfbetaに変えた、とあるので、その間で縦書きクオートの動作を変えたような記憶があります。
ただ、japanese-otfの場合は、Hiraginoという具体的なフォントの想定がありかつ変換先がAdobe-JapanのCID指定だったはずで、上記で話題の -m オプションとは似て非なるものという気もします。

**Comment by aminophen** [comment]
`-m` オプションの機能を makejvf.1 にドキュメント化しておきました。(r44850-r44851)

japanese-otf-uptex の件，私もバージョンによって約物の出方が違ったような記憶がうっすらと… 定かではありませんが，最新版は簡単なテストで japanese-otf と同じなので問題ないのでしょう。

`-m` オプションは完了ということで close します。
