### ISSUE TITLE
[eptex] \epTeXinputencoding プリミティブで Segmentation fault

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#23]
全くの偶然で発見したのですが，以下のソースが落ちるようです。

OS X 10.11.6 El Capitan，r45220 のセルフビルドです。

~~~~
$ cat a.tex
\epTeXinputencoding utf8\show\x

$ eptex a
This is e-pTeX, Version 3.14159265-p3.7.1-161114-2.6 (utf8.euc) (TeX Live 2018/dev) (preloaded format=eptex)
 restricted \write18 enabled.
entering extended mode
(./a.texSegmentation fault: 11
~~~~

**Comment by aminophen** [comment]
`\epTeXinputencoding utf8\relax` でも落ちます。

**Comment by abenori** [comment]
なおしました（ 002c2b2 ）．

**Comment by aminophen** [comment]
（各種 SNS とか TeX Live svn へのコミットも含めて）みなさまありがとうございます。

ターミナルから

~~~~
$ eptex -ini \\epTeXinputencoding utf8\\relax\\end
~~~~

はやはり落ちるように思いますが，まあ当たり前といえば当たり前…

**Comment by h-kitagawa** [comment]
> 当たり前といえば当たり前…

とはいうものの，やはり Segfault が出るのはおかしいので，
876ce044ee0b67f832cfb33c10e8a37fff4d6300 で修正しました．

```
\scantokens{\epTeXinputencoding utf8\relax}
```
 のように \scantokens 由来の仮想ファイルや \openin，あるいはターミナルから呼んでいるときは \epTeXinputencoding は無効で，
```
Warning: \epTeXinputencoding is ignored, since I am current reading
from the terminal.
```
などと警告をログに出すようにしました（無効にする，という仕様で良いか？）．

**Comment by aminophen** [comment]
> 876ce04

（コードは全く理解できませんが）動作確認しました。特殊なケースはほぼ発生しないと思いますので，落ちなくなれば十分だと思います。

**Comment by abenori** [comment]
どうもすみません，ファイルがない時があるのは失念……コード，よさそうですね．

> あるいはターミナルから呼んでいるときは 

エンコーディングを指定するというのは意味を持つんですよね．整合性という観点からは動いた方がよいのかもしれない？（個人的には使う人いないと思うけど……．）

**Comment by h-kitagawa** [comment]
確かに，どこまで需要があるかわからないですが
「ターミナルの入力エンコーディングと出力エンコーディングを独立して設定できる」
機能はあったらおもしろいかもしれません．

**Comment by abenori** [comment]
ターミナルからでもエンコーディングが切り替わるようにしてみましたが，どうでしょうか？（ 9da5208 ）

**Comment by aminophen** [comment]
リビルドしてテストしてみると，ほぼ問題なく動いているように見えましたが

~~~~
$ eptex \\epTeXinputencoding u\\relax
~~~~

が一回だけ落ちた気がするので，再現するかどうか調べてみます。

**Comment by aminophen** [comment]
やはり「ターミナルから，認識不能なエンコードが指定された場合」に落ちていました。

ここで気になったのですが，\epTeXinputencoding で認識できない値がソース中で指定された場合，これは単に無視されるという挙動に見えますが，代わりに警告が出るか，「現在そのファイルがどのエンコードで読まれているか」を表示するプリミティブがあれば何かと便利そうな気がしました。

**Comment by h-kitagawa** [comment]
> ターミナルから，認識不能なエンコードが指定された場合

しまった，log_file が開かれていないのにも関わらず， log_file に警告を出しているのがいけないようですね．

**Comment by aminophen** [comment]
> これは単に無視されるという挙動

おっと，log file には警告が出ていたのですね，見落としていました。

**Comment by aminophen** [comment]
> log_file が開かれていないのにも関わらず， log_file に警告を出しているのがいけない

確かに，以下のようにしてみると落ちなくなりました。

~~~~ pascal
      if (log_file=0) then
        begin wterm_cr;
        wterm('Unknown encoding `');
        fputs(stringcast(name_of_file + 1), term_out);
        wterm('''');
        end
      else
        begin wlog_cr;
        wlog('Unknown encoding `');
        fputs(stringcast(name_of_file + 1), log_file);
        wlog('''');
        end
      end
~~~~

**Comment by h-kitagawa** [comment]
24ac783d3b098042930f8060542163f8db14e822 で，各種の TeX の診断メッセージと同じように
「端末とログの両方に出力するのは，ログが開いている かつ \tracingonline>0 のとき 」としてみました．

**Comment by aminophen** [comment]
ありがとうございます。大丈夫そうです。

**Comment by abenori** [comment]
おお，これはチェック不足……ありがとうございます．（そもそも僕はなぜログファイルにしかメッセージを出さないようにしていたのだろう．）

**Comment by aminophen** [comment]
ChangeLog をつけて master にマージしました。ありがとうございました。

**Comment by aminophen** [comment]
> \epTeXinputencoding works also with the terminal (H. Kitagawa and N. Abe)

Done ([r45249](https://www.tug.org/svn/texlive?view=revision&revision=45249)).
