### ISSUE TITLE
\shipout の組方向が dvipdfmx で変？

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#30]
以下のソースを ptex で処理して得る DVI を dvipdfmx で処理すると，期待とは違うものが出てきました。

~~~~ tex
% test.tex
\ifx\directlua\undefined\else\input luatexja.sty\fi
\tracingonline1
\showboxdepth10000
\showboxbreadth10000

\shipout\vbox{\tate A\showlists}

\shipout\vbox{B\showlists}

\end
~~~~

この2ページめのログは

~~~~
### yoko direction, horizontal mode entered at line 8
\hbox(0.0+0.0)x20.0
\tenrm B
spacefactor 999
### yoko direction, internal vertical mode entered at line 8
prevdepth ignored
### yoko direction, vertical mode entered at line 0
prevdepth ignored

! OK.
l.8 \shipout\vbox{B\showlists
                             }
?
~~~~

これを見る限り横組みで出るべきだと思いますが，dvipdfmx の出力では B が縦に回転しています。

`dvips test.dvi && ps2pdf -dAutoRotatePages=/None test.ps` の出力及び `pxdvi test.dvi` での見た目は期待どおりだったので，ptex ではなく dvipdfmx の問題と思われます。

**Comment by h-kitagawa** [comment]
2ページ目を「BCDE」にすると，各文字が縦に寝たまま回転していますね．dvi.c 中の関数 `clear_state` で `pdf_dev_set_dirmode(0);` を忘れている？

**Comment by aminophen** [comment]
> dvi.c 中の関数 `clear_state` で `pdf_dev_set_dirmode(0);` を忘れている？

ありがとうございます。そういうことらしいので [r45449](https://www.tug.org/svn/texlive?view=revision&revision=45449) でコミットしました。
