### ISSUE TITLE
[ptex] \discretionary と和文，組方向

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#31]
以前ツイッターで

「\discretionary 内部，もしくは周囲に和文が絡むと `! This can't happen (disc4).` が出る現象」の対処法は，結局「第3引数を \hbox に入れる」とすれば常に安全なのか？

という疑問が出ていたと思います。この疑問がネックになってパッケージを作れないということもありえるので，issue にしてみます。関連：[forum:416](https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=416)，[qa:55536](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/55536.html)

（エラーが出る原因が「ptex の \kanjiskip / \xkanjiskip 挿入処理，および禁則ペナルティ挿入」である，ということは実際に私も確認してみましたが…。）

----

ところで，pTeX の \discretionary では `dir_node` が考慮されていないように見えます（落ちる，とかはありませんが，2: の結果は変で，組方向情報が消えているようです）。

~~~~ tex
\ifx\directlua\undefined\else\input luatexja.sty\fi
\tracingonline1 \showboxdepth10000 \showboxbreadth10000

1: a\discretionary{o}{s}{b\hbox{\yoko c}}d\showlists

2: a\discretionary{o}{s}{\tate b\hbox{\yoko c}}d\showlists

\end
~~~~

以下のようにすれば ptex でも `! Improper discretionary list.` エラーを出せますが，luatexja だと上のソースの 1: はエラーが出ませんから，それとは違う挙動になってしまいます。

~~~~ patch
Index: Build/source/texk/web2c/ptexdir/ptex-base.ch
===================================================================
--- Build/source/texk/web2c/ptexdir/ptex-base.ch	(revision 45449)
+++ Build/source/texk/web2c/ptexdir/ptex-base.ch	(working copy)
@@ -5341,7 +5341,7 @@
       begin print_err("Improper discretionary list");
 @y
   begin if not is_char_node(p) then
-    if (type(p)>rule_node)and(type(p)<>kern_node)and
+    if ((type(p)>rule_node)or(type(p)=dir_node))and(type(p)<>kern_node)and
          (type(p)<>ligature_node)and(type(p)<>disp_node) then
       if (type(p)=penalty_node)and(subtype(p)<>normal) then
         begin link(q):=link(p); free_node(p,small_node_size); p:=q;
~~~~

**Comment by zr-tex8r** [comment]
「2の期待値は`! Improper discretionary list.`エラー`」、ということ？

**Comment by aminophen** [comment]
私は 2 はエラーでいいんじゃないかな，と思っていました。luatexja はそうしているみたいですし。

**Comment by zr-tex8r** [comment]
了解です。（まあそれで普通ですよね。）

**Comment by h-kitagawa** [comment]
3cb476c64abc53c251ff5eb4b3d21986a317fd16 で\discretionary でも組方向チェックをすることにしました．

**Comment by aminophen** [comment]
> 3cb476c

コードを見る限り大丈夫そうだったので [r45463](https://www.tug.org/svn/texlive?view=revision&revision=45463) でコミットしました。
