### ISSUE TITLE
dvipdfmx などで「実際に使われたファイル」のリスト

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#33]
これまた TeXConf2017 の話題からです。

CI で TeX を使うためには，「必要最小の TeX Live をインストールする」という方法が有用だと思います。しかし tlmgr は依存関係を完全には解決できないため，このようなインストールが難しくなっています。

そういう理由で，現在は「必要最小のファイル」を知るために

[1] とりあえず CI で適当に scheme-small あたりをインストールして，コンパイルしてみてエラーが出たらそれを元に逐次 tlmgr で追加していく

とされているとお聞きしました。これが面倒なので

[2] フルインストールしてある環境で，何かオプションをつけてコンパイルすると，「実際に使われたファイルのリスト」を得ることができないか？

という意見がありました。ところが，これがどうも現状では難しいようです。

----

〜TeX については `-recorder` オプションを使うと，拡張子 .fls のファイルができて

````
INPUT /usr/local/texlive/2017/texmf-dist/web2c/texmf.cnf
INPUT /(中略)/.texlive2017/texmf-var/web2c/eptex/platex.fmt
OUTPUT test.log
INPUT /usr/local/texlive/2017/texmf-dist/tex/platex/base/jltxdoc.cls
````

のような感じで一行ずつ記録される，という話はご存知の方もいると思います。

一方 dvipdfmx については，このようなオプションが私には見つけられていません。「標準エラー出力を解析すればいけるのでは」という話もありましたが，かなり厳しそうです。

- ログをうるさくする `-v` 〜 `-vvvv` オプション（現在は個数 4 まで意味があるらしい；例えば dvipdfm-x/fontmap.c などに効く）を使うと，読まれたファイルが一応表示される。
    - しかし，ファイル読込ごとにログが行分割されるわけではないので，これを parse して cmap の「H」などを検知するのは，外からはほぼ不可能。
    - そのうえ，「gbm.tfm」などは `-vv` にするとそのフルパスを表示できる一方，「H」や「glyphlist.txt」などのフルパスは表示できない。

ドキュメントのビルドは dvipdfmx まで通る必要がありますので，「実際に使われたファイルのリスト」を得るオプションを付けられると便利なのではないか？ というわけで issue にします。

**Comment by aminophen** [comment]
補足：dvipdfmx のファイル読込とは言っても結局は kpathsea で探しているはずなので，「kpathsea 側にそういう機能があればその方が良い」と思いますが，そちらも私は見つけられていません。

**Comment by t-tk** [comment]
dvipdfmx に --kpathsea-debug というオプションがありますが、それは役に立つでしょうか?
かすかな記憶では、ファイルの検索とopenはこれで分かったような記憶があります。

**Comment by aminophen** [comment]
おお，なんかいけそうです。ありがとうございます。値は[ここ](http://tug.org/texinfohtml/kpathsea.html#Debugging)を見ればわかって，一番詳しいのが -1，fopen/fclose だけ表示するのが 4 ですね。これなら parse はできそうです。
