### ISSUE TITLE
和文のコントロールシンボル

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#37]
texjporg/uplatex#3 が気になったので， @t-tk さんの[コメント](https://github.com/texjporg/uplatex/issues/3#issuecomment-344900349)にある

> (u)pTeX で、「トークン列の（＝\string以外の）文字列化の際に、制御記号については「後に空白文字を補う」挙動が抑止される。」が出来るようになれば良いのでしょうか?

をちょっとやってみました。 → [Gist](https://gist.github.com/aminophen/c8e1e819085ba8f3247a70d294a2b698)

今のところ，和文文字を2バイト固定と仮定したコードですので，pTeX のみサポートしています（upTeX の方は内部処理を理解できなかったのですみません…）が，手元では上においたテストケースがうまく動いていますし，\DeclareRobustCommand 及び e-TeX の \protected も期待通りに動くような気がします。

edit: よくみるとなぜか t を pool_pointer にしている… 型はもっと適切なものにすべきでしょうね。

**Comment by h-kitagawa** [comment]
ありがとうございます．jachar_cs ブランチを作って Gist を適用させておきました．

**Comment by aminophen** [comment]
> 4fa3ecf で multistrlen() を使うようにしてみました．これで upTeX でも動いているようです

ありがとうございます。あとは uptex-m.ch で (cat=hangul) も空白をプリントすればいいんでしょうか。

> （ただ，\pdfprimitive 関連の修正とは干渉するのでそのときにはもう一回修正）．

pdftex の修正は今朝 TL svn に取り込まれたようですね。対応はお任せいたします。

**Comment by aminophen** [comment]
jachar_cs ブランチの bf0be0d が #29, #37 両方の問題をクリアしたことを確認しました。merge してよければマージして ChangeLog をつけようと思いますが，よろしいでしょうか。

**Comment by h-kitagawa** [comment]
> merge してよければマージして ChangeLog をつけようと思いますが，よろしいでしょうか。

よろしくお願いします（本来なら ChangeLog は私が自分で書くべきでしたね……）．

**Comment by aminophen** [comment]
[r45950](https://www.tug.org/svn/texlive?view=revision&revision=45950) で ptex-base.ch のコントロールシンボルの扱いを，[r45956](https://www.tug.org/svn/texlive?view=revision&revision=45956) で pdfutils.ch 等の \pdfprimitive の修正を，それぞれコミットしました。

**Comment by h-kitagawa** [comment]
[texjporg/ptex-manual](https://github.com/texjporg/ptex-manual) で pTeX の入力プロセッサの状態遷移図を書いていたときに，和文のコントロールシンボルについて気になる挙動があったので再オープンします．

以下のソースをタイプセットすると，「3.」で示された（`\ ` でない）コントロールシンボルの直後の改行の際に，欧文文字からなる `\@`，和文文字からなる `\】` 問わず，改行が空白扱いされます．

```tex
\kcatcode`】=18

\def\】{◆}
\def\@{◆}

1. \】◇，\@◇

2. \】%
◇, \@%
◇

3. \】
◇, \@
◇

4. \】 ◇, \@ ◇

\bye
```

この挙動を「仕様」としても良いですが，個人的には「和文の直後の行末は無視」にそろえて，
`\】` のような和文コントロールシンボルの直後の改行も無視させたいと思っています．
[control_symbol](https://github.com/texjporg/tex-jp-build/tree/control_symbol) ブランチにコードを書いておきました．

**Comment by h-kitagawa** [comment]
> control_symbol ブランチにコードを書いておきました．
肝心の ptex-base.ch の変更点をコミットするのを忘れていました……．

**Comment by aminophen** [comment]
「既存のものに影響が出ないか」という観点で調べてみたいので，とりあえず「和文コントロールシンボルの実例」を思いついくままに挙げていきます。

(1) okumacro の倍角ダーシ

(2) OTF パッケージ http://psitau.kitunebi.com/otf.html のマニュアル (PDF 2004/3/5) によると

![303e8960-37d3-4250-9d61-fd630e06c842](https://user-images.githubusercontent.com/9957466/50423540-2decf300-089a-11e9-8de7-094a73ce73af.jpeg)

![4724e1c1-5057-494d-871a-1387cf4897c3](https://user-images.githubusercontent.com/9957466/50423541-2e858980-089a-11e9-9531-00b04ca70359.jpeg)

他にもあるでしょうか。

**Comment by aminophen** [comment]
他の例です。

(3) jlreq クラスの \[全角空白] （和文間隔を挿入）

(4) パッケージ化されている訳ではないが，ぶら下げ組を 
https://qdaibungei.github.io/latex/2018/01/12/burasage.html のようにしている人もいる。

**Comment by aminophen** [comment]
まだご提案の control_symbol ブランチを試せていないのですが…。

今まで列挙したうち，『「コントロールシンボルの直後の改行」が実際のソースで今まであり得たか』を考えると，(1) と (2) は外して良さそうですね。

(1) 倍角ダーシは `\――` のように，コントロールシンボル本体 `\―` + 引数 `―` の組が必要で，「コントロールシンボル直後に改行」はできなかったはず。

(2) 全て `\ajLig{`[記号][文字]`}` のショートカットなので，多分くっつけているはず。

``` tex
\documentclass[autodetect-engine]{jlreq}
\usepackage{okumacro}
\usepackage{otf}

\usepackage[hiragino-elcapitan-pron]{pxchfon}
\begin{document}

%\def\showthe\kcatcode`#1{\expandafter\show\csname #1\endcsname}
%\def\showthe\kcatcode`#1{}

% ===== jlreq の和文コントロールシンボル用文字
% 全て pLaTeX/upLaTeX とも \kcatcode 18
\showthe\kcatcode`　 % 全角空白

% ===== okumacro の和文コントロールシンボル用文字
% 全て pLaTeX/upLaTeX とも \kcatcode 18
\showthe\kcatcode`— % U+2014
\showthe\kcatcode`― % U+2015
\showthe\kcatcode`− % U+2212
\showthe\kcatcode`－ % U+FF0D

% ===== OTF の和文コントロールシンボル用文字
% ほとんどは pLaTeX/upLaTeX とも \kcatcode 18
\showthe\kcatcode`○ [\○秘]
\showthe\kcatcode`● [\●問]
\showthe\kcatcode`□ [\□印]
\showthe\kcatcode`■ [\■◇]
\showthe\kcatcode`◇ [\◇ほ]
\showthe\kcatcode`◆ [\◆答]
\showthe\kcatcode`▽ [\▽〒]
\showthe\kcatcode`△ [\△!]
\showthe\kcatcode`（ [\（株）]
\showthe\kcatcode`※ [\※湯]
\showthe\kcatcode`！ [\！か]

% ただし upLaTeX では以下の 2 つのみ \kcatcode 17
\showthe\kcatcode`゛
\showthe\kcatcode`゜

[\゛う\゜か]\par
% => upLaTeX ではコントロールワードとみなされるので ! Undefined control sequence.

[\゛ う\゜ か]\par
% => これなら OK

\end{document}
````

----

さて，(3) は JLReq で言うところの「和字間隔」ですが， ソース中で行末に書かれる機会もありそうな気がしました。(4) はなおさら行末に書かれていそうです。

時間ができたら control_symbol ブランチをビルドし，いろいろ試してみます。

**Comment by aminophen** [comment]
大変遅くなりましたが，いろいろ試してみて，結局 @h-kitagawa さんの

> 「和文の直後の行末は無視」にそろえて，\】 のような和文コントロールシンボルの直後の改行も無視させたいと思っています．

に賛成します。

(4) の例をもとにすると，この変更で「組版結果が変わる例」を作ることができるわけですが，むしろ変更後の挙動のほうが望ましいような気が個人的にはします。

``` tex
\documentclass[twocolumn]{jsarticle}
\def\、{\nobreak\makebox[1zw][l]{、}}%
\def\。{\nobreak\makebox[1zw][l]{。}}%
\begin{document}
てふ\。ゆきだるま\。てふ\。日本\。
てふ\。ゆきだるま\。てふ\。日本\。
てふ\。ゆきだるま\。てふ\。日本\。
てふ\。ゆきだるま\。てふ\。日本\。
てふ\。ゆきだるま\。てふ\。日本\。
てふ\。ゆきだるま\。てふ\。日本\。
\end{document}
```

他に懸念がなければ，近いうちにマージします。

**Comment by aminophen** [comment]
r49957 でコミット。

ptex-manual への記載はどうしましょうか？

**Comment by h-kitagawa** [comment]
> ptex-manual への記載

[ptex-manual/d7add6a](https://github.com/texjporg/ptex-manual/commit/d7add6a7b6049778a0b0cdc0f87ade4e95c97a51), [ptex-manual/16a91b2](https://github.com/texjporg/ptex-manual/commit/16a91b22b8149fe90f15348686a30bffd98a4761) で追記．

**Comment by aminophen** [comment]
追記ありがとうございます。こちらは閉じます。
