### ISSUE TITLE
FAM256 パッチのプリミティブの \show

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#38]
表題の通り，eptex / euptex で期待と違う結果でした。

~~~~
*\show\odelimiter
> \odelimiter=\delimiter.

*\show\omathaccent
> \omathaccent=\mathaccent.

*\show\omathchar
> \omathchar=\mathchar.

*\show\oradical
> \oradical=\radical.
~~~~

**Comment by aminophen** [comment]
というか，Aleph も同じ結果になるようなのですが，これはそういう仕様なのでしょうか？

**Comment by h-kitagawa** [comment]
> Aleph も同じ結果になるようなのですが，これはそういう仕様なのでしょうか？

単純に考慮忘れじゃないのかなあ，と思うのですが……．

> Aleph の方はもっとひどくて，\show\omathchardef → \toksdef になる。

tex.web だと次のようになっているので，単に case がないだけですね．
```
shorthand_def: case chr_code of
  ...
  othercases print_esc("toksdef")
  endcases;
```

**Comment by aminophen** [comment]
e-pTeX は 192d237 で大丈夫そうです。こちらでは Aleph の方をいじってみました。これで良さそうでしょうか？

- https://gist.github.com/aminophen/ba6fb588c995b7d132864d8f5c45ef78

Aleph には \hfi, \vfi というプリミティブは実装されていない，みたいですね。omfi.ch にも存在しないようで，単に fi という無限大レベルだけが定義されているような感じでしょうか。

**Comment by h-kitagawa** [comment]
> Aleph

これで良さそうだと思います．

>  \hfi, \vfi というプリミティブは実装されていない

無限大レベル fi を実装したときに，「じゃあ対応物として当然 \hfi, \vfi, \pagefistretch もあるよね」と思って e-pTeX に入れてしまいました^^; しかし，teTeX3 の doc-1.12.ps や doc-1.8.dvi には \hfi, \vfi についても言及されています．方針が途中で変わったんですかね？

**Comment by aminophen** [comment]
だん (r46059, r46060).

2008年の W32TeX には素の Omega (This is Omega, Version 3.141592-1.23.2.3 (WEB2C 7.5.6)) が入っていたのですが，そちらでも undefined になります。（\show を使わずに素で \vfi してもエラー）まあずっとα版みたいな状態でしたから，方針が途中で変わったんでしょう。
