### ISSUE TITLE
[eptex] "! File ended while scanning text of ???"

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#39]
またまた細かい issue です。e-pTeX の pdfTeX 互換プリミティブの `! File ended ...` エラー

~~~~
@ @<Tell the user what has run away...@>=
~~~~

で出るべきエラーメッセージ内容が一部出ません。いろいろテストすると pdfTeX も一箇所 NG でした。

~~~~ tex
%% 両方NG
\pdfstrcmp{}{ %
% eptex,pdftex => ! File ended while scanning text of ???.
\endinput
~~~~

~~~~ tex
%% e-pTeX NG
\pdfmdfivesum{ %
% eptex => ! File ended while scanning text of ???.
% pdftex => ! File ended while scanning text of \pdfmdfivesum.
\endinput
~~~~

~~~~ tex
%% e-pTeX NG
\pdffiledump{ %
% eptex => ! File ended while scanning text of ???.
% pdftex => ! File ended while scanning text of \pdffiledump.
\endinput
~~~~

~~~~ tex
%% 両方OK
\pdfstrcmp{ %
% eptex,pdftex => ! File ended while scanning text of \pdfstrcmp.
\endinput
~~~~

~~~~ tex
%% 両方OK
\pdffilemoddate{ %
% eptex,pdftex => ! File ended while scanning text of \pdffilemoddate.
\endinput
~~~~

~~~~ tex
%% 両方OK
\pdffilesize{ %
% eptex,pdftex => ! File ended while scanning text of \pdffilesize.
\endinput
~~~~

`sprint_cs(warning_index);` がうまく動かずに tex.web の print() 関数の `if s<0 then s:="???" {can't happen}` が走っているのだと思いますが，私の環境だけでしょうか？

**Comment by h-kitagawa** [comment]
自動的に close されてしまったので修正報告を兼ねて reopen．
pdfTeX では scan_keyword にも修正が加えられていたのに気づきませんでした．

**Comment by aminophen** [comment]
ありがとうございます．pdfTeX も XeTeX も同様の修正で ok になるようです。

- pdfTeX: https://gist.github.com/aminophen/906fe5795d3b00e3ea2bd76d9cb2dde0
- XeTeX: https://gist.github.com/aminophen/839cfffc2aa1e6a383e0326599460d88

e-pTeX は r46068 でコミットしたので，他はこちらでレポートしておきます。

→ [XeTeX](https://sourceforge.net/p/xetex/bugs/144/)
