### ISSUE TITLE
disp_node と段落頭の JFM グルー

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#40]
おそらくよく知られている話だと思いますが，

~~~~ tex
\documentclass{tarticle}
\begin{document}
\noindent「あいうえお」\par
\noindent「あいうえお」
\end{document}
~~~~

の一行目と二行目が揃わない，というのがあります。

- https://groups.google.com/forum/#!msg/fj.comp.texhax/RGnqUnabZOk/9MxDz0pxY5gJ

これを突き詰めてみると，pTeX の「段落頭に disp_node が挿入されると，結果的に JFM グルーが消えない」という挙動が原因のようです。以下のソースの \showbox0 でわかるように，「直前の段落が和文で終わったかどうか」が次の行の `\noindent （` の JFM グルーに影響します。

~~~~ tex
\tracingonline1
\showboxdepth10000
\showboxbreadth10000

\def\ADJUST{\ybaselineshift3pt\relax}

% こちらの挙動が問題；disp_node が原因で頭の JFM グルーが残る
\setbox0=\vbox{%
\ADJUST
\noindent 「あA\par   % 先頭が disp_node → JFM グルーが残る
\noindent 「あA」\par % ここも先頭が disp_node → JFM グルーが残る
\noindent 「あA\par   % 直前の段落が和文で終わっているので先頭が disp_node でない
\noindent いEお}\showbox0 \box0

% 今回とは無関係
\setbox2=\vbox{%
\ADJUST
「あA\par   % 先頭が \hbox(0.0+0.0)x20.0 → JFM グルーが残る
「あA」\par % 同様
「あA\par   % 同様
いEお}\showbox2 \box2

% こちらも今回とは無関係
\parindent0pt
\setbox4=\vbox{%
\ADJUST
「あA\par % \parindent 由来の \hbox(0.0+0.0)x0.0 が JFM グルー非消滅の原因
「あA」\par % 同様
「あA\par   % 同様
いEお\par}\showbox4 \box4
\end
~~~~

（\everypar{\inhibitglue} すればそれまで，なのですが。）

**Comment by aminophen** [comment]
> 「直前の段落が和文で終わったかどうか」が次の行の `\noindent （` の JFM グルーに影響します。

この挙動を逆利用すると，

「pLaTeX の \adjustbaseline の実装次第で，この pTeX の挙動を回避することもできる」

ということみたいです。\adjustbaseline の最後に欧文文字以外を組めばいいので，

~~~~ tex
\def\adjustbaseline{%
    \setbox\adjust@box\hbox{\char\jis"3441}%"
    \cht\ht\adjust@box
    \cdp\dp\adjust@box
    \cwd\wd\adjust@box
    \cvs\normalbaselineskip
    \chs\cwd
    \cHT\cht \advance\cHT\cdp
  \iftdir
    \setbox\adjust@box\hbox{\tbaselineshift\z@ M}%
    \adjust@dimen\ht\adjust@box
    \advance\adjust@dimen\dp\adjust@box
    \advance\adjust@dimen-\cHT
    \divide\adjust@dimen\tw@
    \advance\adjust@dimen\cdp
    \advance\adjust@dimen-\dp\adjust@box
    \tbaselineshift\adjust@dimen
    \setbox\adjust@box\hbox{\char\jis"3441}% <= ここを追加
  \fi}
~~~~

という実装がありえることになります。

**Comment by aminophen** [comment]
disp_jfm ブランチ (7e3841f) のようにすると，リスト先頭の displace の直後でも JFM グルーを抑制できると思いますが，どうでしょう？

**Comment by aminophen** [comment]
> disp_jfm ブランチこの対処により，以下のコードで JFM グルーが消えない現象も直ります。

~~~~ tex
\documentclass{article}
\begin{document}
\xkanjiskip0pt
\ybaselineshift10pt
あA\hbox{（あ）}A\par % \hbox 内部最初の JFM グルーが消えなかったのが，直る。
\ybaselineshift0pt
あA\hbox{（あ）}A\par
\end{document}
~~~~

**Comment by h-kitagawa** [comment]
今回の JFM グルーの話と半分別件になると思いますが．「段落頭に disp_node が挿入される」ことが不思議に思っています．DVI に hbox を出力する hlist_out では `disp:=0;` が先頭部にあるので，段落頭に disp_node 0.0 がなくても問題はないと思いますが……．

**Comment by aminophen** [comment]
> DVI に hbox を出力する hlist_out では disp:=0; が先頭部にあるので，段落頭に disp_node 0.0 がなくても問題はないと思いますが……．

確かに，段落頭の disp_node 0.0 は必要なさそうですね。その方が綺麗だと思います。

**Comment by aminophen** [comment]
235a2d6 のコメントや Slack に飛んでしまいましたが，改めてこちらへ。

「（段落頭や折り返し行頭の JFM グルーを）メトリック側で調整」は少し不親切な気がしてきました。メトリックを一般ユーザが作るにしても，公式サイドが作るにしても，課題があると思います。

一般ユーザが作る場合，

- 「JFM / VF の作り方」「特定の JFM を使うように LaTeX ソース中で指定する方法」を解説している文献が少ない → JFM に新機能が追加されても，使いこなせるユーザは少ないだろう。

公式に TeX Live で配布する場合，

- pTeX 標準 / upTeX 標準 / OTF パッケージ / JLReq クラスのそれぞれについて，従来式（互換性対策）と新方式の JFM を作る必要がある → 必然的に VF も含めるため，単純にファイル数と容量が倍になる。パッケージの方でも，インタフェースを考えなければならない。

それよりも，この issue の大元であった

> 段落頭に disp_node が挿入されると，結果的に JFM グルーが消えない
> 「直前の段落が和文で終わったかどうか」が次の行の \noindent （ の JFM グルーに影響

という問題を直したいと思っています。

> DVI に hbox を出力する hlist_out では disp:=0; が先頭部にあるので，段落頭に disp_node 0.0 がなくても問題はない

だけの変更を適用してここは一旦閉じ，段落頭などの JFM は改めて別の issue にしたいです。

なお，「「文字コード XXxxxx，文字クラス yy」を xxxx XXyy と格納するようにすれば U+10000 以上も指定可能」は #8 に対して有用そうなので，そちらで始めてみました。

**Comment by h-kitagawa** [comment]
>> DVI に hbox を出力する hlist_out では disp:=0; が先頭部にあるので，段落頭に disp_node 0.0 がなくても問題はない
>
> だけの変更を適用してここは一旦閉じ，段落頭などの JFM は改めて別の issue にしたいです。

なるほど，話題も発散しているのでひとまずそうしましょうか．

**Comment by aminophen** [comment]
> 次のソースを実行した時，\box1 内部ではベースライン補正量が 0.0 にリセットされないまま終わるので，段落頭の 2つ目の \unhcopy1 で挿入される「い」にベースライン補正がかかってしまいます：

おっと，unbox する場合というのは気づきませんでした。ということは，私が最初に試していた disp_jfm ブランチの方が安全でしょうか？

**Comment by h-kitagawa** [comment]
（調べるだけでコードを書く余裕がしばらくないのですが）
現状でも和文文字で段落が終わり，その後和文文字で段落が始まった場合には段落頭の disp_node が入らないので，以下のソースで「え」の位置がおかしくなります．
```tex
\ybaselineshift10pt
\setbox0=\vbox{%
  いi\par uう\par えe\par
  \setbox1=\lastbox\unskip\unskip
  \setbox2=\lastbox\unskip\unskip
  \setbox3=\lastbox\unskip\unskip
  \leavevmode\unhcopy3\unhcopy1
}
\showboxbreadth10000
\showboxdepth10000
\tracingonline1
\showbox0\box0\end
```

そのため，次のようにするのが良いのかもしれません．
 * 段落や \hbox が文字で始まった場合にはいつも（ベースラインシフト量が0でも，欧文文字であっても） disp_node を入れる←unbox 時を考慮
 * disp_jfm ブランチのように，「\noindent の段落開始時」「\hbox 開始直後」の disp_node のあとの JFM グルー挿入は無視
 * \indent の段落開始時については機会があれば別 issue で．

**Comment by h-kitagawa** [comment]
> 段落や \hbox が文字で始まった場合にはいつも（ベースラインシフト量が0でも，欧文文字であっても） disp_node を入れる←unbox 時を考慮

d141d3f79 で実装してみました．実際には段落・\hbox の開始と文字の間にボックスなどが挟まることがあるので，「まだ現在のリストで disp_node を挿入していない場合は入れる」ことにしました．

**Comment by aminophen** [comment]
今度は，例えば unbox を一切しない以下のようなケース

```` tex
\tracingonline1
\showboxdepth10000
\showboxbreadth10000

\def\ADJUST{\ybaselineshift3pt\relax}

\setbox0=\vbox{%
\ADJUST
\noindent 「あA\par
\noindent 「あA」\par
\noindent 「あA\par
\noindent いEお（）\par
\noindent ・えE\par
\noindent ・うE}\showbox0 \box0
\bye
````

の処理結果では，

````
..\displace 0.0
..\displace 0.0
````

や

````
..\displace 0.0
..\penalty 10000(for kinsoku)
..\displace 0.0
````

のような連続が新たに発生するようですが，これはそういうものなのでしょうか？ 一応，master と disp_jfm の間のログ差分を貼ってみます。（グルーを挿入しない件は意図通りに動いているようです。）

```` diff
 > \box0=
 \vbox(67.77588+3.0)x469.75499, yoko direction
-.\hbox(7.77588+3.0)x469.75499, glue set 440.60512fil
+.\hbox(7.77588+3.0)x469.75499, glue set 445.18715fil
+..\displace 0.0
 ..\displace 0.0
-..\glue(refer from jfm) 4.58203 minus 2.291
 ..\tenmin 「
 ..\penalty 10000(for kinsoku)
 ..\glue(\kanjiskip) 0.0 plus 0.4 minus 0.4
@@ -20,9 +20,9 @@
 ..\glue(\rightskip) 0.0
 .\glue(\parskip) 0.0 plus 1.0
 .\glue(\baselineskip) 1.22412
-.\hbox(7.77588+3.0)x469.75499, glue set 435.56499fil
+.\hbox(7.77588+3.0)x469.75499, glue set 440.14702fil
+..\displace 0.0
 ..\displace 0.0
-..\glue(refer from jfm) 4.58203 minus 2.291
 ..\tenmin 「
 ..\penalty 10000(for kinsoku)
 ..\glue(\kanjiskip) 0.0 plus 0.4 minus 0.4
@@ -39,6 +39,7 @@
 .\glue(\parskip) 0.0 plus 1.0
 .\glue(\baselineskip) 1.22412
 .\hbox(7.77588+3.0)x469.75499, glue set 445.18715fil
+..\displace 0.0
 ..\tenmin 「
 ..\penalty 10000(for kinsoku)
 ..\glue(\kanjiskip) 0.0 plus 0.4 minus 0.4
@@ -53,6 +54,7 @@
 .\glue(\baselineskip) 1.22412
 .\hbox(7.77588+3.0)x469.75499, glue set 424.23174fil
 ..\displace 0.0
+..\displace 0.0
 ..\tenmin い
 ..\displace 3.0
 ..\glue(\xkanjiskip) 2.40553 plus 1.0 minus 1.0
@@ -72,6 +74,7 @@
 .\glue(\baselineskip) 1.22412
 .\hbox(7.77588+3.0)x469.75499, glue set 444.34232fil
 ..\penalty 10000(for kinsoku)
+..\displace 0.0
 ..\tenmin ・
 ..\glue(refer from jfm) 3.04276 minus 3.04276
 ..\tenmin え
@@ -83,10 +86,10 @@
 ..\glue(\rightskip) 0.0
 .\glue(\parskip) 0.0 plus 1.0
 .\glue(\baselineskip) 1.22412
-.\hbox(7.77588+3.0)x469.75499, glue set 441.29956fil
+.\hbox(7.77588+3.0)x469.75499, glue set 444.34232fil
 ..\displace 0.0
 ..\penalty 10000(for kinsoku)
-..\glue(refer from jfm) 3.04276 minus 3.04276
+..\displace 0.0
 ..\tenmin ・
 ..\glue(refer from jfm) 3.04276 minus 3.04276
 ..\tenmin う
````

**Comment by h-kitagawa** [comment]
「現在のリストで disp_node をどこかに挿入した」フラグの設定を抜かしたところがありました．commit f23c7259d64f443983f95198dd0867ccd9f6610d で修正．

**Comment by aminophen** [comment]
> 「現在のリストで disp_node をどこかに挿入した」フラグの設定を抜かしたところがありました．commit f23c725 で修正．

確認しました。ありがとうございます。

**Comment by aminophen** [comment]
今回の disp_jfm ブランチをまとめると

- 段落や \hbox の開始後，最初に組まれる文字の時点で，まだ現在のリストに disp_node が挿入されていなければ，（ベースラインシフト量が0でも，欧文文字であっても）disp_node を入れる ← unbox 時を考慮
- 「\noindent の段落開始時」「\hbox 開始直後」の disp_node のあとの JFM グルー挿入は無視

ということで，問題なさそうなのでマージしておきます。

**Comment by aminophen** [comment]
[r46500](https://www.tug.org/svn/texlive?view=revision&revision=46500) でコミット。
