### ISSUE TITLE
use proper commiter emails in git commits

### ISSUE THREAD

**Issue by norbusan** [texjporg/tex-jp-build#5]
I have used git-svn for checking out TL svn, too, and I used the following `authorsfile`, configuration in `.git/config`:
`````
[svn]
        authorsfile = .git/usermap
`````
[usermap.txt](https://github.com/texjporg/tex-jp-build/files/659760/usermap.txt)

The authorsfile is attached.

**Comment by t-tk** [comment]
Norbert-san,
Thank you for your proposal.
I set '--authors-file' option when I checked out the TeX Live svn repository today.
From today, you will find better commit log in our git repository.

I also commit the usermap file in the master branch as "usermap_texlive_svn.txt".
Some mail addresses in the usermap seems obsolete.
If you find any obsolete mail address, please update it.

**Comment by norbusan** [comment]
Perfect, thanks!
