### ISSUE TITLE
[eptex] \lastnodesubtype 命令の追加

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/tex-jp-build#52]
platex/#63 や 「\inhibitglue の効力」(#28)，[aminophenさんのツイート](https://twitter.com/aminophen/status/967546426371670016) に関連して，「最後のノードの subtype を返す」`\lastnodesubtype` 命令を 6c491886583903092d24c263b87faaeee1950f06 で作ってみました．

現状ではただ subtype を返すだけ（リストの先頭では -1，文字ノードはつねに 0）です．本格的にやるにはドキュメントに戻り値の意味の表を作らないといけませんね．

**Comment by aminophen** [comment]
ありがとうございます。グルーの方は，\lastnodesubtype さえあればマクロで目的達成できそうです。

（ペナルティの方は，追加で pTeX に「`subtype=kinsoku_pena` なペナルティを強制発行するプリミティブ」があれば，\lastnodesubtype との組み合わせで #27 を解消できるかも，と考えている途中で，まだ自分の考えがまとまっていません。）

**Comment by aminophen** [comment]
228aa30 で inhibitglue.tex の中に \lastnodesubtype を活用したマクロを書いてみて，JFM グルーノードを消せることをを確認しました。

[edit] \protected を忘れたので de5f867 で付けました。

**Comment by aminophen** [comment]
b027e24 で，JFM カーンにも subtype を設定して「4: JFM 由来カーン」にしてみました。

```` tex
\tracingonline1
\showboxdepth10000
\showboxbreadth10000

\font\x=jis\x
\setbox0=\hbox{あ……あ}\showbox0

\newfam\mx
\textfont\mx=\x \scriptfont\mx=\x \scriptscriptfont\mx=\x
\jfam\mx
\setbox0=\hbox{$あ……あ$}\showbox0

\bye
````

````
> \box0=
\hbox(7.77588+1.38855)x38.48865, yoko direction
.\displace 0.0
.\x あ
.\penalty 250(for kinsoku)
.\glue(\kanjiskip) 0.0 plus 0.4 minus 0.4
.\x …
.\penalty 250(for kinsoku)
.\kern 0.0 (refer from jfm)
.\x …
.\x あ

> \box2=
\hbox(7.77588+1.38855)x38.48865, yoko direction
.\displace 0.0
.\mathon
.\x あ
.\x …
.\kern 0.0 (refer from jfm)
.\x …
.\x あ
.\mathoff
````

**Comment by h-kitagawa** [comment]
> JFM カーンにも subtype を設定して「4: JFM 由来カーン」
> tex.web l.17558, l.17588, l.17621 に subtype=normal の条件があるが，変更不要？

もともと normal が（欧文）フォントのカーニングや数式由来のものを表す subtype なので，個人的には分けなくても良いと思っています．

**Comment by aminophen** [comment]
> もともと normal が（欧文）フォントのカーニングや数式由来のものを表す subtype なので，個人的には分けなくても良い

欧文フォントのカーニングと同じと考えれば，確かに新設する必要はないですね。元に戻しておきましょう。

**Comment by aminophen** [comment]
ペナルティについては，元の tex.web にはそもそも subtype という概念がなく，「明示的な \penalty」と「\interlinepenalty，\clubpenalty，\widowpenalty のような通常のペナルティ」が分かれていません。ptex-base.ch で `explicit` という新たな subtype を作ってはまずいでしょうか？

**Comment by aminophen** [comment]
→ と思ったけど，ちょっと考えたらマクロを展開する段階では通常のペナルティはリストに入っていないので，区別しなくても subtype=0 なペナルティは必ず明示的なペナルティでよいのか。

**Comment by aminophen** [comment]
\inhibitglue の挙動の方はもう少し検討が必要なので，それとは独立に \lastnodesubtype の追加コミットだけ git cherry-pick して master に持って行き，TeX Live svn にコミットしておきます。

**Comment by aminophen** [comment]
Done ([r46753](https://www.tug.org/svn/texlive?view=revision&revision=46753)).
