### ISSUE TITLE
[e-TeX] 起動直後の \lastnodetype

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#54]
eptexdoc.pdf の内容に対する質問ですが，e-pTeX のプリミティブの挙動が絡むのでここで。

plain e-pTeX を起動した直後の \lastnodetype は 0 となっているようです。eptexdoc.pdf に依るとこれは char_node なのだと思いますが，直後で \lastnodechar の値を取得すると -1 になります。

~~~~ tex
%#!eptex
\showthe\lastnodetype
\showthe\lastnodechar
\bye
~~~~

eptexdoc.pdf に依ると \lastnodechar は

> 現在構築中のリストの「最後のノード」が文字由来であれば，そのコード番号（内部コード）を内部整数として返す．

とありますが，この挙動だけを見ると「最後のノードが文字由来であるが，その内部コードが返っていない」ように見えてしまいます。

**Comment by h-kitagawa** [comment]
> 最後のノードが文字由来であるが，その内部コードが返っていない

`\showlists` で調べると空リストになっていることから，`\lastnodetype` の返り値の方がおかしいと思います．pdfTeX, XeTeX でも同様の症状が起こっており，LuaTeX のみ `\showthe\lastnodetype` で期待される -1 が返ってくる状況です．

**Comment by aminophen** [comment]
> \lastnodetype の返り値の方がおかしい

おっと，そっちでしたか… タイトルを変えておきます。

**Comment by aminophen** [comment]
0872ed3 で問題なさそうです。pdfTeX / XeTeX の方も以下のコードで直せるようなので

https://gist.github.com/aminophen/efbe2cb69b8412ae2a11bf238b015ce8

tex-k メーリングリストに投稿しておきます。

**Comment by aminophen** [comment]
#52 に依ると e-pTeX の \lastnodesubtype は

> リストの先頭では -1，文字ノードはつねに 0

なので，そちらも初期化を追加したほうが良いかもしれません。

**Comment by h-kitagawa** [comment]
>  e-pTeX の \lastnodesubtype の初期化

b6976164967f8665a9c3ef33469d3fc0781537f8 で追加．

**Comment by aminophen** [comment]
r47096, r47100 でコミットされました。
