### ISSUE TITLE
[(u)pTeX] 内部コードの -kanji-internal オプション

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#55]
「(u)pTeX の内部コードを TeX ソースを使って判定する」ということをやろうとして，以下の .tex ソースを書いてみました。これを `-kanji-internal=<enc>` で指定してコンパイルすると，pTeX は期待通り SJIS あるいは EUC に切り替わるようですが，なぜか upTeX では効きません。

```` tex
\catcode`{=1
\catcode`}=2
\ifnum\jis"3441="3441
  \message{JIS}
\else
  \ifnum\jis"3441="8ABF
    \message{SJIS}
  \else
    \ifnum\jis"3441="B4C1
      \message{EUC}
    \else
      \ifnum\jis"3441="6F22
        \message{UTF8}
      \else
        \message{What?}
      \fi
    \fi
  \fi
\fi
\end
````

upTeX でも，INI モード (-ini) の場合は -kanji-internal が効くようです。upTeX には「フォーマットファイルが読み込まれた場合は効かない」という仕様があるのでしょうか？

**Comment by t-tk** [comment]
私としては、仕様として意図的にそのようにした、ということはありません。
もしも期待通り動くように修正できるなら修正に賛成します。

現象はこちらでも再現しました。
バナーのところは ``--kanji-internal`` の指定通りになるみたいですね。不思議です。

````
$ uptex --kanji-internal=sjis kcode.tex 
This is upTeX, Version 3.14159265-p3.8.0-u1.23 (utf8.sjis) (Web2C 2018/dev) (preloaded format=uptex)
 restricted \write18 enabled.
(./kcode.tex UTF8 )
No pages of output.
Transcript written on kcode.log.
````

**Comment by zr-tex8r** [comment]
(u)pTeXのフォーマットファイルは一般的には内部漢字コードに依存するので、フォーマット生成時と異なる `-kanji-internal` を与えた場合の動作は、一般的には未定義になると思います。

**Comment by t-tk** [comment]
> (u)pTeXのフォーマットファイルは一般的には内部漢字コードに依存する

そうすると、フォーマット生成時と異なる ``--kanji-internal`` を与えることは実用上役に立たないものになるでしょうから、現状の動作でも問題無さそうですね。

**Comment by aminophen** [comment]
> (u)pTeXのフォーマットファイルは一般的には内部漢字コードに依存する

**Comment by aminophen** [comment]
r23753 (5608b9b) で，(e-)upTeX だけに「フォーマットファイルを読み込む時に，その冒頭を undump して，フォーマット作成時の内部コード状態を読み出し，必ずその内部コードを使う」という処理が入っていることがわかりました。どうせ

> (u)pTeXのフォーマットファイルは一般的には内部漢字コードに依存するので、フォーマット生成時と異なる -kanji-internal を与えた場合の動作は、一般的には未定義にな

のであれば，これは (e-)(u)pTeX すべてに共通の実装として「フォーマット生成時と異なる -kanji-internal を与えると警告を出して無視する」とするのが安全そうです。あとでコードを書きます。

**Comment by aminophen** [comment]
> (e-)(u)pTeX すべてに共通の実装として「フォーマット生成時と異なる -kanji-internal を与えると警告を出して無視する」とするのが安全そう

kanji-internal ブランチで実装してみました。食い違った場合は

```
Option --kanji-internal invalid when a format file is loaded.
I'll stick to euc.
```

のような感じになります。いかがでしょうか？

**Comment by t-tk** [comment]
方針に異論ありません。賛成します。

**Comment by h-kitagawa** [comment]
私もこの方針に賛成します．

`-ini` オプションと `iniptex` というプログラム名以外では virtual mode になるよう（Web2C のマニュアルには「1行目を `%&ini` にする」方法も紹介されているが，効かない？）なので，バナー出力段階で`--kanji-internal` を無視するという警告 or エラーにしてしまうことは可能でしょうか？

**Comment by aminophen** [comment]
> バナー出力段階で`--kanji-internal` を無視するという警告 or エラーにしてしまう

可能かどうか，まだ私にはわかりません。ただ，pTeX 系列の処理手順としては

- ターミナルへのバナー出力
- フォーマットファイル読込
- 実際の入出力（ログファイルへの出力開始もこのとき）

の順で行なっているようなので，仮にやってしまうと「フォーマットと同じ内部コードが -kanji-internal で指定されたとき」にも警告かエラーが出てしまうと思います。

今の実装なら，「フォーマットと同じ内部コードが -kanji-internal で指定されたとき」を何も出さず素通りできる，という利点があります。もちろん，その副作用？として，「起動時オプションとフォーマットの内部コードが食い違うとき」に

- ターミナルへのバナー出力には `(utf8.sjis)` と出て， ←(1)
- 例の警告 (Option --kanji-internal invalid 以下略) が出て，内部コードは強制的に euc になって，
- ログファイルには `(utf8.euc)` と出る ←(2)

という感じで(1)のターミナルと(2)のログの食い違うわけですが。

**Comment by aminophen** [comment]
https://tug.org/pipermail/tex-k/2018-September/002895.html にあるように，ターミナルに出るバナーとログが食い違うのは pTeX に限らず TeX でも，preloaded format でよく起こる話ですし。

**Comment by h-kitagawa** [comment]
> ターミナルとログの食い違い

なるほど，じゃあ現状の kanji-internal ブランチの実装のままでいいですね．

**Comment by aminophen** [comment]
r49955 でコミット，449960 で警告内容をより適切にしました。
