### ISSUE TITLE
epTeX weirdness with \numexpr

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#58]
See http://tug.org/pipermail/tex-live/2018-May/041575.html (report from @josephwright)

**Comment by h-kitagawa** [comment]
Linux などでの再現方法をここに記述しておきます．まず，Joseph さんの報告にあるソース
```code tex
\RequirePackage{expl3}
\def\test#1{\number\numexpr#1\relax}
\message{\test{ 0 + ( 1 + 2 }}
\let\foo\relax
\def\test#1{\number\numexpr#1\foo}
\message{\test{ 0 + ( 1 + 2 }}
\csname stop\endcsname
\bye
```
を nametest.tex とでもして保存します．

次に，（想定されている platex の呼び出し方ではないですが）
```
platex -kanji-internal=*** nametest.tex
```
を実行します．`***` の項目には `euc` か `sjis` を入れます．`euc` では 2 つ目のエラーが
```
! Missing ) inserted for expression.
<to be read again>
                   \foo
```
という意図通りのものになりますが，`sjis` だと
```
! Missing ) inserted for expression.
<to be read again>
                   \foo \BAD.
```
と追加で `\BAD.` が出力されてしまいます．

----
エラー出力の際に `\foo` を出力するトークンリストを見ると，確かに sjis の方が一つ長いのですが，全くわかりません．

**Comment by h-kitagawa** [comment]
エラーの context 出力段階で `check_kanji` がトークン \foo を和文文字と誤判定し，そのため「余分なトークン」が1つ追加されたのが原因のようです． 777e2d67107d9b635a75dba019ee163758956b62 では当該箇所の if 文に条件を追加することで回避しました．

なお，角藤さんからの返信で気づきましたが，upTeX の kanji.c は `check_kanji` 関数の段階で `cs_token_flag` 以上のものに対して false を返すようにしています．こちらのほうが筋が良いような気もします．

**Comment by h-kitagawa** [comment]
>この check_kanji 関数をいじるほうが筋が良いような気もします．

f067a5a91dda840a7637385f53f32286ac31704c として実装してみました．

----
なお，uptexdir/kanji.c では
```
if (c > CS_TOKEN_FLAG) return false;
```
となっていますが，私は等号付きの
```
if (c >= CS_TOKEN_FLAG) return false;
```
の間違いかなあ，となんとなく思っています．ptexdir/kanji.c では等号付きの形で入れました．

**Comment by t-tk** [comment]
このようにしてみました。https://github.com/texjporg/tex-jp-build/commit/31d589e2bf981102fedf895188051e9151e4e2ae
異論なければ後ほどTeX Live svn にコミットしておきます。

uptex/kanji.c で ``c==CS_TOKEN_FLAG`` ならば、従来のコードでも次の行でfalseが返りますね。
しかし、修正しました。

**Comment by h-kitagawa** [comment]
[tags/texlive-2018.1](https://github.com/TeX-Live/texlive-source/tree/texlive-2018.1) で修正が反映されたので，完了とします．
