### ISSUE TITLE
[dvipdfm-x] Incorrect TrueType cmap table?

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#6]
（前に書いたコメントは間違っていたようなので削除しました）

https://github.com/texjporg/tex-jp-build/blob/master/source/texk/dvipdfm-x/cidtype2.c#L597

~~~~ c
    /*
     * This part contains a bug. It may choose SJIS encoding TrueType cmap
     * table for Adobe-GB1.
     */
~~~~

この bug の再現例がわかればよいのですが…

**Comment by t-tk** [comment]
dvipdfmxの[当時の開発元](http://project.ktug.org/dvipdfmx/)(ChoFさんのところ)で探してみると、
該当部分は[2003年11月25日の更新](http://cvs.ktug.org/viewcvs/dvipdfmx/src/cidtype2.c?revision=1.9&view=markup)から存在するようです。

**Comment by norbusan** [comment]
コミットをお願いします！

**Comment by aminophen** [comment]
調べていただきありがとうございます。This part contains a bug とあるのですが、MWE がどこを探しても見つからないので、bug があるのかどうか私にはわかっていません。（CTeX のドキュメントに「このバグのせいで STSong.ttf が読めない」という旨が書かれていますが、これは実際はフォントの cmap table が Adobe-GB1 を含んでいないためであることがわかっていて、無関係でした。）

**Comment by aminophen** [comment]
再現例が長い期間でていないので，とりあえず閉じておきます。
