### ISSUE TITLE
upBibTeXが特定の方法でsubstringを使うとフリーズする

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#64]
埋もれないようにリンクだけ貼っておきます。

https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2496

**Comment by isamuwada** [comment]
和田です。

> 309 行目に + 1 を追加するのが最も楽なのですが、294 295 298 行目のようにappend_char したら incr しているように書き換え、308 から 311 行目を削除された方がベターだと思います。

上記は NG ですね :-< 。incr(sp_ptr) を append_char 毎にやったら multibytelenの判定ができなくなってしまいますから ...
ですので  309行目の行末に ; を追加し、310 行目の else を削除し 311 行目の incr(sp_ptr); のインデントを調整の方が良いかなと思います。もちろん ループで処理できた方がいいのですが ...

**Comment by miimou** [comment]
もとの投稿をした者です。

本issueは4つに分けて考えることができるものです。

* (仕様a)文字列値をスタックから取り出した時点で文字列プールから文字列の実体が論理的に削除される。（オリジナルのBibTeX由来の仕様。[bibtex.web l.7297付近](https://github.com/texjporg/tex-jp-build/blob/ee5d039d704aa0613d4c7827dce0c1794a06356e/source/texk/web2c/bibtex.web#L7297)）
* (問題1) 文字列プールにゴミが入っている場合があり、このときはそのゴミが代わりに消えて値が削除されない。(この問題の原因は発見できず。今回の問題が見つけにくい原因。)
* (問題2) 「substring$の範囲がマルチバイト文字の1バイト目に始まり最終バイトに終わっていない場合補正する処理」（参考：[前回のフリーズ解決時のforum:2006の投稿](https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2006#p12493)）が2回に分けて書かれている（pBibTeX由来の問題。[1回目](https://github.com/texjporg/tex-jp-build/blob/aba20f44c6034b4ec3c5bffab798676ac2f9628a/source/texk/web2c/uptexdir/upbibtex.ch#L259)、[2回目](https://github.com/texjporg/tex-jp-build/blob/aba20f44c6034b4ec3c5bffab798676ac2f9628a/source/texk/web2c/uptexdir/upbibtex.ch#L301)）
* (問題3) 2回目の「補正する処理」の実装がin-placeでないにもかかわらず、in-placeに処理しようとする場合がある。
    - in-placeでない条件: 対象文字列がUTF-8 かつ 対象文字列の第1バイトが1バイト文字 かつ substring$の範囲の開始点が第2バイト かつ 範囲内に3バイト文字が含まれる
        - [upbibtex.chの301行目付近](https://github.com/texjporg/tex-jp-build/blob/aba20f44c6034b4ec3c5bffab798676ac2f9628a/source/texk/web2c/uptexdir/upbibtex.ch#L301)と、[append_char(char)](https://github.com/texjporg/tex-jp-build/blob/ee5d039d704aa0613d4c7827dce0c1794a06356e/source/texk/web2c/bibtex.web#L1373)がstr_pool[pool_ptr++] = charという内容であることをもとに、pool_ptr:=sp_ptr-1の場合を考えてみてください。
    - in-placeに処理しようとする条件: 問題1に該当しない
        - 仕様aにより、処理対象の文字列は文字列プールから削除されているので、pool_ptrは処理対象の文字列の開始位置を指すことになる

本issueは問題3か仕様aを修正することで解決可能です。
（問題1を修正するとこの問題の発生頻度が上がります。
問題2は直接の原因ではありませんが、まっとうに修正すれば本issueをついでに解決すると思われます。）
私が書いたパッチは問題3の「in-placeでない」という点を修正するものです。
in-placeでない原因は、

* 1文字のコピー中にその文字の1バイト目の位置に2バイト目の値を上書きしてしまい
* 3バイト目のコピーの判定とsp_ptrの加算時にその上書き結果を読み込んでしまう

ことです。
私のパッチはこの読み込みを行わないよう、最初に読み込んだ結果を変数に保存しておくというものでした。

私が心配しているのはここで問題1や2を放置してよいのかということです。
とくに問題2の構造は根治できなかった問題に対症療法を施した跡のような不気味さがあります。
もし余力があるのなら取り組んだほうが良いと思うのですが、難しいでしょうか。
難しいなら私の提案はあのパッチの通りです。

**Comment by t-tk** [comment]
@miimou さん、@isamuwada さん、詳しいご報告有り難うございます。
問題があることは認識しました。

TeX Forumに書いていただいているパッチですが、行先頭の空白が消えてしまったせいなのか、上手く当たりません。
TeX Forumの方にパッチを添付ファイルとして投稿して頂くか、
ここで適当なbranchを分けてそこにコミットして頂くか、
pull requestをここに送って下さると検討に入りやすいです。

正直に申しますと、このあたり「BibTeXやpBibTeXが何を処理しているのか理解せずに対症療法的にpBibTeXの2バイト処理をマルチバイト処理に拡張してみた」というのが今までです。
より良い方法があればその方が良いです。

> 問題2の構造は根治できなかった問題に対症療法を施した跡

もし具体的に明快な解決策があれば、そちらに移行したいです。

> ここで問題1や2を放置してよいのか

これも、具体的な障害事例と原因特定と解決策があれば採用したいです。

> 本issueは問題3か仕様aを修正することで解決可能です。

BibTeXの仕様に関わるところまで踏み入って仕様拡張するのは荷が重すぎると思います。
問題3の修正で済むのならば、そちらの方が好ましいと感じます。

**Comment by isamuwada** [comment]
途中経過ですが ....
問題となっている upbibtex.ch 301 行目あたりから 310行目の以下のコードに疑義を挟んだまましばらく時間がかかってしまいました。問題箇所のチェックしてみました。

``` {.pascal}
append_char (str_pool[sp_ptr]);
if multibytelen(str_pool[sp_ptr]) > 1 then
    append_char (str_pool[sp_ptr+1]);
if multibytelen(str_pool[sp_ptr]) > 2 then
    append_char (str_pool[sp_ptr+2]);
if multibytelen(str_pool[sp_ptr]) > 3 then
    append_char (str_pool[sp_ptr+3]);
if multibytelen(str_pool[sp_ptr]) > 0 then
    sp_ptr := sp_ptr + multibytelen(str_pool[sp_ptr])
else
    incr(sp_ptr);  
```

結論から申し上げると、上記コードは概ね正しいです。multibytelen の返す値に対しての処理が不足していますが、そのことが今回の問題を引き起こす主な要因ではないと現時点では考えています。（ですので、この部分に関する疑義の件は撤回します）

さて multibytelen に渡す str_pool[sp_ptr] の1バイト目の情報を調べたところ長さとして -2 を返す 129(0x81) と130(0x82) を渡していたことがわかりました。 
（デバッグ方法は、 「デバッグコード」 の項を参考にしてください）

なお、上記のコードでは -2 の時も文字として処理し sp_ptr を更新していますが、そ れが正しいかどうか今は不明です。

単純に grep で multibytelen を探すと 以下の texk/upmendex/mendex.h ですが、...

``` {.shell}
texk/upmendex/mendex.h
93:#define  multibytelen(a)  ((a)<0xc2 ? 1 : ((a)<0xc2 ? -2 : ((a)<0xe0 ? 2 : ((a)<0xf0 ? 3 : ((a)<0xf5 ? 4 : -1)))))  
```

このマクロ展開が採用されていたら 129(0x81) や 130(0x82) は長さ 1 を返すはずなので、マクロ展開ではなくどこかで関数が定義されていると考え、multibytelen の関 数の在処を探したところ texk/ptexenc/ptexenc.c で定義され、そこから internalUPTEX の時texk/ptexenc/unicode.c の UTF8length を呼び出して長さを求め ていることわかりました。

    texk/ptexenc/ptexenc.c
    275:int multibytelen (int first_byte)
    276-{
    277-    if (is_internalUPTEX()) {
    278-        return UTF8length(first_byte);
    279-    } else if (is_internalSJIS()) {
    280-        if (isSJISkanji1(first_byte)) return 2;
    281-    } else { /* EUC */
    282-        if (isEUCkanji1(first_byte))  return 2;
    283-    }
    284-    return 1;
    285-}  

    texk/ptexenc/unicode.c
    33:int UTF8length(int first_byte)
    34-{
    35-    first_byte &= 0xff;
    36-    if (first_byte < 0x80) return 1;
    37-    if (first_byte < 0xc2) return -2;  /* illegal */
    38-    if (first_byte < 0xe0) return 2;
    39-    if (first_byte < 0xf0) return 3;
    40-    if (first_byte < 0xf5) return 4;
    41-    return -1; /* reserved/undefined */
    42-}
    43-

デバッグコード
--------------

以下のように upbibtex.ch にデバッグコードを付与して multibytelen で utf8の文字が どのように扱われ、それにより str_pool の sp_ptr の変化などを調べてみました。

``` {.diff}
diff --git a/texk/web2c/uptexdir/upbibtex.ch b/texk/web2c/uptexdir/upbibtex.ch
index d0a5bc4d..45c93300 100644
--- a/texk/web2c/uptexdir/upbibtex.ch
+++ b/texk/web2c/uptexdir/upbibtex.ch
@@ -298,6 +298,13 @@ end;
          append_char (str_pool[sp_ptr]); incr(sp_ptr);
          end;
 @y
+
+    write_ln (stderr, 'DEBUG before <sp_ptr=', sp_ptr, '<multibytelen=', multibytelen(str_pool[sp_ptr+0]), '>',
+    '<00=', str_pool[sp_ptr+0], '>',
+    '<01=', str_pool[sp_ptr+1], '>',
+    '<02=', str_pool[sp_ptr+2], '>',
+    '<03=', str_pool[sp_ptr+3], '>');
+
     append_char (str_pool[sp_ptr]);
     if multibytelen(str_pool[sp_ptr]) > 1 then
         append_char (str_pool[sp_ptr+1]);
@@ -309,6 +316,8 @@ end;
         sp_ptr := sp_ptr + multibytelen(str_pool[sp_ptr])
     else
         incr(sp_ptr);
+
+    write_ln (stderr, 'debug after  <sp_ptr=', sp_ptr, '>');
 @z

 @x
```

利用データ
----------

　さかいたかし さんのデータ。

``` {.bash}
=> a.aux <==
\bibstyle{a}
\bibdata{./a}
\citation{a}

==> a.bib <==
@a{a,}

==> a.bst <==
ENTRY{}{}{}
FUNCTION {a}{}

READ

STRINGS{t}

FUNCTION {begin.bib}
{
 "11あ" #2 #200 substring$ #2 #200 substring$ warning$
 "11あ" #2 #200 substring$ #2 #200 substring$ #4 #200 substring$ warning$
}
EXECUTE {begin.bib}
```

上記デバッグ用パッチを当てた upbibtex で試してみた結果
------------------------------------------------------

``` {.shell}
./inst/bin/x86_64-apple-darwin17.7.0/upbibtex a
This is upBibTeX, Version 0.99d-j0.33-u1.23 (utf8.uptex) (TeX Live 2018)
The top-level auxiliary file: a.aux
The style file: a.bst
Warning--I didn't find any fields--line 1 of file a.bst
Database file #1: ./a.bib
DEBUG before <sp_ptr=503<multibytelen=1><00=49><01=227><02=129><03=130>
debug after  <sp_ptr=504>
DEBUG before <sp_ptr=504<multibytelen=3><00=227><01=129><02=130><03=50>
debug after  <sp_ptr=507>
DEBUG before <sp_ptr=513<multibytelen=3><00=227><01=129><02=130><03=0>
debug after  <sp_ptr=514>
DEBUG before <sp_ptr=514<multibytelen=-2><00=129><01=130><02=0><03=0>
debug after  <sp_ptr=515>
DEBUG before <sp_ptr=515<multibytelen=-2><00=130><01=0><02=0><03=0>
debug after  <sp_ptr=516>
Warning--ぁ�    ←文字化け
DEBUG before <sp_ptr=503<multibytelen=1><00=49><01=227><02=129><03=130>
debug after  <sp_ptr=504>
DEBUG before <sp_ptr=504<multibytelen=3><00=227><01=129><02=130><03=50>
debug after  <sp_ptr=507>
DEBUG before <sp_ptr=513<multibytelen=3><00=227><01=129><02=130><03=0>
debug after  <sp_ptr=514>
DEBUG before <sp_ptr=514<multibytelen=-2><00=129><01=130><02=0><03=0>
debug after  <sp_ptr=515>
DEBUG before <sp_ptr=515<multibytelen=-2><00=130><01=0><02=0><03=0>
debug after  <sp_ptr=516>
これ以降フリーズ？エンドレスループ？
```

現在検討中のもの
----------------

upbibtex.ch の 301 行目から 311行目くらいを以下のように multibytelenの返す値 に対応した処理を行えるようにしてみましたが、 1 2 3 4 以外の値の時の処理を単に警告だけでスルーしてしまっているのでエンドレスループになってしまいますので以下のパッチを試すときは 1 2 3 4 以外のにも incr(sp_ptr) する暫定処置が必要です。
 なお、append_char は while ループで書き換えてあります。また、それを行なってもフリーズの状態が解消されるわけでもありません。ですので、ここに来るまでの処理をこれから検討してみます。

``` {.diff}
diff --git a/texk/web2c/uptexdir/upbibtex.ch b/texk/web2c/uptexdir/upbibtex.ch
index d0a5bc4d..7bfbc188 100644
--- a/texk/web2c/uptexdir/upbibtex.ch
+++ b/texk/web2c/uptexdir/upbibtex.ch
@@ -298,17 +298,23 @@ end;
          append_char (str_pool[sp_ptr]); incr(sp_ptr);
          end;
 @y
-    append_char (str_pool[sp_ptr]);
-    if multibytelen(str_pool[sp_ptr]) > 1 then
-        append_char (str_pool[sp_ptr+1]);
-    if multibytelen(str_pool[sp_ptr]) > 2 then
-        append_char (str_pool[sp_ptr+2]);
-    if multibytelen(str_pool[sp_ptr]) > 3 then
-        append_char (str_pool[sp_ptr+3]);
-    if multibytelen(str_pool[sp_ptr]) > 0 then
-        sp_ptr := sp_ptr + multibytelen(str_pool[sp_ptr])
-    else
-        incr(sp_ptr);
+    write_ln (stderr, 'DEBUG before <sp_ptr=', sp_ptr, '<multibytelen=', multibytelen(str_pool[sp_ptr+0]), '>',
+             '<00=', str_pool[sp_ptr+0], '>',
+             '<01=', str_pool[sp_ptr+1], '>',
+             '<02=', str_pool[sp_ptr+2], '>',
+             '<03=', str_pool[sp_ptr+3], '>');
+
+    tpe := multibytelen(str_pool[sp_ptr]);
+    if (tpe > 0) and (tpe < 5) then begin
+         tpe := sp_ptr;
+         while (sp_ptr < tpe) do
+                append_char (str_pool[sp_ptr]); incr(sp_ptr);
+         end
+    else write_ln(stderr,
+                  'ERROR multibytelen return unknown/illegal length was ', tpe,
+                  ' character was ', str_pool[sp_ptr], '.');
+
+    write_ln (stderr, 'debug after  <sp_ptr=', sp_ptr, '>');
 @z

 @x
```

**Comment by t-tk** [comment]
@miimou さん、ありがとうございました。
そのままマージさせていただきました。
TeX Live にもコミットしました。([r48676](http://www.tug.org/svn/texlive?view=revision&revision=48676))

@isamuwada さん、ご検討有り難うございます。
具体的な障害事例と原因特定と解決策がまとまったらまたご教示ください。

**Comment by isamuwada** [comment]
パッチ適用して、文字化けやフリーズしなくなったのを確認しました。
最後の multibytelen を利用したバイトコピーがごっそりなくなっているので C に展開されたコードを見てその意図がわかりました。

それから杞憂に終われば良いのですが、multibytelen を使った表現に以下のものがあります。

````
texk/web2c/uptexdir/upbibtex.ch
223 @y
224        append_ex_buf_char_and_check (name_buf[name_bf_ptr]);
225         if multibytelen(name_buf[name_bf_ptr]) > 1 then
226             append_ex_buf_char_and_check (name_buf[name_bf_ptr+1]);
227         if multibytelen(name_buf[name_bf_ptr]) > 2 then
228             append_ex_buf_char_and_check (name_buf[name_bf_ptr+2]);
229         if multibytelen(name_buf[name_bf_ptr]) > 3 then
230             append_ex_buf_char_and_check (name_buf[name_bf_ptr+3]);
231         name_bf_ptr := name_bf_ptr + multibytelen(name_buf[name_bf_ptr])-1;
````

230 行目までは、今回問題となったような操作中に起点となる name_buf[name_bf_ptr] の 内容が変わることはないので問題はないのですが、231 行目の最後の -1 は文字化けなどの原因になるのではないのか心配です。figureouttheformattedname の一部なのですが、どのようにテストデータを作れば良いのか不明です。

**Comment by miimou** [comment]
@isamuwada さん、
texk/web2c/uptexdir/upbibtex.ch 223行についてですが、
この処理は間違ってはいますが実害を起こさないように見えます。
そして、私としては放置するのがいいだろうと考えます。

対象のコードと結論
=====
問題のパッチが当たる場所を探して見ました。
**問題のパッチ**
```pascal
@x
            if name_buf[name_bf_ptr]>127 then begin
                append_ex_buf_char_and_check (name_buf[name_bf_ptr]);
                incr(name_bf_ptr);
                append_ex_buf_char_and_check (name_buf[name_bf_ptr]);
            end
            else
                append_ex_buf_char_and_check (name_buf[name_bf_ptr]);
@y
        append_ex_buf_char_and_check (name_buf[name_bf_ptr]);
        if multibytelen(name_buf[name_bf_ptr]) > 1 then
            append_ex_buf_char_and_check (name_buf[name_bf_ptr+1]);
        if multibytelen(name_buf[name_bf_ptr]) > 2 then
            append_ex_buf_char_and_check (name_buf[name_bf_ptr+2]);
        if multibytelen(name_buf[name_bf_ptr]) > 3 then
            append_ex_buf_char_and_check (name_buf[name_bf_ptr+3]);
        name_bf_ptr := name_bf_ptr + multibytelen(name_buf[name_bf_ptr])-1;
@z
```
さて、upbibtexをビルドするとWork/texk/web2c/upbibtex.webにできるファイルが
名前に反してpBibTeXまでのパッチを反映し終えたWeb言語のファイルです。（たぶん）
ここから先ほどのパッチが当たる場所を探しますと、次の部分が見つかります。
**pBibTeXのコード**
```pascal
@<Finally output an abbreviated token@>=
begin
name_bf_ptr := name_tok[cur_token];
name_bf_xptr := name_tok[cur_token+1];
while (name_bf_ptr < name_bf_xptr) do
    begin
    if (lex_class[name_buf[name_bf_ptr]] = alpha) then
        begin
            if name_buf[name_bf_ptr]>127 then begin
                append_ex_buf_char_and_check (name_buf[name_bf_ptr]);
                incr(name_bf_ptr);
                append_ex_buf_char_and_check (name_buf[name_bf_ptr]);
            end
            else
                append_ex_buf_char_and_check (name_buf[name_bf_ptr]);
        goto loop_exit;
        end
    else if ((name_buf[name_bf_ptr] = left_brace) and
                                (name_bf_ptr + 1 < name_bf_xptr)) then
      if (name_buf[name_bf_ptr+1] = backslash) then
        @<Finally output a special character and exit loop@>;
    incr(name_bf_ptr);
    end;
loop_exit:
end
```

ここから2つのことが分かります。

* この場所の実装はpBibTeXの時代から間違っている
* この間違いはpBibTeXでもupBibTeXでも無益だが（わずかなコード量の増加を除けば）無害である
    - こちらは他の場所も確認する必要がありますが、私が確認する限り問題ないようです

少し解説しておきます。

この場所の実装はpBibTeXの時代から間違っている
-----
先に挙げたpBibTeXのコードを確認すると、2バイト文字ならポインタを1バイト進め、
1バイト文字ならポインタを進めない、という処理が書かれています。
これは、（[pbibtex.chでの変更](https://github.com/texjporg/tex-jp-build/blob/master/source/texk/web2c/ptexdir/pbibtex.ch#L414-L434)も合わせて考えると）
**ループの「形」**
```pascal
while (name_bf_ptr < name_bf_xptr) do
    begin
    if (lex_class[name_buf[name_bf_ptr]] = alpha) then
        ...
    else if ((name_buf[name_bf_ptr] = left_brace) and
        ...
    ;
    incr(name_bf_ptr);
    end;
```
という「形」を見て、1文字ずつ読みながら判定して処理をしていると理解して、処理した文字が2バイト文字の1バイト目であれば**最後にある```incr(name_bf_ptr);```と合わせて**2バイト進んでもらう必要があると考えた結果であろうと思われます。

ところが、このコードはこの```...```と記した部分でそのままループを抜けてしまいます。
つまり以下のように理解するのが正しいのです。
**ループの「構造」**
```pascal
while (name_bf_ptr < name_bf_xptr) do
    if (lex_class[name_buf[name_bf_ptr]] = alpha) then
        ...
    else if ((name_buf[name_bf_ptr] = left_brace) and
        ...
    else
        incr(name_bf_ptr)
    ;
```
この理解のもとで見ると、**最後にある```incr(name_bf_ptr);```と合わせて**という考え方はおかしいということになります。

この間違いはpBibTeXでもupBibTeXでも無益だが無害である
-----
間違っているならなぜ問題が起こらないのか、という部分を考えるためにはもう少し広い範囲を見る必要があります。
先ほどのコードのループの外側を見てみます。
**変数の扱い**
```pascal
@<Finally output an abbreviated token@>=
begin
name_bf_ptr := name_tok[cur_token];
name_bf_xptr := name_tok[cur_token+1];
while (name_bf_ptr < name_bf_xptr) do
    begin
    if ... then
        begin
        ...（問題のパッチが関係する処理）...
        goto loop_exit;
        end
    else if ...
        ...;
    incr(name_bf_ptr);
    end;
loop_exit:
end
```
```name_bf_ptr```はこの処理の最初に初期化されており、問題の部分を過ぎるとこの処理自体が終了しています。
つまり、間違ってインクリメントしてしまった```name_bf_ptr```は、その時点ですでに“用済み”であり、何をしても構わないと考えられるのです。

実際に```name_bf_ptr```の使用箇所を見て回ったところ、
いずれもここと同様に何らかの値を与えてから処理を開始していました。
つまり、言語仕様の都合でローカル変数にはなっていないものの、これは*ローカル変数的に使われる変数*なのです。

結論・意見
=====
私はこの実装が正しいと思えません。
が、修正する必要もないと思います。

[pbibtex.ch 426行](https://github.com/texjporg/tex-jp-build/blob/22415d2f220dc961200cebe765094ad5d0c59285/source/texk/web2c/ptexdir/pbibtex.ch#L426)も[upbibtex.ch 218行](https://github.com/texjporg/tex-jp-build/blob/22415d2f220dc961200cebe765094ad5d0c59285/source/texk/web2c/uptexdir/upbibtex.ch#L218)も[upbibtex.ch 231行](https://github.com/texjporg/tex-jp-build/blob/22415d2f220dc961200cebe765094ad5d0c59285/source/texk/web2c/uptexdir/upbibtex.ch#L231)も要らない**でしょう**。
ただ、**本当に**ここを変えて良いのか調べようとすると、とても面倒な気がします。
実際のところ、どうやったらここが使われるのか、ここまで記してきた分析をしても私には分かりませんでした。
その確認の手間を考えると、「まあいいんじゃないか、動くなら」ということにするのがいいのかなと思うのです。

**Comment by isamuwada** [comment]
miimou  さん、詳細な解説ありがとうございました。それを参考に自分なりに調べたところ強いて変更するのならコメント付記するくらいですが、最後の「結論・意見」に書かれているような対応でよいと思います。
ありがとうございました。

**Comment by t-tk** [comment]
`name_bf_ptr`の件、了解しました。
実害がないであろうとの意見を受け現状維持としますね。
upbibtex のメンテナンス方針としては以下のように考えています。

* 上流(bibtex, pbibtex)の更新は行われないことを想定
* コードの修正は、原則としてバグ対応やセキュリティ対策などのみ
* 機能の追加は行わない
* コードのリファクタリングなどは行わない

bibtex, pbibtexはもう何年も僅かな更新しか行われていない状況です。
もしも今後(p)bibtexが大きく動き出すと前提から崩れてしまいますが、それは現状あまり想定しにくいです。
有益な課題は他にも沢山あるので私はそちらに力を入れたいと思っています。
機能追加に関しては((u)p)bibtexが有益なソフトである限り新しい要望が出てくる可能性も考えられますが、その都度検討することになると思います。

ここは閉じることにします。また何かあればここのissueを新たに立てるなどお願いします。

**Comment by aminophen** [comment]
関連するのでこちらにも書いておきます。

* pbibtex の substring$ 関数が仕様書通りに動いていないバグが判明したので，その修正を行いたい。
    * upbibtex は #1, #64 などにより大丈夫になっていた。
* pbibtex, upbibtex とも「文字列を途中から又は途中まで切り出す」ときに文字列が短くならないことが原因で無限ループすることがある（現状の仕様通りではあるが，仕様が好ましくない）ので，その修正を行いたい。

この2件について #133 を立てました。TeX Live 2022 のソースコミット締切が近いと思いますので，問題がありましたらお願いします。
