### ISSUE TITLE
dviout-utilのTeX Liveへの導入

### ISSUE THREAD

**Issue by t-tk** [texjporg/tex-jp-build#65]
@aminophen さんが提案してくださった dviout 所収のツールの一部(dvispc, chkfont, propw)を TeX Live に導入しようという件についてです。
大島先生、乙部先生からはご快諾いただきました。有り難うございます。
私のファイルの整理がなかなか進まず作業が止まってしまっていました。
https://github.com/aminophen/dviout-util をベースに作成し、ブランチ https://github.com/texjporg/tex-jp-build/tree/dviout-util を作りました。
TeX Liveへの導入にあたり、いくつか作業を進めて来ました。

- automake, autoconf 関連ファイルの用意
- test の用意
- マルチプラットフォーム対応のため UTF-8化
- dvispcの文字列出力で ptexenc導入。日本語の出力文字コードが選択可能に。upTeXも対応。
   この機能のため -j オプションの代わりに -J オプションを導入。

unixでのfile openに関する小さいバグ修正もありました。

バージョン番号は "Ver.201809xx (TeX Live 2019/dev)" のような風にしました。
`201809xx`の部分は`configure.ac` の `AC_INIT` で指定されています。

まだドキュメントなどに不整合な点が残っていると思います。
忌憚ないご意見をお願いします。

**Comment by aminophen** [comment]
ありがとうございます。

- chkfont という名称の全く別のツール https://linux.die.net/man/6/chkfont が，どうやら Linux に存在しているようです。TeX Live に入れるためには，例えば chkdvifont に名前を変えておく？
- propw について，[r188](http://tug.org/svn/dviout/trunk/util/propw.c?r1=2&r2=188&pathrev=188) で `exit( 2 );` を `goto rep;` に書き直したのですが，私が map file の使い方を勘違いしていたからでした。元に戻します。

**Comment by t-tk** [comment]
chkfont.exe でググると、そちらでもWindows用の別のツールが引っかかるようですね。
名前を変えるのに賛成です。
chkdvifont だと少々長いような気もします。
例えば chkdfont とか。しかしそれだと何だかよく分からないのでやはり chkdvifont にしましょうか。
dvispc と propw は大丈夫そうですね。

propw の内部漢字コードのこと等が分かっていません。今のソースではどこかの動作が壊れているかもしれません。
propw は Windows 上では、オリジナル版と同様に `-#` オプションが利くようになることを期待しています。

https://github.com/aminophen/dviout-util/issues/1 を拝見しました。
dvispc と chkfont については、Window,Mac,Linux, その他プラットフォームで Autoconf に従って正しく make できることを期待しています。
propw ではまだ問題が残るかもしれません。思ったより大変です。

**Comment by aminophen** [comment]
propw はそもそも「Windows の GDI の機能で，システムにインストールされている日本語プロポーショナルフォントのメトリック情報を取得して，PL ファイルを作る」のが主目的のツールなので，Unix に単純に移植してもあまり有用ではない（等幅フォント用の JIS メトリックと等価な PL しか作れない）です。Windows でも，MinGW 等でビルドした場合に GDI にリンク出来るのか等も試したことはありません。

**Comment by t-tk** [comment]
> Unix に単純に移植してもあまり有用ではない

それならば、propw は今回の TeX Live版への採用は見送るのが今の時点では適当と思います。
個人的には #45 の問題を解決する手段の一つとして dvispc が TeX Live で利用できるようになるところまで達成されれば満足です。

もし propw の利用法が提案できて文字コード周りの見通しがよくなれば、TeX Liveへの導入を進めればよいと思います。

**Comment by aminophen** [comment]
propw は見送る方向で ok です。dvispc と chkdvifont の導入を進めたいのですが，

- 提案はどのメーリスに投稿すれば良いのでしょう？ tex-live ？
- allow5c のソースコードを角藤先生から仮に頂けたら，それを調べて dvispc に同等の機能を持たせるのはどうでしょう？（extractbb が xdvipdfmx の別名になっているように，シンボリックリンクで allow5c → dvispc とするのを想定）
- これは私の怠慢ですが，command_line_encoding への理解が追いつかぬままです。あの後 W32TeX では pdvipdfmx 等がなくなって mydvipdfmx 等の名前に変わったのですね。

**Comment by t-tk** [comment]
> * 提案はどのメーリスに投稿すれば良いのでしょう？ tex-live ？

私の考えでは、「Karlさんに入れたい旨を断ってからTeX Live MLに入れます宣言をして TeX Live svnにコミット」のような流れでいいような気がしています。あるいは、「Karlさんに入れたい旨を断ってから TeX Live svn にコミットし、TeX Live MLに入れましたと宣言する」でも良いです。
入れることによる負の面としては、容量を圧迫すること位でしょうか。「TeX Liveが大きすぎる、DVDに収まらない」などの問題提起は時々見ます。しかし、dviout-utilの大きさは僅かでしょうし、日に日に膨らんでいるCTANよりははるかに小さくて気にならないと思います。
なので、手順を踏んで有用性を訴えれば反対意見は出ないように思います。
もっと別の問題、例えば「プラットフォームによってはコンパイルが困難・テストが通らない」とか「セキュリティホールが開いてしまう」とかはおそらく発生しないと予想しています。

> * allow5c のソースコードを角藤先生から仮に頂けたら，それを調べて dvispc に同等の機能を持たせるのはどうでしょう？

私の理解では allow5c が内部で dvispc を呼び出していると思います。
dvispc に allow5c のやっている機能を持たせることはもちろん出来ると思います。
Unix系では通常 #45 のところで述べたように pLaTeX で作った dvi はスペシャルによって書き込まれる画像ファイル名が EUC になるので、それを UTF-8 に変換して dvi に書き戻すことが出来ればよいです。
Windowsでは、私の想像ですが、allow5c は \x5c を含む SJISのファイル名を \x5c を付加して dviwareからは適切にエスケープされて見えるようなファイル名に書き換えているものと思います。
その代わりに、SJIS のファイル名を UTF-8 に書き換え、mydvips.exe,   mydvipdfmx.exe により処理する方法もあると思います。その場合は Unix系と共通の方法で実現できそうです。

> * あの後 W32TeX では pdvipdfmx 等がなくなって mydvipdfmx 等の名前に変わったのですね。

これは、配布にdefaultでついてくる texmf.cnf に `command_line_encoding=utf-8` と書く方針(該当プログラムでのdefaultがUnicode)から書かない方針(defaultがレガシーエンコーディング)に変わったことに伴うものです。
現在では、ユーザー側が my* を使うなり `command_line_encoding=utf-8` を設定すれば UTF-8 仕様の動作が選択できます。

**Comment by t-tk** [comment]
dviout-utilブランチでpropw を外しました。
そろそろ Karl さんにお伺いを立ててもよいかと思います。
TeX Live導入活動とallow5c類似機能の開発は並行して進めてもよいと思います。
どうしましょうか。

**Comment by aminophen** [comment]
ありがとうございます。では私から Karl さんにメール（Cc で [texjp issue メーリス](
https://ml.texjp.org/mailman/listinfo/issue)）してみましょうか。

**Comment by t-tk** [comment]
お願いします。

**Comment by aminophen** [comment]
いま気づいたのですが，「[dvispcとvf](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/43177.html)」という TeX QA の古いトピックで，大島先生が

> dvipscを作ったときの方針（すなわち，tfm, pk, vf などがなくてもよい，TeX の環境 -- フォントを探す順序とか、texmf.cnf -- と独立）

という[発言](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/43188.html)をされています。

TeX Live 版では ptexenc を使うために kpathsea の config も読んでいるようです。厳密に考えると「方針」とすれ違うように思いますが，例のご発言は 「dvicopy のように VF も展開したいという要望は気が進まない」という感想にも受け取れますし，

- UTF-8 対応の手間を考えると ptexenc を流用するのが簡単
- （私の GitHub のように）standalone 版としても簡単にコンパイルできる

という事情を加味すると，許してもらえるんじゃないかと。一応コメントでした。

**Comment by aminophen** [comment]
For the record 
https://ml.texjp.org/pipermail/issue/2018-September/000189.html

**Comment by t-tk** [comment]
> dvipscを作ったときの方針（すなわち，tfm, pk, vf などがなくてもよい，TeX の環境 -- フォントを探す順序とか、texmf.cnf -- と独立）

問題になることは無いと思う理由を一応コメントします。

* 今dviout-utilブランチにあるコードにおけるptexencの使い方は、「JIS→その他のエンコーディングの文字コード変換」とその表示の部分にしか使っていないので、texmf.cnf の中身を見ていない。
* TeX Live版では、一般のユーザーはコンパイルされたバイナリー配布を使うことになるのでTeX Liveの環境(kpathsearchやptexencを利用することなど)を前提として困ることはない。
* 今のところ、 PTEXENC を無効にしVERSION, TL_VERSIONを定義すればTeX Live以外でもコンパイル可能。

今後、「TeX Live版のソースをTeX Live以外の環境に持っていってコンパイルして使用する」ような利用法にどこまで配慮するか、が論点になると思います。あまり深く考えていませんが、追加したい機能によって判断すればよいと思います。
dvispc が書かれた2003年頃といろいろな点で状況が異なってきています。今は GitHubの履歴をたどれば過去の好きな時点のソースを拾えますし、内容によっては原作者の大島先生と異なる判断が生じても許容されると思います。

**Comment by aminophen** [comment]
> Karlさんのコメントにあった件、TeX Live svnのdviout repositoryとの関係

大筋は合意です。

dviout-util は元々私個人持ちのつもりで作っていたので，README もそれ用に書いただけでした。TeX Live に収録する方向性がほぼ決まったので，管理元を texjporg/tex-jp-build に移管するという前提で，README と COPYING は書き換えておきます。

あと，Win32 だと dviout が丸ごとTeX Live に収録されていて，そこに dvispc.exe も置かれているのでこのままだと重複します。2019 pretest に移行する際に dviout 配下の方を消すことになるでしょうか？（記憶が正しければ，dviout はファイルオープンするときに dvispc を最初に実行するはずなので，その機能を壊さないかどうかは確認が必要ですが）

**Comment by t-tk** [comment]
COPYING は先ほど私が触りましたが、適宜推敲して頂いて構いません。

dvispc.exeの重複の件、
Windowsで、またはW32TeXでどうするべきか、角藤先生と相談ですね。
TeX Live版は別の名前にするか、重複を厭わずに両方同じ名前で入れるか、どちらかを消すか、いくつか選択肢が考えられると思います。

**Comment by aminophen** [comment]
COPYING の冒頭の情報は README に移せば一本化できるので， 9f6f432 で直しました。また，README は色々のメモも兼ねてかなり詳しくしました。

W32TeX には allow5c.exe のために dvispc.exe が入っていて，さらに chkfont.exe も独自に追加されていたようです。一旦相談してみます。

**Comment by aminophen** [comment]
`dvipsc -b in.dvi` とすると元ファイルが in.dvi.bak として保持されるはずなのですが，なぜか in.dvi.bak が存在しない時はエラー終了していたので直しました。（`unlink(tmp_buf) == -1` は `tmp_buf` が存在しない時 -1 になるので弾かれてしまっていたらしい）

**Comment by t-tk** [comment]
> dviout 側が仮に「dviout.exe 本体と同じ場所に dvispc.exe がなくても，環境変数 PATH 内にそれが見つかれば呼び出せる」という実装になっているかを確認

ソースを追ってみました。

* 現状は、dviout.exe 本体と同じ場所`^x`のみをdvispc.exeの場所として明示的に指定している
* dvispc.exe は結局 misc.c の WinMinExecute() 関数の中で Win32APIの[CreatePath](https://msdn.microsoft.com/ja-jp/library/cc429066.aspx)を使って呼び出されている

CreatePath は、実行すべきモジュール(今回は dvispc.exe)のパスを指定しない場合、Windowsシステムディレクトリや環境変数 PATHなどを順番に探すそうです。
若干の改修をすれば対応可能のようですが、少々面倒そうです。

**Comment by aminophen** [comment]
> ソースを追ってみました。

ありがとうございます。どう改修するのが良いか私には判断がつかないので，「とりあえず消さない」という方向でいきましょうか。

ひとまず windows 以外の環境に dviout-util を入れる準備は整いました。man page もアップロードしたので，この連休中に TeX Live svn にコミットしようと思います。

**Comment by aminophen** [comment]
r48839, r48840 で dviout-util を TeX Live svn にコミットしました。

が，手元で通ったテストが Travis CI で落ちていて，テストファイルの open に失敗しているようですが，なぜ手元と違うのかよくわかっていません。

**Comment by aminophen** [comment]
手元で再現させることができ，ようやくテストが通るように dvispc.c を修正しました。ようやくわかったのが以下の内容でした。

- (1) TeX Live のソースをビルドすると，make check-TESTS で走るバイナリには tracing が効いていて，その出力をログに redirect している。
- (2) dvispc の従前のコードは「output_dvi_file が明示的に指定されていても，リダイレクトされている場合は無視してそちらへ流す」挙動というリダイレクト側に流す」という挙動だった。
- 上記 (1) (2) が組み合わさることで，ビルド方法によって dvispc の出力の向け先が違っていた。

**Comment by aminophen** [comment]
現状 [r48843](https://www.tug.org/svn/texlive?view=revision&revision=48843) (= e0fffee) ですが，

- Travis CI の Linux 3種類
- 手元の OS X 10.11.6 El Capitan

では成功していますが，

- Travis CI の OS X

では失敗しています。理由がよくわかりません…。

**Comment by aminophen** [comment]
導入は完了ということで tex-live ML に流しました。この issue は閉じておきます。

https://tug.org/pipermail/tex-live/2018-October/042507.html

まだ少々気になる挙動が残っているので，  https://github.com/aminophen/dviout-util に立ててある issue は時間を見て引き続き検討していきます。
