### ISSUE TITLE
TeX Live 2019 に向けて

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#69]
年度末はあまり時間が取れなそうなので，今のうちに考え始めます。

# pTeX 系列

以下はマージして TeX Live 2019 に変更を反映させたいです。

- 和文のコントロールシンボル (control_symbol ブランチ #37)
    - 直後の改行文字を空白として扱わずに無視
- \inhibitglue の効力 (inhibit_flag_list ブランチ #28)
    - ノードを作らないもの（\relax とか代入とか）は透過させる
    - リスト境界をまたがない
    - \inhibitglue を無効化する \disinhibitglue プリミティブの新設

また，

- \epTeXinputencoding の警告の表示エンコーディング (#34)

もあまり厄介な話ではないので，そろそろ結論を出したいです。

**Comment by aminophen** [comment]
ついでにこれも。

- [(u)pTeX] 内部コードの -kanji-internal オプション (#55)

**Comment by h-kitagawa** [comment]
さらについでに，abenori さんの [Twitter](https://twitter.com/abenori/status/1090581338808147970) に関連した修正 （pdfsavepos ブランチ）も．

**Comment by aminophen** [comment]
> - \epTeXinputencoding の警告の表示エンコーディング (#34)

これも for-tl2019 ブランチに取り込みました。

**Comment by aminophen** [comment]
もし間に合うのであれば

- [ptex] エラー出力の余分なバイト (#59) → trick_buf2 ブランチでしょうか？

も直せればいいなと思います。私には現象がまだ掴めていないのですが，今後この「余分なバイト」が expl3 (LaTeX3) の自動テストとかを fail させる潜在的な懸念があるので…。

**Comment by aminophen** [comment]
> * [(u)pTeX] 内部コードの -kanji-internal オプション (#55)
> * abenori さんの Twitter に関連した修正 （pdfsavepos ブランチ）
> * 和文のコントロールシンボル (control_symbol ブランチ #37)
> * \inhibitglue の効力 (inhibit_flag_list ブランチ #28)
> * \epTeXinputencoding の警告の表示エンコーディング (#34)

以上 5 件，先ほど r49955 -- r49959 で TeX Live svn にコミットしました。
