### ISSUE TITLE
[makejvf] 第1引数と第2引数が同じ basename の場合

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#71]
https://twitter.com/aminophen/status/1088041686821830656 の私のツイートから：

> makejvf はその存在意義から判る通り
> 
> $ makejvf jis jis
> 
> のように第1・第2引数を同じ basename にすることは無益である（第1引数が指す入力ファイルが，仮にカレントディレクトリに有ると，それが上書きされて壊れる）。そこで，「この呼び出し方ならばエラー終了」とするのはどうだろう？

直近で見つけたのは [forum:736](https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=736#p3990) や [漢字フォントの導入(多書体 TeX)](http://www.comb.kokushikan.ac.jp/MT02/archives/2004/11/_tex.html) ですが，他にも何度も makejvf の引数を同じにして“壊した”例をみかけたので，このさい禁止してもよいのではと考えています。

**Comment by t-tk** [comment]
入力ファイルを壊してしまうような引数の組み合わせは「無益」というより「有害」という方が当たっているかもしれません。
「禁止してよい」に賛成です。

**Comment by aminophen** [comment]
makejvf-args ブランチで実装してみました。

- 「入力ファイルを出力ファイルが同一のため上書きしてしまう」または「入力ファイルと出力ファイルが（たまたまディレクトリは違ったが）basename が同じ名前になってしまう」という場合をすべて禁止。例えば，以下のような呼び出し方がすべて禁止される。
    - `makejvf hoge hoge`
    - `makejvf hoge.tfm hoge`
    - `makejvf $(kpsewhich hoge.tfm) hoge` ← 入力ファイル名はフルパスの可能性もあるため
    - `makejvf -K hoge hoge fuga`
    - `makejvf -u jis -J hoge hoge fuga`
    - `makejvf -u jis -U hoge hoge fuga`
- ついでに「-u」なしの場合に -J / -U / -3 / -H は無意味であることから警告を出しました。さらに「-u」ありでも -J と -U を同時に使うことも想定外なはずですから，これはエラーにしました。

**Comment by t-tk** [comment]
ありがとうございます。
後ほど私も uptex-fonts で一応テストしようかと思っています。今回の変更で影響は受けないはずです。

**Comment by t-tk** [comment]
uptex-fonts で今回の変更の影響を受けていないことを確認しました。
変更内容に賛成です。

**Comment by aminophen** [comment]
ご確認ありがとうございます。r50106 でコミットしました。
