### ISSUE TITLE
[upmendex] multibytelen

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#76]
https://github.com/texjporg/tex-jp-build/blob/9c7ae9df354ab27c7b1fd44c79aa6afac2f7098c/source/texk/upmendex/mendex.h#L93

ここの最初の `(a)<0xc2 ? 1` は正しくは `(a)<0x80 ? 1` ではないでしょうか。少なくとも [ptexenc/unicode.c](https://github.com/texjporg/tex-jp-build/blob/master/source/texk/ptexenc/unicode.c#L33) はそうなっています。

**Comment by t-tk** [comment]
ご指摘ありがとうございます。おっしゃる通りです。
今、upmendex のマニュアルを編集中でして、それと一緒にコミットしようと思います。

**Comment by aminophen** [comment]
Karl さんが「Luigi の MetaPost のバグ修正をコミットしたらリビルド要請する」と仰っていたので，そう遠くないと思い先回りして r50255 でコミットしました。

**Comment by t-tk** [comment]
お手数をおかけしました。
ここは閉じます。
