### ISSUE TITLE
\readline で和文文字

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#88]
e-TeX 拡張プリミティブである \readline を使って，和文文字を読み込もうとすると，全て「\catcode 12 の欧文バイト列」に変換されてしまうのですね…。

素の TeX の \read と並べて示します↓

``` tex
\newwrite\OUT
\immediate\openout\OUT=\jobname-out.tex
\immediate\write\OUT{English日本語Alphabet漢字}
\immediate\closeout\OUT

\font\x=ec-lmr10\x

\newread\IN
\openin\IN=\jobname-out.tex
\read\IN to\DATA [read: \DATA]
\closein\IN
\openin\IN=\jobname-out.tex
\readline\IN to\DATA [readline: \DATA]
\closein\IN

\bye
```

<img width="493" alt="eptex-read-readline" src="https://user-images.githubusercontent.com/9957466/64481521-dddf7200-d217-11e9-8937-114b81ec8780.png">

**Comment by h-kitagawa** [comment]
```\readline``` が初耳だったのでもしやと思いましたが，やはり単純に日本語対応処理を追加するのを忘れていただけでした……．今日中にやります．

**Comment by h-kitagawa** [comment]
https://github.com/h-kitagawa/tex-jp-build/commit/493d301ac97f57485aaed3b6b247750cd399e5a8 で日本語対応処理を追加．

**Comment by aminophen** [comment]
早速ありがとうございます。発見したのは [kanji-config-updmap のマニュアル](https://github.com/texjporg/jfontmaps/tree/7991ebc3550003dbdbff8171330bf3b6f153dc60) を書いていた最中だったのですが，これも正常に組めるようになりました。

夕方にでも TeX Live svn にコミットしようと思います。

**Comment by aminophen** [comment]
Done (r52053).
