### ISSUE TITLE
[ptex] \show\synctex=[unknown integer parameter!]

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#91]
ptex -ini で掲題のとおりになります。eptex -ini は OK です。

https://twitter.com/zr_tex8r/status/1181946423698284545

**Comment by zr-tex8r** [comment]
ちなみに：

* `ptex -help`のヘルプ画面には`-synctex`がある。
* ptexコマンド（plain pTeX）で`-synctex=1`のオプション指定や`\synctex=1`の実行をすると、ちゃんとSyncTeXが働く。

**Comment by h-kitagawa** [comment]
次の行が e-TeX 拡張ありの場合にのみ適用される synctex-e-rec.ch0 にしかないからですね：
```
synctex_code:    print_esc("synctex");
```
今日中に対処しようと思います．

TeX Live の中では，SyncTeX 拡張がないエンジンは次の 2 つです
 * TeX82（標準では無効化．```--enable-tex-synctex``` をつけると搭載されると思われるが，おそらく今回と同じ症状が発生）
 * Aleph（SyncTeX 対応がそもそもされていない）
