### ISSUE TITLE
[ptex] reading \kansujichar

### ISSUE THREAD

**Issue by aminophen** [texjporg/tex-jp-build#93]
\kansujichar は代入できるのに取得はできない，という挙動が気になっています。「いったん \kansuji で文字を出してそのコードを取得」ならできるのですが，なんだか不便です。

``` tex
\kansujichar1=46042
\showthe\kansujichar1
% => ! You can't use `\kansujichar' after \the.

\count200=\kansujichar1
% => ! You can't use `\kansujichar' after \the.

\count201=\expandafter`\kansuji1
\showthe\count201 % => 46042.

\end
```

https://github.com/texjporg/ptex-manual/issues/6 の英語版ドキュメントには，各プリミティブの具体的機能は書かずに，そのシンタックス (expandable, read-only integer, etc.) を書こうと思っているのですが，\kansujichar は assignment-only で本当にいいんだろうかというのが気になりました。

**Comment by zr-tex8r** [comment]
自分の考えとしては

* 数値パラメタなのに読みだせないのは直観に反する
* なので、実装が難しくないなら、読み出せるように改修したほうがよい
* ただしマニュアルで「読出は新しい機能である」旨の注意をしておくべき。

ですね。

**Comment by h-kitagawa** [comment]
> いったん \kansuji で文字を出してそのコードを取得

単純にこういう使い方を想定していただけなのかなあ，という気がします．\kansujichar だけ取得不能としておく理由はないと思います．

**Comment by aminophen** [comment]
コメントありがとうございます。実装自体はなんとかなりそう？ → f38d636

**Comment by h-kitagawa** [comment]
> コメントありがとうございます。実装自体はなんとかなりそう？ → [f38d636](https://github.com/texjporg/tex-jp-build/commit/f38d6360ba9563f61f965706827b9086b9b8c293)

これで動いているようです，ありがとうございます．

**Comment by aminophen** [comment]
`\count123=\kansujichar45` とした場合に `! Invalid KANSUJI number (45).` となりますが，その後のリカバーはどうしましょうか？ 今は `\count123=45` と同義になる実装ですが，この場合 `cur_val` は捨てるべきな気もします。

**Comment by h-kitagawa** [comment]
不正な引数が来たときに `"I'm skipping this control sequences."` というメッセージを出して単に無視するのは `\kansujichar` 特有のような気がしています．全部調べたわけではありませんが，他の命令では `"I changed this one to zero."` と引数を 0 に読み替えるのが一般的？

**Comment by aminophen** [comment]
たしかに "I changed this one to zero." と読み替える（＝ `\kansujichar0` を返す）というリカバーは他の TeX82 命令を見ると一般的で良さげですが，一方いままでの pTeX は代入時の不正な引数を "I'm skipping this control sequences." で読み飛ばしていた（＝ `\kansujichar0` への代入は起こらない）ので，それとの整合性が取れないように感じています。

**Comment by aminophen** [comment]
今の自分の感覚としては，「値＝不正な引数」あるいは「値＝\kansujichar0」よりは，「値＝0」あるいは「値＝-1」にしたい気分です。他のプリミティブでそのような値をリカバーする例はないか探し中…。

**Comment by h-kitagawa** [comment]
> いままでの pTeX は代入時の不正な引数を "I'm skipping this control sequences." で読み飛ばしていた

なるほど，確かに，取得時に `\kansujichar0` を返すようにするのはかえって不統一ですね．あまり意見はないのですが，`\kansujichar45=...` という不正な引数で代入操作を読み飛ばすのなら，今の 「`\count123=\kansujichar45` は `\count123=45` と同義」というのも `\kansujichar` という変換操作を読み飛ばすという意味ではそんなに不自然ではないのかも．

**Comment by aminophen** [comment]
> \kansujichar という変換操作を読み飛ばすという意味ではそんなに不自然ではないのかも

私もそんなに不自然ではない気がしてきたので，このまま行こうと思います。エラーリカバリを利用して何かする訳でもないですし，! Missing number を避けるにはこれで十分なので。

\kansujichar の取得は新機能とも言えるので，問題なければ \synctex の件と合わせて pTeX のリビジョンを1だけ増やして夜にコミットしようと思います。

**Comment by aminophen** [comment]
pTeX p3.8.2 → p3.8.3 に上げて r52389 でコミットしました。

**Comment by aminophen** [comment]
> ただしマニュアルで「読出は新しい機能である」旨の注意をしておくべき。

texjporg/ptex-manual@9953f67 で注意書きを追加しました。
