### ISSUE TITLE
和文vf の fallback を dviware で

### ISSUE THREAD

**Issue by t-tk** [texjporg/tex-jp-build#99]
(English summary follows Japanese.)
uptex-font の方で以前[話題にした](https://github.com/texjporg/uptex-fonts/issues/3)ことのある件を調べ始めました。今後主に dviware の改良の話に向かいたいのでこちらの tex-jp-build に Issueを立てます。

まずは、一部繰り返しになりますが、振り返りながらまとめます。
動機は次の通りです。
japanese-otf(-uptex)などで和文vfを利用する際、漢字など大量のエントリーが『文字コードを維持したまま最初のJFM のchar_type 0番にフォント名、メトリックスを割り当てる』だけのものになっている。そこが単純な割に容量を食っていて、書体数や文字数を増やそうとするとバカにならないくらい巨大になる。そこで、「和文vf の中でエントリーが見つからない場合は『文字コードを維持したまま、最初のJFM のフォント名を、かつJFMのchar_type 0番にメトリックスを割り当てる』のような動作を仕様化して dviware 側で対処しよう」、という提案です。

[uptex-fontの方](https://github.com/texjporg/uptex-fonts/issues/3) で長い議論がありましたが、一部以下に再掲します。

「MAPFONTで指示されているfont IDの一番若いものがJFMであるとき、要求されたコードポイントが明言されていな場合は，それが最小の font ID に属し，かつそのコードポイントそのものを出力する」
というルールの追加でよいように思います。つまり、VFの仕様拡張としては、idを追加して新しい命令を用意して…という方向でなく、解釈を拡張するというイメージです。

例えば、現状、upphiraminw3-h.ovp は、冒頭が
```
(MAPFONT D 1
   (FONTNAME uphminr-h)
   (FONTCHECKSUM O 0)
   (FONTAT R 1.000000)
   (FONTDSIZE R 10.000000)
   )
```
で、おしまいの方に次のようなエントリーが延々と続きます。
```
(CHARACTER H 2F9F4
   (CHARWD R 1.000000)
   (MAP
      (SETCHAR H 2F9F4)
      )
   )
```

その代わり、CHARACTERのエントリーがない文字コード 0xXXXXX の要求が来た場合、従来エラーでしたがその代わりに
```
(CHARACTER H XXXXX
   (CHARWD R 1.000000)
   (MAP
      (SETCHAR H XXXXX)
      )
   )
```
であると解釈する、という新ルールです。

otf パッケージでは、現在 {,u}mkjvf によりovp を生成しています。該当部分を削除すれば済むだけですので、改造は容易でしょう。
~~逆に出力不能な文字がソースに来た場合、従来は{,u}platexのコンパイル時にエラーが出ましたが、新ルールの元ではdviwareの処理までエラーが出ないことになります。~~
逆に出力不能な文字がソースに来た場合、従来はdviwareがvfのエントリー不足を発見した時にエラーが出ましたが、新ルールの元ではdviwareが実フォントにアクセスを試みるまでエラーが出ないことになります。

---
(English summary)
I propose a new rule:
If a virtual font has no entry of a codepoint and the first MAPFONT designates (u)pTeX JFM,
we designate the glyph of the same codepoint in the TFM(JFM) with the smallest font ID.
The new rule helps to shrink size of Japanese virtual fonts.

For example, conventionally `upphiraminw3-h.ovp` starts with
```
(MAPFONT D 1
   (FONTNAME uphminr-h)
   (FONTCHECKSUM O 0)
   (FONTAT R 1.000000)
   (FONTDSIZE R 10.000000)
   )
```
and a huge volume of entries for fullwidth characters continue such as:
```
(CHARACTER H 2F9F4
   (CHARWD R 1.000000)
   (MAP
      (SETCHAR H 2F9F4)
      )
   )
```

Conventionally, if the virtuanfont lacks an entry of a CHARACTER 0xXXXXX, dviware rejected.
My proposal is to introduce the new rule to interpret as the fullwidth CHARACTER 0xXXXXX of `uphminr-h`:
```
(CHARACTER H XXXXX
   (CHARWD R 1.000000)
   (MAP
      (SETCHAR H XXXXX)
      )
   )
```

---
(Extended feature, 2023-04-29)

The rule for virtual fonts (VF) fallback is extended:
If a VF has no entry of a codepoint and the first
MAPFONT designates an OFM for (u)pTeX, then we designate the
glyph (usually with a fullwidth metric) of the same codepoint
with the same metrics of the codepoint in the OFM.

**Comment by t-tk** [comment]
前回話題になっていたソフトのリストです。

和文vfを取り扱うdviware:

* [ ] **dvipdfmx**
* [ ] **dvips**
* [ ] **dvisvgm**
* [ ] dvicopy
* [ ] dviout
* [ ] pxdvi

和文vfを生成するソフトウェア:

* [ ] makejvf
* [ ] ovp2ovf / wovp2ovf
* [ ] japanese-otf(-uptex) (OVPのエントリーを削る)

**Comment by t-tk** [comment]
ブランチ https://github.com/texjporg/tex-jp-build/tree/vf_fallback で試しています。
dvipdfmx は https://github.com/texjporg/tex-jp-build/commit/3dc3d48998a9cb59fa3281027efaf8ccab6186ad のようにしようかと考えています。
(u)pTeX の vf であることをチェックするのに「定義されている文字コードの最大値が 0x100 以上である」ということで行っています。欧文 TeX の vf では当然使っていないはずなので弾くことが出来ますが、Omega の不正な vf ではfallbackの部分にたどり着いてしまう可能性があります。しかし、本来 Omega の正常な vf ではこのfallbackには来ないはずで omega + dvipdfmx の利用者に迷惑がかかることも無いかと思います。
きちんとするには JFM をたどって (u)pTeX の JFM かどうかをチェックする方がよさそうですがよく分かりませんでした。
dvipdfmx は vf の文字幅を操作することは無く並べるだけのようです。なので今回のコードでも JFM のメトリックスを見に行くこともしていません。

**Comment by t-tk** [comment]
参照先の tfm が jfm であることを判定する方法が分かったのでそちらで判定するようにしました。 https://github.com/texjporg/tex-jp-build/commit/1b3e72ebd55a08398678c7b4e229deaa0c661df8
本日が TeX Live 2020 の code freeze 予定日です。
手元で上手く動いていてコードも簡潔で副作用も考えにくいので、急ではありますがTeX Live svnにコミットしてしまおうと思います。

**Comment by t-tk** [comment]
makejvf は https://github.com/texjporg/tex-jp-build/commit/6470129cb56519ad86fc0e0442d7304b6c445b6d のようにしようかと考えています。
-O オプションを追加。これが設定されているときは、約物以外(全角幅のdefaultのグリフをもつ文字)はVFに記載しない。-t によるカスタム設定との同時使用は禁止。-t によるカスタム設定の方が自由度が高いため。

これは TeX Live 2020 には入れず、来年を目指します。
何かご意見や問題などがあればお知らせください。

**Comment by t-tk** [comment]
私の認識では

- ``wovp2ovf`` (``ovp2ovf``のweb版,`` ovp2ovf`` ver 1.xx )
- ``ovp2ovf`` (``ovp2ovf``のC版, ``omfonts -ovp2ovf``に同じ, ``ovp2ovf`` ver 2.xx )

ともに、入力の ``*.ovp`` の時点で生成を省略したいエントリーを前もって削除しておけば所望のvfが作成できると思っています。今回の件ではソースの変更はしないつもりです。

dvicopy は従来の pTeX の vf も現時点では扱えないようなので、今回の拡張も対処無しにしたいと思います。もし将来 pTeX の vf も対処することがあるならば今回の拡張も含めることを期待することにします。

**Comment by aminophen** [comment]
> makejvf は 6470129 のようにしようかと考えています。

試していますが，非漢字部を別の TFM に割り当てる -K オプションで全角幅の文字が仮名にならないので対策しようと思います。少し時間をください。

``` tex
% cp -p jis.tfm myjis.tfm
% makejvf -K myjis-kana myjis myjis-kanji
% cp -p jis.tfm myjiso.tfm
% makejvf -O -K myjiso-kana myjiso myjiso-kanji

\documentclass[a4paper]{jsarticle}

% for myjis
\DeclareKanjiFamily{JY1}{myjis}{}
\DeclareFontShape{JY1}{myjis}{m}{n}{<-> s * [0.961] myjis}{}
\DeclareFontShape{JY1}{myjis}{m}{it}{ssub * myjis/m/n}{}
\DeclareFontShape{JY1}{myjis}{m}{sc}{ssub * myjis/m/n}{}
\DeclareFontShape{JY1}{myjis}{m}{sl}{ssub * myjis/m/n}{}
\newcommand{\myjisdefault}{myjis}
\DeclareRobustCommand\myjisfamily{\kanjifamily\myjisdefault\selectfont}
\DeclareTextFontCommand{\textmyjis}{\myjisfamily}

% for myjiso
\DeclareKanjiFamily{JY1}{myjiso}{}
\DeclareFontShape{JY1}{myjiso}{m}{n}{<-> s * [0.961] myjiso}{}
\DeclareFontShape{JY1}{myjiso}{m}{it}{ssub * myjiso/m/n}{}
\DeclareFontShape{JY1}{myjiso}{m}{sc}{ssub * myjiso/m/n}{}
\DeclareFontShape{JY1}{myjiso}{m}{sl}{ssub * myjiso/m/n}{}
\newcommand{\myjisodefault}{myjiso}
\DeclareRobustCommand\myjisofamily{\kanjifamily\myjisodefault\selectfont}
\DeclareTextFontCommand{\textmyjiso}{\myjisofamily}

% map file
\AtBeginDvi{\special{pdf:mapline rml H ipaexm.ttf}}
\AtBeginDvi{\special{pdf:mapline gbm H ipaexg.ttf}}
\AtBeginDvi{\special{pdf:mapline myjis-kana H ipaexm.ttf}}
\AtBeginDvi{\special{pdf:mapline myjis-kanji H ipaexg.ttf}}
\AtBeginDvi{\special{pdf:mapline myjiso-kana H ipaexm.ttf}}
\AtBeginDvi{\special{pdf:mapline myjiso-kanji H ipaexg.ttf}}

\pagestyle{empty}
\begin{document}

\myjisfamily
[漢字・あいうえお。漢字も、大丈夫（かなだけ別）だよ]

\myjisofamily
[漢字・あいうえお。漢字も、大丈夫（かなだけ別）だよ]

\mcfamily
[漢字・あいうえお。漢字も、大丈夫（かなも同じ）だよ]

\gtfamily
[漢字・あいうえお。漢字も、大丈夫（かなも同じ）だよ]

\end{document}
```

**Comment by aminophen** [comment]
> 非漢字部を別の TFM に割り当てる -K オプションで全角幅の文字

391c95c でどうでしょう？

**Comment by t-tk** [comment]
ご検討有難うございます。
-K オプションとは知りませんでした。
kanatfm の対象が「非漢字部」ということですがその集合がよく分かりません。
JIS X 0208の6区(0x2621..0x2658, ギリシャ文字), 7区(0x2721..0x2771, キリル文字) はどちらに含まれるのでしょうか? もしこれらがkanatfmの対象になるのならば、エントリーを省略しない方に回すことになりそうです。

**Comment by aminophen** [comment]
> kanatfm の対象

``` c
if (!kanatfm || code > 0x2576)
```

の 0x2576 は，その下の方にあった

``` c
	if (kanatfm) {
		if (code <= 0x2576)
```

に依拠しています（妥当かどうかはさておき）。個人的には，

* 6区ギリシャ文字
* 7区ロシア文字
* 8区罫線素片

が漢字側なのは違和感がありますが，アスキー版の挙動が今に至るまで維持されているため今回もそれに従いました。

UCS mode については #16 のときの議論のとおりです。

**Comment by t-tk** [comment]
kanatfm の文字集合は了解しました。https://github.com/texjporg/tex-jp-build/commit/391c95c0da110c34160d5634ef2a7de99ba28959 に合意します。

**Comment by t-tk** [comment]
japanese-otf-uptex は、私の所[「和文vf の fallback を使った vf の軽量化」](https://github.com/t-tk/japanese-otf-uptex/issues/3)で検討します。

**Comment by t-tk** [comment]
[IPAmj明朝フォント](https://mojikiban.ipa.go.jp/1300.html)の変体仮名で遊んでみました。
uplatex + dvipdfmx ver.20200315 で予定通り変体仮名が埋め込まれました。
しかしupTeX(とdviware)が合成用の濁点・半濁点に対応していないので、IPAmj明朝フォントが[濁点・半濁点付きグリフ](https://mojikiban.ipa.go.jp/contents/2019/05/f0216ed4b3bf8599632bf32259275e18.html)を持っているのにもかかわらず利用できていません。
#46 の開発項目が実現できれば同時に出来るはずで、いつかは実現したいところです。

``` tex
\documentclass{ujarticle}
\AtBeginDvi{\special{pdf:mapline uprml-h unicode ipamjm.ttf}}

\begin{document}

\section{変体仮名}

𛀂𛀃𛀄𛀅𛀆𛀇𛀈𛀉𛀊𛀋𛀌𛀍𛀎𛀏
𛀐𛀑𛀒𛀓𛀔𛀕𛀖𛀗𛀘𛀙𛀚𛀛𛀜𛀝𛀞𛀟
𛀠𛀡𛀢𛀣𛀤𛀥𛀦𛀧𛀨𛀩𛀪𛀫𛀬𛀭𛀮𛀯
𛀰𛀱𛀲𛀳𛀴𛀵𛀶𛀷𛀸𛀹𛀺𛀻𛀼𛀽𛀾𛀿
𛁀𛁁𛁂𛁃𛁄𛁅𛁆𛁇𛁈𛁉𛁊𛁋𛁌𛁍𛁎𛁏
𛁐𛁑𛁒𛁓𛁔𛁕𛁖𛁗𛁘𛁙𛁚𛁛𛁜𛁝𛁞𛁟
𛁠𛁡𛁢𛁣𛁤𛁥𛁦𛁧𛁨𛁩𛁪𛁫𛁬𛁭𛁮𛁯
𛁰𛁱𛁲𛁳𛁴𛁵𛁶𛁷𛁸𛁹𛁺𛁻𛁼𛁽𛁾𛁿
𛂀𛂁𛂂𛂃𛂄𛂅𛂆𛂇𛂈𛂉𛂊𛂋𛂌𛂍𛂎𛂏
𛂐𛂑𛂒𛂓𛂔𛂕𛂖𛂗𛂘𛂙𛂚𛂛𛂜𛂝𛂞𛂟
𛂠𛂡𛂢𛂣𛂤𛂥𛂦𛂧𛂨𛂩𛂪𛂫𛂬𛂭𛂮𛂯
𛂰𛂱𛂲𛂳𛂴𛂵𛂶𛂷𛂸𛂹𛂺𛂻𛂼𛂽𛂾𛂿
𛃀𛃁𛃂𛃃𛃄𛃅𛃆𛃇𛃈𛃉𛃊𛃋𛃌𛃍𛃎𛃏
𛃐𛃑𛃒𛃓𛃔𛃕𛃖𛃗𛃘𛃙𛃚𛃛𛃜𛃝𛃞𛃟
𛃠𛃡𛃢𛃣𛃤𛃥𛃦𛃧𛃨𛃩𛃪𛃫𛃬𛃭𛃮𛃯
𛃰𛃱𛃲𛃳𛃴𛃵𛃶𛃷𛃸𛃹𛃺𛃻𛃼𛃽𛃾𛃿
𛄀𛄁𛄂𛄃𛄄𛄅𛄆𛄇𛄈𛄉𛄊𛄋𛄌𛄍𛄎𛄏
𛄐𛄑𛄒𛄓𛄔𛄕𛄖𛄗𛄘𛄙𛄚𛄛𛄜𛄝𛄞


「生𛁛𛂦゙」「生そば」

「天𛂱゚𛃭」「天ぷら」

「𛁈る𛀸」「しるこ」

\end{document}

```

**Comment by t-tk** [comment]
makejvf v20200412, `-O`オプション追加, TeX Live [r54693](https://www.tug.org/svn/texlive?view=revision&revision=54693) 完了。

**Comment by t-tk** [comment]
dvips の対応は少々苦労しましたが  https://github.com/texjporg/tex-jp-build/commit/eca7562e1486cea4349583fef22435001c43fb5c で出来ているように思います。
https://github.com/t-tk/japanese-otf-uptex/issues/3 で作った `upexpminr-h.vf` などを使ってテストしていますが、手元では vf の軽量化以前と同様の結果を得ることが出来ています。
debug 用のメッセージがオプション `-d 4` (D_FONT)で出ます。
vf がpTeX用かどうかの判定をしていてpTeX以外の欧文TeX, Omegaへの動作の影響は無いはずです。また、エントリー省略のない従来のpTeX用vfの動作への影響も無いはずです。

pprescan.c の `pscanpage()` のルーチンに処理が回るケースを見つけることが出来ておらずそのテストが出来ていません。どういうケースがあるのかご教示いただけると助かります。scanpage.c とほぼ同じことをしているのでおそらく大丈夫であろうと思ってはいますが。

**Comment by t-tk** [comment]
dvips は私のテストでは上手く動いているようで副作用も無いはずなので TeX Live svn にコミット ([r54794](https://www.tug.org/svn/texlive?view=revision&revision=54794)) しました。
まずい所があったらご指摘お願いします。

**Comment by h20y6m** [comment]
dvipdfmx Version 20200315 で軽量 VF を試しているのですが、
dvipdfmx に `-v` オプションをつけると、
```
dvipdfmx:warning: Fallback multibyte character in virtual font: name=bjlreq--upnmlminrn-v char=0x00732b(29483)
```
のような警告メッセージが大量に出力されます。
少し抑制等出来ないでしょうか？
（verbose とはいえちょっと多すぎるのではないかと……）

**Comment by t-tk** [comment]
> （verbose とはいえちょっと多すぎるのではないかと……）

具体的に仕様案はありますか?
例えば、dvipdfmx の場合、`-v`, `-vv` と2段階あるそうなので、
`-v` のときはフォントの組み合わせ(VF→TFM)だけを出す、
`-vv` のときは文字コードも含めて全部出す、とか。

`dvips -d 4` もどうしましょうかね。こちらは1段階だと思います。

**Comment by aminophen** [comment]
dvipdfmx は，実は -vvvvv まであります。1個から5個まで，それぞれ煩さが違います。

**Comment by aminophen** [comment]
煩さについては，「軽量VFがどれほどメジャーになるか」も関わる気がします。例えば (u)ptex-fonts や OTF パッケージのJFMを軽量化しなければ，実際に -v で警告が発生するのは U+30000 など従来サポートできなかった文字コードに限られます。個人的には，今のままでもいいのではないかと思っています。

**Comment by h20y6m** [comment]
すみません。具体案があるわけではありません。
意図通りの VF が読み込まれているか確認したくて `-vv` オプションを使用したところ、数千行の警告が出力され他の情報がほとんど見えなくなってしまったので何とかならないかと思い書き込ませていただきました。
aminophen さんのおっしゃるような状況なら今のままでよい気もします。

**Comment by t-tk** [comment]
> 「軽量VFがどれほどメジャーになるか」

私としては少しずつ適用領域を拡大していき将来的には当たり前に使えるようになればいいな、と思っています。
`-v` と `-vv` の差位はあってもよい気がするので警告の情報量の調節を検討してみようかと思います。`-vvvvv`まであるとは知りませんでした。

> 意図通りの VF が読み込まれているか確認したくて `-vv` オプションを使用したところ、数千行の警告が出力され他の情報がほとんど見えなくなってしまったので何とかならないか

うーん。少なくとも今回の件で入れた警告は分かりきった特定のパターンなので適当な方法でフィルタリングすれば容易に選り分けられると思いますし、意図した動作かどうかを確認するなら情報量は多い方が役に立つような気もしますし、入力の量を絞り込むよう調整すれば該当の警告は減る道理ですし、、、デバッグ情報を利用しようとする人に期待するスキルの範囲で何とでも方法は見つかると思いますが…。ただし、前述のように2段階位は考えてみます。

TeX Live svn に最近入れたテスト [r54887](https://www.tug.org/svn/texlive?view=revision&revision=54887), [r54979](https://www.tug.org/svn/texlive?view=revision&revision=54979) では、VFのエントリー省略ありなしで出力が変わらないことを確認するようにしてみました。このテストは最小例しかありませんが、大規模なテストに拡張することも出来ると思います。

いずれにせよ、今回の拡張仕様は将来的には安心して当たり前に使えるものにしたいので、試行とフィードバックをいただけるとありがたいです。

**Comment by t-tk** [comment]
dvipdfmx の警告を`-v`では文字コード出力をやめてVF一個につき一回の出力にしてみました。 `-vv` は今までどおりです。
https://github.com/texjporg/tex-jp-build/commit/611b31834d3242360049122a5db419f278c46b10

dvipsは mapページに

>  -d num Set  the  debug flags.  This is intended only for emergencies or for unusual fact-finding expeditions

とあり、明確にdebug用であることが記載されているので、情報量が多くてもそのままにしたいと思います。

**Comment by t-tk** [comment]
dvisvgm を試してみたところ、現状ではエントリーを省略したvfではエラーで落ちるのではなく該当文字が欠けて出力されるようです。私の手元で少し検討を進めてみて、修正の難易度を見極めてから開発元にどう持っていくかを考えるつもりです。そして、dvisvgm の状況が整ったところで japanese-otf-uptex のvf軽量化リリースの順番のつもりです。

pxdvi はもう2016年か2017年を最後に更新されていないようです。TeX Forumで話題になることもないようですし対応しないことにするつもりです。

dviout は東京大学の「dviout開発室」が消えています。[配布ページ](https://www.ms.u-tokyo.ac.jp/~oshima/dviout/dvihist.html)で"Ver 3.18.5 August    20, 2013"が入手できるのと[ZRさんのところ](https://qiita.com/zr_tex8r/items/8b50836f719dec8b0bee)で「3.18.4 ALPHA 1」版 2013年12月」が紹介されていて、どちらが最新なのか分かりにくいです。TeX Live svn に [dviout のリポジトリ](https://www.tug.org/svn/dviout/)がありますが、メンテナンスやリリースの状況などが分かりにくいです。しかし、pxdviよりは使い続けている根強いユーザー方が現在もいらっしゃるようです。
2018年8月頃の拡張JFMのとき https://github.com/texjporg/tex-jp-build/issues/8#issuecomment-413373785 は対応なしとして、そのままになっています。私自身が今回の件で対応作業をするのは正直荷が重く、二の足を踏んでしまいます。
dviout の対応をまたずに軽量化VF関連のマクロの配布を進めようと思っています。

**Comment by abenori** [comment]
dvioutはTeX Liveに現在でも入っています．入るのは3.18.4 (Feb 22 2012)のようで，上で言われているのよりも古いですね．

**Comment by h20y6m** [comment]
ptex-ng (Asiatic pTeX) は対応するのでしょうか？

**Comment by aminophen** [comment]
ptex-ng は libdpx（dvipdfmx のコードをコピーしたもの）を組み込んであるので，dvipdfmx が対応した時点で半自動的に対応済みです。

**Comment by h20y6m** [comment]
そんな気がしたのですが W32TeX の ptex-ng (compiled time: 2020 May 27 06:28:47 with Win64/MSVC) だと
```
char=0x308c(12428)
Tried to set a nonexistent character in a virtual font
```
のようなメッセージが出力され文字が表示されませんでした。
該当メッセージを出力している部分（vf_ng.c の ng_set_packet）は独自のコードのように見えます。

**Comment by t-tk** [comment]
ソースをざっと見るとこの辺りのようですね。
https://github.com/clerkma/ptex-ng/blob/56c09f22459b381c4a84356724e349815b975d68/src/libdpx/ng/vf_ng.c#L162-L167

ざっと眺めた感じでは、修整がdvipsよりもずっと容易でdvipdfmxよりも少し難しい程度のように見えますが、私としては全く知らないソフトウェアなので手を出しづらいところです…

**Comment by t-tk** [comment]
dviout 3.18.4 について軽量vfの動作確認してみました。
異常終了や警告メッセージなどは無く、vfのエントリーを省略した文字が消えてしまいvfのエントリーが存在する文字は表示されました。異常終了が無かった点は新vfをリリースする際には気が楽です。当然ではありますが、動くようにするためには機能追加が必要です。

今回の件をどうするかはともかく、この際dvioutのメンテナンス状況をもう少し分かりやすくしたいなあと思います。
TUG の [svnレポジトリ](https://www.tug.org/svn/dviout/) や [dviout ML](https://tug.org/pipermail/dviout/) を見ると更新も要望もほとんど無い状態です。
@aminophen さんが2017,2018年頃お書きになったパッチが結局 TeX Live のリリースに取り込まれたのかどうかもよく分かりません。CTAN版は"Ver 3.18.4 February 12, 2012"で、その後東大で公開された"Ver 3.18.5 August    20, 2013"はCTANに反映されていないようです。折角の成果物がユーザーに届いていないように見えます。「3.18.4 ALPHA 1版 2013年12月」がどこにあるのかも未だに分かりません。
現状の延長でいくならば「開発意欲のある人は TUG の svnレポジトリのコミット権をもらって、そこで定期的に整理してリリース」が本筋と思います。それでもいいのですが、一案として、dviout MLで了承をもらってここtexjporgのGitHubで引き取ってメンテナンスするのはどうでしょうか。内容についての議論やパッチの提案などが他の関連ソフトと同様の環境で出来るようになると敷居が下がります。新しい人も入って来やすいようになるように思います。あるいはTUGのsvnはそのままでgit svnで開発機能だけtexjporgのGitHubに持ってくるなどの折衷案もあり得ると思います。dvioutは凍結で構わないという判断もあり得ると思います。
ご意見ください。

**Comment by t-tk** [comment]
「3.18.4 ALPHA 1版 2013年12月」のありかが分かりました。
TeX Live svn で2013年12月に付けられた版数でした。
http://tug.org/svn/dviout?view=revision&revision=183
詳細は未確認ですが、おそらく東大の"Ver 3.18.5 August 20, 2013"と行き違いになっているのではないかと思います。時期も微妙です。
おいおいこの辺りも整理できればと思います。

**Comment by t-tk** [comment]
和文vfのfallbackの新仕様対応策を dviout について(とぎれとぎれで)6月から検討してまいりましたが11月になってしまいました。
未だに見通しが立たないため、私としては未対応のまま保留にすることにしました。
dviout のソースは多少の整理を試みてきました。 r194〜[r203 ](https://www.tug.org/svn/dviout?view=revision&revision=203)あたりまでで一旦まとめることをご提案しようかと思っています。

和文vfのfallback対応の今後の方針ですが、あと dvisvgm, japanese-otf-uptex が残っています。
dvisvgm は作者に連絡するだけにするつもりです。
japanese-otf-uptex は dviware が出揃ってから新版をリリースするつもりだったのですが、これ以上出揃わせるのが難しいのでもうそろそろリリースしようと思います。

**Comment by t-tk** [comment]
fallbackに対応完了したdviwareは結局、2020/11/8現在 dvipdfmx と dvips だけですが、これ以上出揃わせるのが難しいと判断しjapanese-otf-uptexはリリースすることにしました。[v0.26](https://github.com/t-tk/japanese-otf-uptex/releases/tag/v0.26)
CTAN版は遠からず投稿するつもりです。
問題になる場合の回避法は以下で述べました。
https://github.com/t-tk/japanese-otf-uptex/issues/2
https://github.com/t-tk/japanese-otf-uptex/issues/3

**Comment by t-tk** [comment]
japanese-otf-uptexは [2020-11-14](https://github.com/texjporg/japanese-otf-mirror/releases/tag/2020-11-14)を作りCTANに投稿しました。

**Comment by t-tk** [comment]
dvisvgm は開発元にサポート依頼の投稿をしました。
https://github.com/mgieseki/dvisvgm/issues/144

**Comment by t-tk** [comment]
[japanese-otf vfの軽量化](https://github.com/texjporg/japanese-otf-mirror/issues/20) でご報告頂いた件、
https://github.com/texjporg/japanese-otf-mirror/issues/20#issuecomment-734256378
「参照先がjfmかつ、文字のエントリーが無く全ての文字がfallback対象になっているvf」がdvipsで処理出来ませんでした。
https://github.com/texjporg/tex-jp-build/commit/70856308d60d9b17f7cf126e32e5019127220449 で直ったと思います。

**Comment by aminophen** [comment]
> 7085630 で直ったと思います。

ありがとうございます。理解できました。

**Comment by t-tk** [comment]
TeX Live svn [r57024](https://www.tug.org/svn/texlive?view=revision&revision=57024) コミットしました。

**Comment by t-tk** [comment]
dvisvgm は原作者の方が対応してくださり[v2.11としてリリース](https://github.com/mgieseki/dvisvgm/releases/tag/2.11)された模様です。

**Comment by t-tk** [comment]
[japanese-otf の軽量化](https://github.com/texjporg/japanese-otf-mirror/issues/20)は、今回の調査で効果の大きさが確認できましたが、今の時点では不採用として閉じることにします。
全ての検討が終わったのでここも閉じます。

**Comment by t-tk** [comment]
TeXフォーラムの投稿 [dvips が otf の expert に対応していないようです。](https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=3068#p18185) でdvips + 軽量vfでの不具合のご指摘がありました。
dvipsの修正が必要な模様。

**Comment by t-tk** [comment]
dvips + 軽量vf の問題、https://github.com/texjporg/tex-jp-build/commit/0db0c2fb75c368cfaa360eaded9897b84eff90cd で直ったと思います。

**Comment by t-tk** [comment]
TeX Live svn [r58812](https://www.tug.org/svn/texlive?view=revision&revision=58812) コミットしました。

**Comment by t-tk** [comment]
変体仮名のテストの縦組み版です。
uplatex + dvipdfmx ver.20200315以降 + IPAmj明朝フォント
dvipdfmxは -l オプションを付加。

```
% 変体仮名のテスト、縦組み版
\documentclass[landscape]{utarticle}
\AtBeginDvi{\special{pdf:mapline uprml-v unicode ipamjm.ttf -w 1}}

\begin{document}

\section{変体仮名}
![hentai001](https://user-images.githubusercontent.com/3814120/138288617-97d370d9-a9d8-4144-9739-c1c80e310166.png)


𛀂𛀃𛀄𛀅𛀆𛀇𛀈𛀉𛀊𛀋𛀌𛀍𛀎𛀏
𛀐𛀑𛀒𛀓𛀔𛀕𛀖𛀗𛀘𛀙𛀚𛀛𛀜𛀝𛀞𛀟
𛀠𛀡𛀢𛀣𛀤𛀥𛀦𛀧𛀨𛀩𛀪𛀫𛀬𛀭𛀮𛀯
𛀰𛀱𛀲𛀳𛀴𛀵𛀶𛀷𛀸𛀹𛀺𛀻𛀼𛀽𛀾𛀿
𛁀𛁁𛁂𛁃𛁄𛁅𛁆𛁇𛁈𛁉𛁊𛁋𛁌𛁍𛁎𛁏
𛁐𛁑𛁒𛁓𛁔𛁕𛁖𛁗𛁘𛁙𛁚𛁛𛁜𛁝𛁞𛁟
𛁠𛁡𛁢𛁣𛁤𛁥𛁦𛁧𛁨𛁩𛁪𛁫𛁬𛁭𛁮𛁯
𛁰𛁱𛁲𛁳𛁴𛁵𛁶𛁷𛁸𛁹𛁺𛁻𛁼𛁽𛁾𛁿
𛂀𛂁𛂂𛂃𛂄𛂅𛂆𛂇𛂈𛂉𛂊𛂋𛂌𛂍𛂎𛂏
𛂐𛂑𛂒𛂓𛂔𛂕𛂖𛂗𛂘𛂙𛂚𛂛𛂜𛂝𛂞𛂟
𛂠𛂡𛂢𛂣𛂤𛂥𛂦𛂧𛂨𛂩𛂪𛂫𛂬𛂭𛂮𛂯
𛂰𛂱𛂲𛂳𛂴𛂵𛂶𛂷𛂸𛂹𛂺𛂻𛂼𛂽𛂾𛂿
𛃀𛃁𛃂𛃃𛃄𛃅𛃆𛃇𛃈𛃉𛃊𛃋𛃌𛃍𛃎𛃏
𛃐𛃑𛃒𛃓𛃔𛃕𛃖𛃗𛃘𛃙𛃚𛃛𛃜𛃝𛃞𛃟
𛃠𛃡𛃢𛃣𛃤𛃥𛃦𛃧𛃨𛃩𛃪𛃫𛃬𛃭𛃮𛃯
𛃰𛃱𛃲𛃳𛃴𛃵𛃶𛃷𛃸𛃹𛃺𛃻𛃼𛃽𛃾𛃿
𛄀𛄁𛄂𛄃𛄄𛄅𛄆𛄇𛄈𛄉𛄊𛄋𛄌𛄍𛄎𛄏
𛄐𛄑𛄒𛄓𛄔𛄕𛄖𛄗𛄘𛄙𛄚𛄛𛄜𛄝𛄞


「生𛁛𛂦゙」「生そば」

「天𛂱゚𛃭」「天ぷら」

「𛁈る𛀸」「しるこ」

\end{document}
```

**Comment by t-tk** [comment]
和文vf の fallback について、若干の機能拡張をしたいと思います。

「MAPFONTで指示されているfont IDの一番若いものがJFMであるとき、要求されたコードポイントが明言されていな場合は，それが最小の font ID に属し，かつそのコードポイントそのものを出力する」『文字コードを維持したまま、最初のJFM のフォント名を、かつJFMのchar_type 0番にメトリックスを割り当てる』
とこのIssueの冒頭に書きました。
その拡張として、

1. JFMではなく、「JFM風に使いたいOFM」の場合も同様にする
2. 『文字コードを維持したまま、最初のJFM/OFM のフォント名かつJFM/OFMでの同じ文字コードのメトリックスに、メトリックスを割り当てる』

の二つです。

(1)は、JFMよりも優先でOFMが読み込まれる場合があり、その時にもfallback機構を使いたいから、
(2)は、JFMのchar_type 0番ではなく、fallback先のJFM/OFMで規定されている文字幅にすることで、半角カナやCIDの1/2,1/3,1/4幅などにも対応可能にしたいから、です。

Ref.
[[dvips] pTeXの和文用TFM(JFM)をOFMに優先させる?](https://github.com/texjporg/tex-jp-build/issues/134#top)
[otf-cjXX-X.ofm は何のため？](https://github.com/texjporg/japanese-otf-mirror/issues/15#top)

dvipdfmx, dvips は期待通り動いているようなので、TeX Live svnにコミットする方向で考えています。

**Comment by t-tk** [comment]
dvipdfmx: TeX Live svn コミット済み [r66965](https://tug.org/svn/texlive?view=revision&revision=66965)
dvips: TeX Live svn コミット済 [r66966](https://tug.org/svn/texlive?view=revision&revision=66966)

dvisvgm: submitted a request to the dvisvgm repo at github.
[Virtual font fallback to OFM for pTeX](https://github.com/mgieseki/dvisvgm/issues/241#top)

**Comment by t-tk** [comment]
Support by dvisvgm have done:
https://github.com/mgieseki/dvisvgm/commit/2ab9ee2954bcd94d08fd053adb568931503415c9

ここは閉じます。
